### ISSUE TITLE
Safari: Update Native app with Become a Contributor copy

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1021]

**Comment by smalluban** [comment]
<img width="512" alt="Zrzut ekranu 2023-03-10 o 11 29 33" src="https://user-images.githubusercontent.com/1906677/224292971-9fe1cff8-f99b-48c2-b809-2529048bd742.png">
<img width="512" alt="Zrzut ekranu 2023-03-10 o 11 29 28" src="https://user-images.githubusercontent.com/1906677/224292980-e4437342-9060-4b0c-ba66-cca1d71bd507.png">

Please provide a new copy for the subscription view - I assume that on the main we change "Subscribe now" to "Become a contributor".

**Comment by yokoffing** [comment]
@smalluban I was trying to find this in Figma, but no luck. If there isn't a link, I can make comments on here?

**Comment by smalluban** [comment]
I think it is not in Figma, that's why I attached the screenshots above.

**Comment by mdsandu** [comment]
@yokoffing  
This can be updated really quickly
screen 1: Subscribe now --> Become a Contributor 
screen 2: button Restore subscription --> Restore donation 
Support our mission for ...--> Become a Contributor and support our mission....
Choose a subscription plan --> Chose the most convenient method for you to support Ghostery. 

Yearly donation
Monthly donation

I think for 👆 we have no room to play as it's just provided by apple - if you want check the screen below 


![Image](https://user-images.githubusercontent.com/116146386/231507534-0442818c-2cd9-492e-acfb-bb72e46f9c2b.png)

other than that in the last sentences - we can just exchange subscription with donation. 
premium features we call now: "extra privacy features and benefits." please use the same wording as on the website 

where should we put this best for you to implement @smalluban ?

**Comment by smalluban** [comment]
> where should we put this best for you to implement @smalluban ?

It can be here in the issue, just as a list of strings, and some pointers on which they replace.

**Comment by mdsandu** [comment]
@yokoffing do you create the strings? the text is above. thanks

**Comment by yokoffing** [comment]
Here's the working draft and a few ideas. Team is reviewing on Friday: https://docs.google.com/document/d/1q_AnS0iueACx-lHPutOHeQOQT9Ki_0OkpDvGajrTaQo/edit

**Comment by yokoffing** [comment]
@smalluban Here's the final changes: https://docs.google.com/document/d/1FqHUxcI_1ChlLfmq1E2HhXtYR07matolJ3gRqBdpLzw/edit.

We're sticking with minor adjustments for now, but eventually we'll want to do a total redesign.
