### ISSUE TITLE
Finalise Ghostery settings designs and copy

### ISSUE THREAD

**Issue by kalinme** [ghostery/ghostery-extension#1033]
List of changes:

- [ ] [copy] use plural type for ‘Permissions required’ : https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15440&t=LM9hP7Hx9S5sMCxM-1
- [ ] [copy] remove dot in ‘We make privacy easy’ onboarding header: https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15384&t=LM9hP7Hx9S5sMCxM-1
- [ ]  add learn more linking to blog post in Anti-Tracking part  https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15031&t=LM9hP7Hx9S5sMCxM-1 
- [ ] WhoTracks me setting changes: https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15277&t=LM9hP7Hx9S5sMCxM-1 
-- [ ] add link to manifesto
-- [ ] add new thumbnail and modal illustration for WhoTracks.Me Wheel
-- [ ] add new thumbnail and modal illustration for Trackers Count

---

Final comments are in Figma https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15031&t=fH9eRe6tbipSSH84-0

**Comment by kalinme** [comment]
@chrmod let me know if these thumbnails and images are more clear or we need still something else? https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1156%3A24693&t=LM9hP7Hx9S5sMCxM-1

**Comment by chrmod** [comment]
@yokoffing Can you please review the setting copy https://www.figma.com/file/GIWeYHGf3bUQzCd3LK9VmL/Ghostery-Panel?node-id=1024%3A15031&t=HJ73VXD3PuSv6YeT-0

**Comment by yokoffing** [comment]
@chrmod I have reviewed. Let me know how you want to move forward. There's still one or two I'm unsure of.

**Comment by chrmod** [comment]
Lets go with the current version
