### ISSUE TITLE
Paused Ghostery still blocking ads on Youtube

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1034]
**Description**
After setting pause the Ghostery on the Youtube webpage, the ads are still visible. 

**Steps to Reproduce**
1. Open http://www.youtube.com and search for any video, for example type investing
2. Select video (for example: https://www.youtube.com/watch?v=5RJF9G0FECs) and turn it on
![Ghostery-not-paused_Ads blocked](https://user-images.githubusercontent.com/40433708/219614122-da775a80-7288-40e8-8d18-d2a9aa152e9f.png)
3. Pause the Ghostery and wait for the reload - no ads are visible
![Ghostery-paused_Ads still blocked](https://user-images.githubusercontent.com/40433708/219614344-e54f5825-818b-4787-aeea-305686a34f08.png)
4. Unpause, turn off ad-blocking then wait for the reload - ads are visible
![Ad-blocking-off_Ads not blocked](https://user-images.githubusercontent.com/40433708/219614481-14e89be2-d4aa-4fe3-b743-16530aad32f8.png)

**Expected Results:**
When the Ghostery is paused, scripts should be turned off and ads should be visible on the webpage.

**Versions:**
Browser: Chrome 110.0.5481.100
OS: Windows 10 Pro 19045.2604
GBE 8.9.9

**Comment by smalluban** [comment]
Is this still valid? Please close re-open if so.
