### ISSUE TITLE
[MV2] Detected tracker URLs broken `gcache.ghostery.com`

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#1045]
Fix or hide **Detected tracker URLs** hyperlink.

![gcache1](https://user-images.githubusercontent.com/11689349/222225662-117bb0e6-3dd2-44e9-98bc-dc0b4da4cca3.png)

![gcache2](https://user-images.githubusercontent.com/11689349/222225692-3d863128-f57f-4ca7-ac87-69ce0a7a7afb.png)

**Comment by chrmod** [comment]
fixed by https://github.com/ghostery/ghostery-extension/pull/1109
