### ISSUE TITLE
100% CPU usage on Raspberry Pi OS

### ISSUE THREAD

**Issue by jimis** [ghostery/ghostery-extension#1046]
I'm running the default (as installed via apt) Firefox-ESR browser on Raspberry Pi OS.
My profile is new, but it has synced many bookmarks and tabs from Firefox Sync. However I have no open tabs on this device, besides the one I'm writing in now.

I have installed only one extension, Ghostery, in order to make browsing snappier on this slow device.

What I notice is that the `WebExtensions` process of Firefox consumes constantly 100% of one core, and the browsing feels sluggish. CPU usage doesn't seem to go down even after 30min or so. It only goes down when I disable Ghostery.

### Versions

+ Ghostery: 8.9.8
+ Browser: Firefox 102.8.0esr (32-bit armhf)
+ OS: Raspberry Pi OS (32-bit) running on Raspberry Pi 400

**Comment by jimis** [comment]
Is there a way to take a stacktrace of Ghostery, maybe using Firefox developer tools or javascript console? It might show in what loop it's stuck.

**Comment by jimis** [comment]
I followed this guide [1] and managed to get some info: stopping the secondary thread `worker.asmjs.bundle.js` releases the CPU. The "copy stacktrace" selection results only in this:
```
onmessage (moz-extension://3cec0a9c-094e-4067-830e-7494d6659c7d/common/hpnv2/worker.asmjs.bundle.js#135)
```

[1] https://extensionworkshop.com/documentation/develop/debugging/#debugging-content-scripts

**Comment by philipp-classen** [comment]
The logs are showing WhoTracks.me messages being sent, but the signing step is slow (the hpnv2 protocol is described in https://0x65.dev/blog/2019-12-04/human-web-proxy-network-hpn.html). It should normally take in the order of 10 ms, but according to the logs is taking around one minute.

The crypto operation (https://github.com/whotracksme/anonymous-credentials) should be using WebAssembly, but that you are seeing "worker.asmjs.bundle.js" may indicate that it is using instead the fallback to asm.js (https://en.wikipedia.org/wiki/Asm.js). And apparently, the JavaScript engine doesn't even apply asm.js optimizations but runs it as standard JavaScript, which is super slow.

Do you know if the `javascript.options.wasm` and `javascript.options.asmjs` options are enabled (in about:config)? It should be enabled by default, but maybe not on Raspberry Pi. We'll also try to reproduce.

**Comment by jimis** [comment]
> Do you know if the javascript.options.wasm and javascript.options.asmjs options are enabled (in about:config)? It should be enabled by default, but maybe not on Raspberry Pi.

Both configuration options are set to `true`.

I wonder if Firefox just doesn't support JIT compilation of javascript on armhf.

**Comment by jimis** [comment]
Can I disable signing or sending of these messages?

**Comment by jimis** [comment]
I searched a lot but couldn't find a way to get spidermonkey's status or enabled features. I still wonder if JIT compilation is even enabled.

**Comment by jimis** [comment]
I get `? - Detection unavailable` on all lines, except two of them that I get `X - Not supported`. Not a single tickmark anywhere.

**Comment by philipp-classen** [comment]
Quick update: we confirmed that wasm and even the fallback to asm.js is not working. From the logs:
```
asm.js type error: Asm.js optimizer disabled because no suitable wasm compiler is available
````

If we can find a way to reliably detect the scenario, we can implement a mitigation (e.g. use the code as on Mobile devices that don't rely on the availability of wasm/asm.js).

**Comment by jimis** [comment]
Thanks for the fix!

I tried the 64-bit Raspberry Pi OS, and WASM is working fine there. I wonder what the deal is on `armhf`.

**Comment by philipp-classen** [comment]
@jimis Don't know either. But thanks again for letting us know! I wasn't aware that wasm (and even asm.js) may not be able on Desktop browsers. That is something that we have to keep in mind. Though technically asm.js code is valid JavaScript, on non-optimizing JavaScript interpreters it is so slow that performance bugs are to be expected. Thus, falling back to JavaScript works in theory but not in practice

**Comment by chrmod** [comment]
@jimis At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!
