### ISSUE TITLE
Additional permission is needed to work on just opened webpage

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1088]
**Description**
After the instalation and before the onboarding, Ghostery Extension need additional permission to work on webpage. One permission to work on just opened webpage, second permission to work on https://ghostery.com - even if I do not opened it yet. 

**Preconditions**
Cache and all permissions must be deleted. 

**Steps to Reproduce**
1. Open any webpage, for example https://cnn.com
2. Install Ghostery Extension
3. Open Safari and wait for the onboarding.
4. Close or just change the tab - do not finish the onboarding - switch to the webpage from step 1
5. Wait for the question to gain access for the Ghostery to work on this page (from step 1) and select to work **only** on this webpage
6. Press the puzzle icon on the right side of the address bar to open settings
7. Press on the Ghostery Icon to open the panel.
8. Wait for the question to gain access for the Ghostery to work on https://ghostery.com
 
![image](https://user-images.githubusercontent.com/40433708/227520882-1a2ab1b6-bae3-45f1-a82c-8eac417a2609.png)

**Expected Results:**
After the installation and before the onboarding, Ghostery Extension need permission to work only on just opened webpage.

**Versions:**
Browser: Safari
OS: iPhone iOS 16.3.1
GBE 10.0.3

**Comment by smalluban** [comment]
I think it is expected behavior as we read cookies from ghostery.com - so even if you did not open the page, we need access to its data. @chrmod ?
