### ISSUE TITLE
Ghostery panel is shifted to the left side

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1099]
**Description**
Almost whole UI is shifted to the left side.

**Steps to Reproduce**
1. Open any webpage, for example https://tasty.co
2. Click on the URL and open Ghostery
![IMG_0150](https://user-images.githubusercontent.com/40433708/229159917-4bf85cad-e2ac-4f7f-a3f7-85b008003a1d.PNG)

**Steps to Reproduce**
1. Open any webpage, for example https://tasty.co
2. Click on the URL and open Ghostery
![IMG_0145](https://user-images.githubusercontent.com/40433708/229160137-0d32e487-47f4-4b0d-9a69-182da2e6d6de.PNG)

**Expected Results:**
UI should always looks according to the design.
![IMG_0151](https://user-images.githubusercontent.com/40433708/229159929-22a44a3d-4851-45de-9229-420a9574304d.PNG)

**Versions:**
Browser: Safari
OS: iPhone iOS 16.4
GBE 10.0.6

**Comment by smalluban** [comment]
@GRadziejewski Please try to reproduce with 10.0.7 (91) - It contains updated hybrids with a possible fix (https://github.com/hybridsjs/hybrids/commit/04d1fa96aff31e13fa57175d4b5c80e2cc8f7179)

**Comment by smalluban** [comment]
It looks like it is a Safari bug - https://bugs.webkit.org/show_bug.cgi?id=254844
