### ISSUE TITLE
Release 8.10.0

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1114]
Changelog:
* #1051
* #1104
* #1108 
* #1109
* #1110
* #1111 
* #1112 
* #1119 
* #1125 
* #1126 
* #1127 
* #1128 
* #1134

**Comment by GRadziejewski** [comment]
1. [] Performed Smoke tests on desktop version:
- Browser: 

2. [] Performed Smoke tests on mobile version:
- Browser: 

3. [] Checked bugfixes. 
- 

4. [] Checked PR change requests.
- #

New issues:
-

**Comment by chrmod** [comment]
New builds with:
* #1125 
* #1126 
* #1127 
* #1128 

[ghostery-chrome-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11295351/ghostery-chrome-v8.10.0.zip)
[ghostery-dawn-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11295355/ghostery-dawn-v8.10.0.zip)
[ghostery-edge-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11295361/ghostery-edge-v8.10.0.zip)
[ghostery-firefox-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11295362/ghostery-firefox-v8.10.0.zip)
[ghostery-opera-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11295363/ghostery-opera-v8.10.0.zip)

**Comment by GRadziejewski** [comment]
# Iteration nr 3.

## Smoke tests on desktop

- [ ] Browser: Firefox 112.0.1
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Chrome 112.0.5615.138
  OS: Windows 10 Pro 22H2 19045.2728
  GBE 8.10.0

- [ ] Browser: Opera 98.0.4759.6
  OS: Windows 10 Pro 22H2 19045.2728
  GBE 8.10.0

- [ ] [ In progress ] Browser: Edge 112.0.1722.46
  OS: Windows 10 Pro 22H2 19045.2728
  GBE 8.9.15

- [ ] Browser: Ghostery Private Browser 2023.1 (c41d1b9)
  OS: Windows 10 Pro 22H2 19045.2728
  GBE 8.9.12


## Smoke tests on mobile

- [ ] Browser: Firefox 

## Checked PRs / bugfixes

- 

## New issues

-

**Comment by chrmod** [comment]
Pre-release builds from revision 366eb3e4c1daaa467c87acbe66bf26f0a6fb8dc2:

* [ghostery-edge-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11310855/ghostery-edge-v8.10.0.zip)
* [ghostery-firefox-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11310858/ghostery-firefox-v8.10.0.zip)
* [ghostery-opera-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11310859/ghostery-opera-v8.10.0.zip)
* [ghostery-dawn-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11310853/ghostery-dawn-v8.10.0.zip)
* [ghostery-chrome-v8.10.0.zip](https://github.com/ghostery/ghostery-extension/files/11310852/ghostery-chrome-v8.10.0.zip)

Changelog:
* #1134 that fixed #1130 and #1133

**Comment by GRadziejewski** [comment]
# Iteration nr 4.

## Smoke tests on desktop

- [ ] Browser: Firefox 112.0.1
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] [ In progress ] Browser: Chrome 112.0.5615.138
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Opera 98.0.4759.6
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Edge 112.0.1722.46
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Ghostery Private Browser 


## Smoke tests on mobile

- [ ] Browser: Firefox 

## Checked PRs / bugfixes

## New issues

**Comment by GRadziejewski** [comment]
# Iteration nr 5.

## Smoke tests on desktop

- [ ] [ In progress ] Browser: Firefox 112.0.1
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Chrome 112.0.5615.138
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Opera 98.0.4759.6
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Edge 112.0.1722.46
  OS: Windows 10 Pro 22H2 19045.2846
  GBE 8.10.0

- [ ] Browser: Ghostery Private Browser 


## Smoke tests on mobile

- [ ] Browser: Firefox 

## Checked PRs / bugfixes

## New issues

**Comment by GRadziejewski** [comment]
Tests are finished.

**Comment by chrmod** [comment]
Release builds are ready. We will start rollout soon.

https://github.com/ghostery/ghostery-extension/releases/tag/v8.10.0
