### ISSUE TITLE
Subscription instead of Donation

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1144]
**Description**
On the donation page there is Monthly / Yearly Subscription.

**Steps to Reproduce**
1. Open Finder / Application
2. Open Ghostery - Privacy Ad Blocker
3. Click on "Become a Contributor" button
4. There is Monthly / Yearly Subscription.
![Screenshot 2023-04-26 at 14 55 03](https://user-images.githubusercontent.com/40433708/234834660-8827a38a-761f-4227-84c6-e7e17ba35c97.png)

**Expected Results:**
On the donation page there must be Monthly / Yearly Donation.

**Versions:**
Browser: Safari 16.3 (18614.4.6.1.6)
OS: MacOS Ventura 13.2.1
GBE 10.0.8

**Comment by smalluban** [comment]
Fixed in App Store Connect panel.
