### ISSUE TITLE
Ghostery doesn't work when download from microsoft edge store

### ISSUE THREAD

**Issue by vilmarap** [ghostery/ghostery-extension#1151]
### Description

Hello everyone.

When I tried downloading the ghostery from the [microsoft edge store](https://microsoftedge.microsoft.com/addons/detail/ghostery-%E2%80%93-bloqueador-de-/fclbdkbhjlgkbpfldjodgjncejkkjcme) the extension does not work. I received a blank screen from ghostery.

![image](https://user-images.githubusercontent.com/33360699/236345783-5083050b-ea15-4895-9156-7695bf440f5c.png)

### Steps to Reproduce

1. If I make a download from [google chrome store](https://chrome.google.com/webstore/detail/ghostery-%E2%80%93-privacy-ad-blo/mlomiejdfkolichcflejclcbmpeaniij/related?hl=en-US) the extension works well. 
 
2. After installation from google chrome store, I can accept and enable ghostery. But in microsoft I don't have this option. 

![image](https://user-images.githubusercontent.com/33360699/236345827-cf4e9f08-5741-4ea7-ab08-9b67c02a262a.png)

![image](https://user-images.githubusercontent.com/33360699/236345840-d3b6d241-a063-4b75-abda-6b0ff9b2dd10.png)

### Versions

+ Browser: Microsoft Edge
Version 112.0.1722.68 (Official build) (64-bit)
+ OS: Windows 10 19045.2846

**Comment by DevDorrejo** [comment]
Same issue

- Edge: 112.0.1722.68
- Windows: Windows 11 Enterprise 22621.1635

![image](https://user-images.githubusercontent.com/7697566/236362791-87ae6591-6ba6-4d1b-ba98-1fefdbe7e342.png)

**Comment by chrmod** [comment]
Update: a new version with a fix was submitted to Opera and Edge extension stores. The extension will work as expected with release [v8.10.1](https://github.com/ghostery/ghostery-extension/releases/tag/v8.10.1)


@vilmarap @FaznetSolutions @callie519 At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!

**Comment by callie519** [comment]
Thank you. I downloaded it from  google chrome and it works perfectly.
________________________________

**Comment by chrmod** [comment]
Closing the issue for now but will keep it pinned for a moment in case anyone else is still on the broken version.

Once again, thank you all for reporting and your support, it's great to have you around!
