### ISSUE TITLE
Suppress second confirmation dialog on never-consent

### ISSUE THREAD

**Issue by dl12345** [ghostery/ghostery-extension#1159]
Each time one visits a new site when never-consent is enabled, there is first a dialog to ask if you want to apply never-consent to this website, followed by another confirming it has been applied and can be unset.

This behaviour is arguably as bad, if not worse, than having to click a single don't-consent banner. The second dialog is completely unnecessary and quite irritating. Please suppress it or give the user the option to suppress it in the settings.

**Comment by smalluban** [comment]
Hi @dl12345! The current flow allows you to check the radio with the setting `on all websites`, so the popup is shown only once - and you are confirming that you want the extension to work for you on all sites. If you set so, the popup shows the confirmation of the choice (is this the second popup that you have meant?). However, the flow in that case is shown once to the user.

**Comment by smalluban** [comment]
@dl12345 Please re-open if you need more info about the feature.
