### ISSUE TITLE
Tab For a Cause Extension Blocked

### ISSUE THREAD

**Issue by Gregmed** [ghostery/ghostery-extension#118]
### Description

The adverts on my Tab For A Cause homepage are blocked from appearing

### Expected Behavior 

For the ads to be shown on this page so that I can generate revenue for the company

### Actual Behavior 

No adverts appear on the page

### Steps to Reproduce

1. Download the Tab For A Cause chrome extension
2. Set Tab For a Cause as your home page
3. Open a new tab

### Versions

+ Browser: Chrome
+ OS: Windows
+ Node: -
+ NPM: -

**Comment by christophertino** [comment]
The Tab For a Cause page is loading ~20 third-party tracking scripts.  Blocking these types of scripts is the fundamental value prop of Ghostery.  There's no way we can change that. 

What we can do is allow normal Ghostery functionality on extension pages (`chrome-extension://` and `moz-extension://`, plus Edge and Opera equivalents). This way your users can whitelist the new tab page like a regular site, if they chose to do so.
