### ISSUE TITLE
JavaScript errors thrown from Ad Blocker when referencing unescaped XPath

### ISSUE THREAD

**Issue by bradleyv8** [ghostery/ghostery-extension#1195]
We're seeing JavaScript exceptions being thrown from the Ghostery browser extension ad blocker when visiting domains that have ad-blocker config using an XPath query that contains quotes. It seems like something is taking ad blocker config and putting this in an array as strings and adding surrounding quotes. If the String already contains quotes, these are not escaped and JavaScript errors result. This is currently happening for all amazon.com domains.

The following is present in `<script-cliqz-adblocker-script>`

`["xpath(//*[name()="Period"][.//*[name()="SupplementalProperty"][@value="Ad"]])","",".mpd","{{4}}","{{5}}","{{6}}","{{7}}","{{8}}","{{9}}","{{10}}"]`

The XPath in question seems to originate from https://github.com/uBlockOrigin/uAssets/blob/8e92d5737794a98cb7d375bc00bd9b36de3fdff4/filters/filters.txt#L11460. There's nothing wrong with the XPath as originally specified, the issue is introduced when it's added to an array as a string surrounded by additional quotes.

On Chrome the error manifests as `"Uncaught SyntaxError: Unexpected identifier 'Period'"`
On Firefox the error manifests as `"SyntaxError: missing ] after element list"`

To repro, visit www.amazon.com with the Ghostery browser extension installed and see the above errors in your dev tools console.

**Comment by chrmod** [comment]
This is the breaking rule `amazon.com##+js(xml-prune, Period:\has([value="Ad"]), , .mpd)`

**Comment by chrmod** [comment]
@bradleyv8 we've just rolled out a fix to all users. 

Please update your Tracker list in Ghostery settings
<img width="581" alt="Screenshot 2023-06-13 at 11 48 09" src="https://github.com/ghostery/ghostery-extension/assets/1228153/67b5215e-af65-4129-9d47-752f3f0e6151">

Can you confirm if the fix works?

**Comment by bradleyv8** [comment]
Confirmed I'm no longer seeing the error after updating to the latest version. Thanks for the quick fix!
