### ISSUE TITLE
Firefox Blocked Add-on Ghostery vs. 8.2.0

### ISSUE THREAD

**Issue by caseyjayner** [ghostery/ghostery-extension#120]
### Firefox #Block #Ghostery 

When I try to click the link to install Ghostery, Firefox blocks the add-on.  It sends me to this site for more information: https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by christophertino** [comment]
If you're trying to load a build from our GitHub releases, you need to visit [about:debugging](about:debugging) in Firefox, turn on add-on debugging and then Load Temporary Add-on.  This is just for test/debug purposes.  For production Ghostery, you need to install it from the FF [store](https://addons.mozilla.org/en-US/firefox/addon/ghostery/).

**Comment by Aziz-Ghostery** [comment]
If you'd like to install the extension in Developer mode:
Unpack the extension in a folder 
Navigate to: about:debugging#addons
load temporary Add-on then specify the folder above.
