### ISSUE TITLE
DevTools failed to load source map

### ISSUE THREAD

**Issue by bechtold** [ghostery/ghostery-extension#1200]
Hey,
in my dev tools console, I keep on getting these warnings:
`DevTools failed to load source map: Could not load content for chrome-extension://mlomiejdfkolichcflejclcbmpeaniij/dist/content_script_bundle.js.map: System error: net::ERR_BLOCKED_BY_CLIENT`

This is quite annoying and distracting while I develop other stuff.
Could you please remove the links to the source maps or include them in the shipped version, so the warnings go away?
Thank you 🙏

![Screenshot 2023-06-14 at 16 41 21](https://github.com/ghostery/ghostery-extension/assets/1275950/ec1226d3-1107-4e06-a242-270cebdf87c2)

**Comment by chrmod** [comment]
Thank you for reporting. I can confirm it is not desired and we will remove the problem with next release.

At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!

**Comment by smalluban** [comment]
The last platform migrated to v10.
