### ISSUE TITLE
German translation issue

### ISSUE THREAD

**Issue by FrankOnGit** [ghostery/ghostery-extension#121]
### Description

German translation issue:
The phrase "Navigate to another page and I promise I'll deliver the goods." cannot be directly translated to "Navigieren Sie zu einer anderen Seite und ich verspreche, dass ich liefern werde."

### Expected Behavior 

I don't speak English good enough to understand the meaning of "deliver the goods", so please ask somebody else for the correct translation.

### Actual Behavior 

[What actually happened]

### Steps to Reproduce

1. [First Step]
open source code github.com/ghostery/ghostery-extension/blob/master/_locales/de/messages.json on line 456
2. [Second Step]
replace "dass ich liefern werde" using something ordinary

**Comment by christophertino** [comment]
This will be in the 8.2.1 release.
