### ISSUE TITLE
Android Panel: All categories are "blocked" when only Advertising was selected on Global Blocking tab

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1222]
**Description**
When only "Advertising" category will be selected to be blocked on Global Blocking tab, all trackers from "Site Blocking" tab would be "blocked". After refreshing "Site Blocking" tab looks correct.

**Steps to Reproduce**
1. Open any website, for example https://aarp.org
2. Open Ghostery panel
3. Open Site Blocking tab to check what is blocked right now
4. Open Global Blocking tab and block only Advertising category
5. Open Site Blocking tab again to check what is blocked right now
6. Refresh the website and open Ghostery / Site Blocking tab again.

https://github.com/ghostery/ghostery-extension/assets/40433708/ecc0b4b5-b8d9-40da-9628-66bbd0d60119

 Expected results
When only "Advertising" category will be selected to be blocked on Global Blocking tab, all trackers from "Site Blocking" tab cannot be blocked.

Versions
Browser: Firefox 114.2.0 (Build #2015957435)
OS: Android 13
GBE 8.10.3

**Comment by smalluban** [comment]
The last platform migrated to v10.
