### ISSUE TITLE
DNR lists hit the limit

### ISSUE THREAD

**Issue by smalluban** [ghostery/ghostery-extension#1227]
I can't find more reliable information about it than this site: https://webkit.org/blog/11727/release-notes-for-safari-technology-preview-126-with-safari-15-features/, which claims about the limit of 150k rules. However, the error in the background process shows that we cannot turn on all three lists at once.

**Comment by smalluban** [comment]
After an investigation of the problem, there is sadly no good news. Safari does not support `|` in `regexFilter`, and `domains` does not work as we would like to - it indicates the origin of the request, not the domain of the request itself (this is why they introduce `requestDomains` - but this is of course not supported in Safari). It means, there is no way currently to change the structure to minimize the amount of rules.

This is not written anywhere, but I think when Safari is compiling rules, it must make more of them than we have in the lists, so we hit the limit even though in DNR lists there are approx. 75k.

**Comment by smalluban** [comment]
The `requestDomains` should work from 16.4, but when I was testing, it didn't work.

**Comment by chrmod** [comment]
@smalluban does this happen on both desktop and mobile? What is the exact error in the console?

**Comment by smalluban** [comment]
@chrmod found this: https://github.com/WebKit/WebKit/blob/c85962a5c0e929991e5963811da957b75d1501db/Source/WebCore/contentextensions/ContentExtensionCompiler.cpp#L199

Creating dummy lists with generated rules confirms, that when 75k rules is reached, the error is thrown.

**Comment by smalluban** [comment]
As we have a temporary solution (removing rules with the `requestDomains` condition), I am closing the issue. We can re-open if needed.
