### ISSUE TITLE
Observed trackers "leak" between page loads

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1241]
**Description**
Tracker is visible on second website when I go to it strictly from the search engine website. After reloads, tracker disappears.

**Steps to Reproduce Scenario 1**
1. Open any search engine website, for example https://google.com
2. Open Devtools and switch to Network tab
3. Search for example example.com
4. Open Ghostery panel and look for Site Analytics/ Google Beacons. 
5. Copy "www.google.com/gen_204"
6. Search it in Network tab, from step 2
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/7d35e7e5-b303-47fc-9e5f-9a9804f48ceb)

7. Open [Example Domain](https://example.com/) and open Ghostery panel
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/e18c8acb-e9e9-4306-8467-ae573e933984)

8. **Tracker is still visible.**
9. Reload the website and open again Ghostery panel
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/fbc737f4-df81-4f20-bd4f-c477880abab1)

---

**Steps to Reproduce Scenario 2**
1. Open any search engine website, for example https://bing.com
2. Open Devtools and switch to Network tab
3. Search for example happy bab la
4. Open Ghostery panel and look for Advertising/ Bing Ads 
5. Copy "bing.com"
6. Search it in Network tab, from step 2
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/318a1bfc-2c1c-4944-bc06-5a93a0cb0bd0)

7. Open [HAPPY - Tłumaczenie na polski - bab.la](https://pl.bab.la/slownik/angielski-polski/happy) and open Ghostery panel
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/305b7121-bba4-4ef0-9083-66e6a94e2a31)

8. **Tracker is still visible.**
9. Reload the website and open again Ghostery panel
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/fbc737f4-df81-4f20-bd4f-c477880abab1)

**Expected results**
Tracker cannot be visible on second website when I go to it strictly from the search engine website. 

**Versions**
Browser: Chrome 115.0.5790.99 (Official Build) (64-bit)
OS: Windows 10 Pro 19045.3086
GBE: 8.11.1

**Comment by philipp-classen** [comment]
Confirmed on Firefox.

**Comment by chrmod** [comment]
This problem manifest itself on whotracks.me, for example:
https://whotracks.me/websites/glowstery.com.html
reports some google trackers which were never present on that page.

**Comment by philipp-classen** [comment]
Also on https://whotracks.me/websites/ghosterysearch.com.html

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.

**Comment by philipp-classen** [comment]
Fine to leave it closed, since I also cannot reproduce it anymore.

However, based on the data, it may still applies: https://www.ghostery.com/whotracksme/websites/ghosterysearch.com (wrongly showing Google Analytics)

We have this ticket open on WhoTracks.me to track that: https://github.com/whotracksme/whotracks.me/issues/333
