### ISSUE TITLE
Ghostery Blocking OneTrust Links

### ISSUE THREAD

**Issue by papagoosa** [ghostery/ghostery-extension#1242]
When Ghostery is active, our "Do Not Sell or Share My Personal Information" link does not show up on https://www.levi.com/US/en_US/ unless we manually change the class and ID of the DOM around the link.  Then it appears.  The link itself is injected via OneTrust script that is loaded via Google Tag Manager.

For me, our "Privacy Policy" link also disappears when Ghostery is enabled (which has nothing to do with OneTrust or any third party script), but it does not disappear for some other co-workers.

All testing so far has been done on Chrome.

**Comment by philipp-classen** [comment]
I have difficulties reproducing it. Without Ghostery, I see an "About Cookies" dialog on the bottom:

![dialog](https://github.com/ghostery/ghostery-extension/assets/1616509/1a22496f-def5-4fa1-adf5-b48f24ccefa1)

Is that the "Do Not Sell or Share My Personal Information" link? If not, can you please post a screenshot how you feel the page is supposed to look, and how it currently looks with Ghostery enabled?

Even better would be to open an issue here (and we can link it): https://github.com/ghostery/broken-page-reports

**Comment by GRadziejewski** [comment]
Reproduced and reported: https://github.com/ghostery/broken-page-reports/issues/336

**Comment by philipp-classen** [comment]
> For me, our "Privacy Policy" link also disappears when Ghostery is enabled (which has nothing to do with OneTrust or any third party script), but it does not disappear for some other co-workers.

Most likely, it depends on the settings. By default, Ghostery will not block Google Tag Manager; but if you block explicitly or turn on blocking of the essential category, it will be blocked. I think, that makes the difference whether the Privacy Policy is being shown (see the discussion on https://github.com/ghostery/broken-page-reports/issues/336)

**Comment by philipp-classen** [comment]
A fix should be coming with the next update of the block lists (can take up to 24 hours until clients update).

**Comment by papagoosa** [comment]
Thank you for the traction!  With the other thread open in a more appropriate location, I'll personally close this thread.
