### ISSUE TITLE
How to configure using policies.json in firefox?

### ISSUE THREAD

**Issue by shreyanshk** [ghostery/ghostery-extension#1243]
Hello,
I would like to do a Firefox deployment and would like to pre-configure the browser on the hosts. I was hoping to automate as much as possible and thus wanted to ask how I can automate configuring ghostery using policies.json . I can already get Firefox to install Ghostery automatically with policies.json file and now I am looking to automate the configuration part.
I tried look around a bit in the docs and the source code but that has been unsuccessful so far.

Please share if I am missing anything here. Any pointers would be useful.

Many thanks.

**Comment by smalluban** [comment]
The current version supports https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#managed_storage_manifests
You can find available options here: https://github.com/ghostery/ghostery-extension/blob/main/src/managed_storage.json
