### ISSUE TITLE
Ghostery panel do not open

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1244]
**Description:**
Clicking the Ghostery button has no effect (the number of trackers blocked are also not listed alongside)

**Steps to Reproduce:**
1. Open https://www.youtube.com/
![RackMultipart20230725-36-p617pr](https://github.com/ghostery/ghostery-extension/assets/40433708/7ba77f05-c27e-4010-9558-ac810ccbd31d)

**Expected Results:**
Clicking the Ghostery button should opens Ghostery panel.

**Versions:**
Browser: Firefox
OS: 
GBE 8.11.0

**Comment by chrmod** [comment]
as 8.11.1 is already available for Firefox I'm closing this issue as potentially obsolete

**Comment by GRadziejewski** [comment]
Reopened. Version of Ghostery Browser Extension updated.

It was reported as: 8.11.1.

Regardless of the version, I cannot reproduce it neither on 8.11.0 nor 8.11.1.
