### ISSUE TITLE
Missing translation in the settings

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1245]
<img width="1512" alt="Screenshot 2023-08-02 at 18 31 40" src="https://github.com/ghostery/ghostery-extension/assets/1228153/21dc0db0-9c53-4dab-a3c8-3518bcd93048">

**Comment by smalluban** [comment]
I'm not sure what you'd like to do here. The translations from Sync feature are in messages - https://github.com/ghostery/ghostery-extension/blob/main/extension-manifest-v3/src/_locales/en/messages.json#L217.

We did not translate those in Transifex (and didn't push to it - it is done semiautomatically when you create a release branch).

**Comment by chrmod** [comment]
oh, if it is new, than the issue can be closed
