### ISSUE TITLE
Trackers Preview is not shown on search results

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1248]
**Description:**
Trackers Preview is not shown on search results.

**Steps to Reproduce:**
1. Open https://google.com
2. Enter any query and search for it
3. Look for Trackers Preview
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/d7bbc946-b17c-46ff-80eb-bc93aabeed55)
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/7cf30767-25ee-427a-b45c-fa54dee34499)

**Expected Results:**
Trackers Preview must be visible on search results

**Versions:**

	Browser: Firefox 117.0b4 (64-bit)
	OS: Windows 10 Pro 19045.3208
	GBE 8.11.1

	Browser: Chrome 115.0.5790.102 (Official Build) (64-bit)
	OS: Windows 10 Pro 19045.3208
	GBE 8.11.0

	Browser: Opera One (101.0.4843.33)
	OS: Windows 10 Pro 19045.3208
	GBE 8.11.0

	Browser: Edge 115.0.1901.200 (Official build) (64-bit)
	OS: Windows 10 Pro 19045.3208
	GBE 8.11.0

	Browser: Safari 16.6 (18615.3.12.11.2)
	OS: MacOS Ventura 13.5
	GBE 10.1.0

**Comment by smalluban** [comment]
Fixed in`@whotracksme/webextension-packages` 3.0.2, but currently it can't be updated, as there is another bug in newest version: https://github.com/whotracksme/webextension-packages/issues/50

**Comment by smalluban** [comment]
Fixed in `v10.1.2`
