### ISSUE TITLE
Facebook.com: Sponsored ads not blocked

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1264]
**Description:**
"Sponsored" ads and "Suggested for you" are visible on Facebook website.

**Steps to Reproduce:**
1. Open https://facebook.com and log in.
2. Just scroll down and look for any sponsored ads, for example: 
![image](https://github.com/ghostery/broken-page-reports/assets/40433708/d084e624-bc8c-4214-b156-842ab311ed37)
![image](https://github.com/ghostery/broken-page-reports/assets/40433708/b27bf314-08ae-49dc-8030-762da4b9175d)
![image](https://github.com/ghostery/broken-page-reports/assets/40433708/107cd160-a7e3-4e56-8501-3c4f3b6e6e75)
![image](https://github.com/ghostery/broken-page-reports/assets/40433708/53edf422-196a-4756-bdb6-2612342c2018)

**Expected Results:**
"Sponsored" ads and "Suggested for you" should be blocked. 

**Versions:**

	Browser: Firefox 116.0 (64-bit)
	OS: Windows 10 Pro 19045.3086
	GBE 8.11.1

	Browser: Chrome 115.0.5790.102 (Official Build) (64-bit)
	OS: Windows 10 Pro 19045.3086
	GBE 8.11.1

	Browser: Opera One (100.0.4815.76)
	OS: Windows 10 Pro 19045.3086
	GBE 8.11.1

	Browser: Edge 115.0.1901.183 (Official build) (64-bit)
	OS: Windows 10 Pro 19045.3086
	GBE 8.11.1

	Browser: Safari 16.5.2 (18615.2.9.11.)
	OS: MacOS Ventura 13.4.1 (c)
	GBE 10.0.14

**Comment by yokoffing** [comment]
Note that there are Sponsored posts and there are Suggested for You posts. uBO does not block the latter by default, but offers an custom filter to block it: https://www.reddit.com/r/uBlockOrigin/wiki/solutions/#wiki_facebook

<details><summary>Logger output</summary>

| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +130 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=29&__rev=1009496691&__s=%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +68 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=27&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +66 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=22&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +64 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1z&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +62 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1s&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +60 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1q&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +58 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1p&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +56 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1k&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +54 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1h&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +52 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1g&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +50 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=1e&__rev=1009496691&__s=g0zlpn%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3` |
| +48 | ##div[aria-posinset] :is(h3, h4) span > a[href]:not([href^="/groups/"]):not([href*="section_header_type"]):matches-attr(href="/__cft__\[0\]=[-\w]{270,}/"):upward(div[aria-posinset]) |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +6 | \|\|fbcdn.net^ | -- | `www.fbsbx.com` | 3,3 | get | script | `https://static.xx.fbcdn.net/rsrc.php/v3/yJ/r/V3XgN1l3wCx.js?_nc_x=Ij3Wp8lg5Kz` |
| +6 | \|\|fbcdn.net^ | -- | `www.fbsbx.com` | 3,3 | get | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yR/l/0,cross/cpqgTojwVjB.css?_nc_x=Ij3Wp8lg5Kz` |
| +6 | \|\|fbcdn.net^ | -- | `www.fbsbx.com` | 3,3 | get | css | `https://static.xx.fbcdn.net/rsrc.php/v3/yA/l/0,cross/GWkTLZI8Uwb.css?_nc_x=Ij3Wp8lg5Kz` |
| +5 | /ajax/bnzai?_ | -- | `www.facebook.com` | 1 | post | xhr | `https://www.facebook.com/ajax/bnzai?__a=1&__aaid=0&__ccg=GOOD&__comet_req=15&__hs=19656.HYP%3Acomet_pkg.2.1..2.1&__hsi=7294282117407780920&__req=n&__rev=1009496691&__s=281nlj%3Agik7ty%3Acmlep7&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332400&__user=100062746066785&dpr=1.5&fb_dtsg=NAcM840rvqyVnpLHWBXnH9bmJ5RqMCJ5jUPoJAG8nlbz5QvMwQgduyQ%3A39%3A1698332399&jazoest=25571&lsd=gms8yCIkkk54xroM0c9U-E&ph=C3&qpl_active_flow_ids=25305590` |
| +4 | ##div[role="complementary"] div:not([class]):not([id]) > span:not([class]):not([id]):not([aria-labelledby]) |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +4 | ##a[aria-label="Advertiser"] |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +4 | ##.sponsorPost |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +4 | ##.post-ads |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +4 | ##.AdBox |  | `www.facebook.com` |  | get | dom | `https://www.facebook.com/` |
| +1 | \|\|facebook.com/ajax/qm/ | -- | `www.facebook.com` | 1 | post | beacon | `https://www.facebook.com/ajax/qm/?__a=1&__user=100062746066785&__comet_req=15&jazoest=25571` |
| +1 | ##+js(trusted-set-cookie, datr, __GMZCgwVF5BbyvAtfJojQwg, 1year, , reload, 1) |  | `www.facebook.com` |  | post | scriptlet | `https://www.facebook.com/` |
| +1 | /ajax/bz?_ | -- | `www.facebook.com` | 1 | post | beacon | `https://www.facebook.com/ajax/bz?__a=1&__ccg=GOOD&__dyn=7xe6E5aQ1PyUbFuC1swgE98nwgU29zEdEc8uwdK0lW4o3Bw5VCwjE3awbG78b87C0yE7i0n24o5-0me2218w5uw5Uwdq0Ho2ewnE3fw6iw4vwbS1Lw4Cwcq&__hs=19656.BP%3ADEFAULT.2.0..0.0&__hsi=7294282031624906691&__req=5&__rev=1009496691&__s=281nlj%3Agik7ty%3Aj58qmd&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332380&__user=0&dpr=1&jazoest=2965&lsd=AVp1nhLlASk` |
| +1 | /ajax/bz?_ | -- | `www.facebook.com` | 1 | post | beacon | `https://www.facebook.com/ajax/bz?__a=1&__ccg=GOOD&__dyn=7xe6E5aQ1PyUbFuC1swgE98nwgU29zEdEc8uwdK0lW4o3Bw5VCwjE3awbG78b87C0yE7i0n24o5-0me2218w5uw5Uwdq0Ho2ewnE3fw6iw4vwbS1Lw4Cwcq&__hs=19656.BP%3ADEFAULT.2.0..0.0&__hsi=7294282031624906691&__req=4&__rev=1009496691&__s=281nlj%3Agik7ty%3Aj58qmd&__spin_b=trunk&__spin_r=1009496691&__spin_t=1698332380&__user=0&dpr=1&jazoest=2965&lsd=AVp1nhLlASk` |
</details>

**Comment by AdamGhst** [comment]
Checked 
On FF and Chrome
Both fon macOS and Win10. 

No ads or sposored posts.
