### ISSUE TITLE
the word "Explorer" is briefly displayed on blank pages on Firefox

### ISSUE THREAD

**Issue by SuperUserNameMan** [ghostery/ghostery-extension#13]
Hi,

### Description

When Ghostery plugin is activated under Firefox 59.0.x, the word "Explorer" is briefly displayed on online blank pages during refresh and also during javascript redirections.

I've noticed this bahavior on my WIP website, but also on random sites on the internet. (only online pages are affected. HTML page created on the desktop are not affected)

Note : when you refresh an empty web page with a dark background, there is also a white ghost that briefly appears at the top (probably caused by a lag with CSS).

### Steps to Reproduce

+ you can test it online with this blank page : https://terminajones.com/blank.html
+ just refresh many time.
+ if you don't notice it, try disabling "hardware acceleration" in Firefox (i've been forced to disable it because of nasty ridiculous display bugs since Firefox Quantum update), or try with a slower computer ...

### Versions

+ Browser: Firefox 59.0.x with Hardware acceleration OFF.
+ OS: Windows 8.1
+ CPU : AMD APU A6-6310 laptop
+ **LOCALE : Fr-Fr**

**Comment by SuperUserNameMan** [comment]
forgot to mention my locale is French

**Comment by SuperUserNameMan** [comment]
ok, after looking into the code repository, the word "Explorer" is only mentionned here : https://github.com/ghostery/ghostery-extension/blob/e5f9ef76829f74a77ea4c7e0d810e6432185d8a6/_locales/fr/messages.json#L202

so, it must be caused by a lag between the displaying of the ghostery HTML code and the interpretation of the CSS code by Firefox ...

so according to your language you'll see something else thant "Explorer" ...

the issue is then the "subliminal" effect.

**Comment by christophertino** [comment]
Interesting.  That's coming from the purple box counter.  If you disable purple box (Settings > Purple Box), does it go away? 

Looks like the "looking" text is displaying before the box fully renders. 

https://github.com/ghostery/ghostery-extension/blob/e5f9ef76829f74a77ea4c7e0d810e6432185d8a6/app/content-scripts/purplebox.js#L483

**Comment by SuperUserNameMan** [comment]
@christophertino : yep, when purple box is disabled, it goes away.
