### ISSUE TITLE
[BUG] many tabs -> memory overrun -> crash

### ISSUE THREAD

**Issue by Kochise** [ghostery/ghostery-extension#1304]
`sessionstore.jsonlz4` can be found zipped at https://bugzilla.mozilla.org/show_bug.cgi?id=1854392

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0

Steps to reproduce:

(before opening Firefox 117+, copy the `sessionstore.jsonlz4` into `Firefox/data/profile`)
Have many tabs opened (because why not).
Yet having another session in another window (currently closed).
Opening the second window (Ctrl+Shift+N).

Actual results:

Watch the memory getting overrun.
The more memory, the more overrun (64 GB gets filled just as well).
Then Firefox crash badly (may even affect computer, backup your work).

Expected results:

Open second window with its own set of tabs.
Without overrunning the memory, without crashing.
Quickly (not after a very long memory overrun).

Steps to reproduce bug:

0- Backup everything
1- Install Firefox (portable App as well) : https://portableapps.com/apps/internet/firefox_portable
2- Create `Firefox(Portable)/data/profile` folder
3- Unzip `sessionstore.jsonlz4` into `Firefox(Portable)/data/profile folder`
4- Open Firefox
5- Install needed certificates if behind proxy/VPN : about:preferences#privacy -> Certificates -> View Certificates... -> Authorities -> Import...
6- Install Ghostery : https://addons.mozilla.org/en-US/firefox/addon/ghostery/
7- Open second window : Ctrl+Shift+N
8- Watch your memory getting overrun and Firefox crash after a while

**Comment by chrmod** [comment]
@Kochise thank you the report - lets continue to discuss under the bugzilla ticket as it is not clear what's the source of the problem. It can be corrupted session, firefox of ghostery bug. Closing this issue until it will be confirmed.

**Comment by Kochise** [comment]
Indeed.
