### ISSUE TITLE
[Ghostery Control Panel] create appealing landing for non-existing WTM Statistical report

### ISSUE THREAD

**Issue by mdsandu** [ghostery/ghostery-extension#1331]
we don't have the whole web in WTM, so many pages will not be found by users. let's make the landing visually appealing and informative for the user offering some of the new facts we created for WTM main page and linking out to somewhere to learn more about WTM 

site like e.g.
https://www.whotracks.me/websites/whotracks.me.html
https://www.whotracks.me/websites/bisoubreton.com.html

starting point is:

![Image](https://github.com/ghostery/ghostery-extension/assets/116146386/27e1d683-4213-4797-97c3-d86d83ad2553)

now landing looks like: 

![Image](https://github.com/ghostery/ghostery-extension/assets/116146386/938c5a83-790c-4aa5-8190-915e04de0aab)

**Comment by chrmod** [comment]
To avoid the current situation we should be shipping a list of domain for which we have stats. This is no different from the list we ship with Trackers Preview.

**Comment by mdsandu** [comment]
the button should be removed from the UI @chrmod

**Comment by mdsandu** [comment]
on a second thought I think it brings more value to leave the page there(even if there is a solution to remove it) and populate it with great stats, great info about WTM and use it as a resource for users to learn more about WTM if they go to the panel anyways)

**Comment by smalluban** [comment]
Ok, so I leave it as it is. For the record, earlier we were checking if the page is not 404, but with the https://github.com/ghostery/ghostery-extension/commit/5e2ac38a1520b69b5acbf0c8393985f77bed5c69#diff-a76932ae38751c82a862adaa5a488620ec81df9d0e049742a7af20d4d30b0e64L29 I removed that check (sorry, I can't remember why :P).

**Comment by mdsandu** [comment]
most probably you removed the check because to trigger the stats in the control panel and create that link behind the button, the page must be loaded in the browser...can it be?

**Comment by kalinme** [comment]
@mdsandu @smalluban how about something like this: https://www.figma.com/file/Ez4ZUl7q5yXVtAh17TZaOF/WhoTracks.Me?type=design&node-id=293%3A6817&mode=design&t=bp96HQK15bALaPde-1 ?

**Comment by kalinme** [comment]
new updates: https://www.figma.com/file/Ez4ZUl7q5yXVtAh17TZaOF/WhoTracks.Me?type=design&node-id=293%3A6817&mode=design&t=T5pZxlG2kEqyYVXA-1

**Comment by mdsandu** [comment]
let's hold this off until the census report is picked by the media. we can proceed then

**Comment by mdsandu** [comment]
@kalinme the latest link is not working: https://www.figma.com/file/Ez4ZUl7q5yXVtAh17TZaOF/WhoTracks.Me?type=design&node-id=424%3A7215&mode=design&t=fkEX6NalaYYH9iqj-1
 can you please update?

**Comment by mdsandu** [comment]
this became irrelevant AFAIK? 

@kalinme @chrmod

**Comment by kalinme** [comment]
@mdsandu we need final decision about placeholder page. Discussion from yesterday: https://ghostery.slack.com/archives/C03MP7U2GJ0/p1709718902319209

**Comment by smalluban** [comment]
We have already merged PR https://github.com/ghostery/ghostery-extension/pull/1498 which hides the button if the WTM stats are missing, so I think we can remove the placeholder page, and show ordinary 404 if the user enters an invalid URL.

**Comment by AdamGhst** [comment]
1. Since there is no easy way for user to get on page that missess data, and button hides in ui when data is not avaiable, there is no reason to use missing page placeholder. 

2. Right now redirect to wtm main is set instead of 404.

**Comment by smalluban** [comment]
Done
