### ISSUE TITLE
Some trackers from trackerdb are still being shown as unidentified 

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#1332]
The extension should use the information from trackerdb to classify trackers blocked by the adblocker. In some cases, the matching does not seem to work.

Example 1: Clarity
* trackerdb: https://github.com/ghostery/trackerdb/blob/af226f3e23ea889075535aaba2c283d10f0282ed/db/patterns/microsoft_clarity.eno#L18
* test page (listed as unidentified tracker): https://www.rattanebike.com/

**Comment by philipp-classen** [comment]
Looks like it is coming from the adblocker library, which drops `www.`: https://github.com/ghostery/adblocker/blob/9a8c891ea790cf94e7459f64ff5c28bc7987d3a7/packages/adblocker/src/engine/metadata.ts#L173

In the latest trackerdb version, the subdomains - including `www.clarity.ms` - are now dropped and there is only `clarity.ms`: https://github.com/ghostery/trackerdb/commit/bca2e078c45f93c7ca6c2a3e1cc55040745bb31f

So, it should work in this specific example; but it is an open question what makes most sense for the matching in the adblocker library.

**Comment by smalluban** [comment]
@philipp-classen Is this still valid? How can we resolve this issue?

**Comment by philipp-classen** [comment]
It should be still valid, but I do not have more insights compared to the last comment. Currently, I am not aware of a real world example either.

**Comment by smalluban** [comment]
If so, I would close the issue.
