### ISSUE TITLE
YouTube, and Twitch ad-block not working

### ISSUE THREAD

**Issue by SuperCoolFunHappyGuy** [ghostery/ghostery-extension#1344]
From last week, YouTube and Twitch ads are showing now.

Not sure if this has already been noted, and is being worked on, but I thought I'd let you know.

Thanks.

**Comment by philipp-classen** [comment]
For YouTube, there is a ticket where we keep notes here: https://github.com/ghostery/broken-page-reports/issues/267

For Twitch, a recent ticket can be found here: https://github.com/ghostery/broken-page-reports/issues/365

If you have more information that can help us to track the problems down, feel free to leave notes in those tickets.

**Comment by mB-PiBox** [comment]
Same on my end as well. 

No warning from YouTube; Instead "player" window is just black, with ad audio heard playing. At the start of every video, and throughout the videos playback as well.

_> I previously was using AdGuard for Mac (Paid Lifetime Subscription) but their method of blocking ads (while only 98% effective) caused network traffic to slow down. Additionally when AdGuard was Enabled, videos would default to a 480p quality... I've been on the search for a AdBlocker that is available on Mac/Safari for several weeks. Ghostery was the only one that worked; at least for the first 3 or 4 days.. 
> 
> I do not like Chrome, however I often regress to it for YouTube viewing as the only AdBlocker I've found in years that works without failure is uBlock Origin which is sadly unavailable on Safari._

**Comment by GRadziejewski** [comment]
I'm closing this ticket.
