### ISSUE TITLE
BUG: Ghostery doesn't init cliqz properly leading to console statement on every page load

### ISSUE THREAD

**Issue by jhaenchen** [ghostery/ghostery-extension#135]
### Description

I noticed the following warning in my console:

`loading pref showConsoleLogs before prefs were initialised, you will not get the correct result`

This was emitted from the Ghostery extension content-bundle.js file. Upon closer examination that statement is emitted from [here](https://github.com/cliqz-oss/browser-core/blob/master/platforms/webextension/prefs.es#L25) and is emitted because init() is not called before reading the prefs. I suspect then that it could be fixed by calling init on the created App instance [here](https://github.com/ghostery/ghostery-extension/blob/8c4491d6d161504cd93ee98501257317823c25b3/src/classes/Cliqz.js#L18)

### Expected Behavior 

Not to see a console statement on every page load.

### Actual Behavior 

I see a console statement.

### Steps to Reproduce

1. Load any page with dev tools open.
2. Observe the console statement.

### Versions

+ Browser: Chrome 67.0.3396.99
+ OS: Mac 10.13.5
+ Node: N/A
+ NPM: N/A

**Comment by jhaenchen** [comment]
Other users are encountering this issue: https://stackoverflow.com/questions/47988759/loading-pref-showconsolelogs-before-prefs-were-initialised-you-will-not-get-the

**Comment by christophertino** [comment]
@chrmod Any ideas on this?

**Comment by philipp-classen** [comment]
@jhaenchen Thanks for your help. I think, you are right. The main idea to fix it is to always wait for the initialization of the prefs.init(), and if necessary start with a default value until the promise resolves.

Do you still get the error message with the current Ghostery release? If you can show me how to reproduce, I will have a look. I tested on Linux not on Mac, but this should not be OS dependent.

There were also some changes recently on the browser-core side. Maybe it is already fixed there, but I do not think the latest Ghostery release has those changes yet.

**Comment by jhaenchen** [comment]
@philipp-classen I can no longer reproduce the issue! Thanks everyone! I'll close if there are no objections.
