### ISSUE TITLE
Microsoft Workspaces (Preview) dropdown doesn't show shared tabs

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#1352]
When using Microsoft Edge 118.0.2088.61 with an account enabled for Microsoft Edge Workspaces, the Ghostery browser extension prevents the Workspaces menu from displaying properly.

Without Ghostery, clicking the Workspaces icon in the titlebar shows a dropdown menu with all available Workspaces.

However, with Ghostery enabled, the Workspaces menu displays incorrectly.

The issue seems to be that Ghostery is blocking part of the Workspaces submenu. A simple exclusion for the Workspaces menu address may resolve this. 

![](https://ghostery.zendesk.com/attachments/token/o4tR0VyRkFzP6Oqs57tTjlY0i/?name=image2.jpeg)

![](https://ghostery.zendesk.com/attachments/token/Fds3TMnTYDvYN4y14rokEYfOB/?name=image3.jpeg)

***

Workspaces requires being logged in to Microsoft Edge and clicking [this link](https://www.microsoft.com/en-us/edge/launch/workspaces?code=YXBwSWRHdWlkPWI2ZDgzM2NmLWI1NGUtNGNhYi04MTQzLTEzMThlMGJjNTBlMSZyZWRlZW1Db2RlPUFzT29qQksxOGQyeWtzTCUyQndCbUFJMDU5aG9BJTJGblIwU2lIZEFwVGhtMEZabUJ2Y0NTRE5iMHB1aG1WOUxtS0VtODZYckwzJTJGWTdkVkJGQkg1dDdmblRadyUzRCUzRA%3D%3D) the launch the Preview.

**Comment by yokoffing** [comment]
I was not able to replicate this issue. However, this may trigger when actively sharing tabs with users/groups?

**Comment by smalluban** [comment]
Edge platform migrated to v10. Feel free to re-open if the issue is still valid.
