### ISSUE TITLE
Refresing Google.com

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1368]
**Description:**
Search results on google.com endless reloaded pages

**Preconditions:**
You need to be logged into your account.

**Steps to Reproduce:**
1. Open https://google.com 
2. Enter any query and wait for the results
(issue is visible after the 10 sec)

https://github.com/ghostery/ghostery-extension/assets/40433708/bcfa00e3-102c-4709-a874-a4ffba33033a

**Expected Results:**
Search results on google.com cannot reloaded pages

**Versions:**

	Browser: Chrome 119.0.6045.106
	OS: Windows 10 Pro 
	GBE 8.12.3

**Comment by philipp-classen** [comment]
Should be fixed with the latest update of the block lists. (It may take up to 24 hours until clients update.)

**Comment by GRadziejewski** [comment]
I cannot replicate the issue at this moment. Will try to do it in some time once again.

**Comment by yokoffing** [comment]
Related? https://github.com/ghostery/ghostery-extension/issues/1206
