### ISSUE TITLE
Blocking first party API requests with `metrics` in the path

### ISSUE THREAD

**Issue by ssandler-panobi** [ghostery/ghostery-extension#1381]
Hi, I work for Panobi, and we've received reports from users that the Metrics portion of our product does not load when Ghostery is enabled. I've reproduced this and can see that Ghostery blocks all requests matching `/api/v1/metrics/*`. These are first party API requests, made to the same domain as the web page itself (`https://app.panobi.com`), which aren't doing any sort of tracking and are core functionality of our product.

It looks like this is the same issue as https://github.com/ghostery/ghostery-extension/issues/1037 which was closed. Is there any possibility of making these rules not apply to first-party API requests?

**Comment by chrmod** [comment]
Hi Scott, thank you for reporting. This looks like you API is blocked by a very generic easylist filter https://github.com/easylist/easylist/blob/a1a600d0a3043f8f7080135f222e7dc70f8b2b0a/easyprivacy/easyprivacy_general.txt#L310
I'm with you that it should only be blocked when being a third party. 

Going to issue a filter list update for Ghostery users - it's going to be live in around 12h. 

Can you please be so kind and report this problem to the EasyList community? Referencing this github issue may help.

**Comment by philipp-classen** [comment]
(Auto-cosed, since a potential fix was merged.)
