### ISSUE TITLE
Implement an option to add regional filter blocklist

### ISSUE THREAD

**Issue by dimeeentor** [ghostery/ghostery-extension#1388]
I would like to use Ghostery Extension on Safari with a regional blocklist, because standard EasyList sometimes does not understand where is the ad. I know that AdGuard for Safari does it, so it would great to have this feature in your app.

**Comment by smalluban** [comment]
The regional lists were introduced in https://github.com/ghostery/ghostery-extension/releases/tag/v10.4.0

Feel free to re-open, if you have problem with the feature.
