### ISSUE TITLE
Third-party requests are blocked by Ghostery extension when they are fetched by a service worker.

### ISSUE THREAD

**Issue by YoumnaElghandoor** [ghostery/ghostery-extension#1393]
## Description

Third-party requests are blocked by Ghostery extension when they are fetched by a service worker.

## Steps to Reproduce

1. Connect to [`https://fabulous-voice-74.app.baqend.com/Ghostery/`](https://fabulous-voice-74.app.baqend.com/Ghostery/)
2. Reload the page to make sure the service worker is active.
3. Activate Ghostery.
4. Select `Trust Site` from Ghostery’s UI
5. Open dev tools and navigate to the network tab.
6. Reload the page to see the failed requests (https://bat.bing.com/bat.js) in the network tab.

## Expected result:

The request should not be blocked.

## Reproduces how often:

Always

## Other Additional Information:

- Does the issue resolve itself when disabling Ghostery? Yes
- Is the issue reproducible on the latest version of Chrome? Yes

Everything works already if the Ad-blocking option is turned off

**Comment by chrmod** [comment]
Thank you for the report and an amazing setup in which you reproduced the problem. This is very helpful!

**Comment by chrmod** [comment]
@smalluban can you please test how this behave in Ghostery 10? we should fix it first there.
