### ISSUE TITLE
Pop-up asking for permissions to 1,300 websites

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1399]
**Description:**
After installing Ghostery Browser Extension for Safari, a pop-up appears asking for permission for 1,300 web pages.

**Steps to Reproduce:**
1. Install Ghostery Browser Extension
2. Open Safari
3. Open any website, for example https://www.amazon.de/

![IMG_6457a](https://github.com/ghostery/ghostery-extension/assets/40433708/33c6c7c3-c69f-4361-91c3-93879d1df489)

**Expected Results:**

**Versions:**

	Browser: Safari  
	OS: iOS 16.7.2 (iPhone XR)
	GBE 10.2.6
	
	Browser: Safari  
	OS: iOS 17.1.1 (iPhone 13)
	GBE 10.2.6

**Comment by smalluban** [comment]
Fixed with #1517
