### ISSUE TITLE
Ghostery blocking whitlisted trackers.

### ISSUE THREAD

**Issue by The009** [ghostery/ghostery-extension#140]
### Description
Firefox 63.0a1 (2018-07-19) (64-bit) Ghostery blocks everything even things on your whitelist

### Expected Behavior 
Ghostery to only block trackers that you have selected

### Actual Behavior 
Ghostery is blocking all trackers even whitelisted

### Steps to Reproduce

1. Install Firefox Nightly and Ghostery (Even the latest release on github)
2. Unblock Disqus
3. Go to any site that uses Disqus comments and log in, it works till the page reloads then blocked again.
4. Pause Ghostery everything works.

### Versions

+ Browser: Firefox Nightly 63.0a1 (2018-07-19) (64-bit)
+ OS:  Windows 10
+ Node:
+ NPM:

**Comment by Aziz-Ghostery** [comment]
It works as expected, and I can't reproduce this issue on Firefox Nightly 63.0a1 (2018-07-20) (64-bit)
(see attached screenshot) not the latest release FF Quantum 61.0.1 (64-bit).
![ff nightly diqus](https://user-images.githubusercontent.com/28308149/43019273-5fe40c96-8c2a-11e8-8109-c3e7410be4dd.PNG)

**Comment by The009** [comment]
Pausing works just fine. Every time I seem whitelist a single tracker it remains blocked.

**Comment by The009** [comment]
I tried toggling tracking protection to only in private and also to never and neither worked.

**Comment by christophertino** [comment]
@The009 I believe he was referring to the Anti-Tracking feature in Ghostery, not FF tracking protection.  This is the blue shield icon at the bottom left of Ghostery. If you disable that, it should work. 

You could also try the site-specific allow feature, if you hover over the tracker block icon and select  "Trust on this Site".  That should allow the tracker to bypass our Anti Tracking module.  

What's happening is that you have Disqus "allowed", but it still gets screen for personally identifiable information in Anti-Tracking.  More on that situation in #148

**Comment by The009** [comment]
@christophertino Thank you! I was mistaken and did do the wrong thing and this is the same issue.

@Aziz-Ghostery  Thank you for your help as well. Yes this is the issue you mentioned.
