### ISSUE TITLE
Cannot find strings location for translation mapping

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1401]
I've tried to find those strings on UI and other pages / places but without success.

- "Enable now" `(Somewhere in onboarding for opera -serp?)`
- "For more information read our full" `(Somewhere in Privacy Policy)`
- "More ad blocking available"  `(Somewhere in onboarding for opera -serp?)`
- "Other" `(category name)`
- "privacy policy" `(???)`
- "More information on $${0} methodology in Ghostery's Manifesto." `(tag: 'ui-onboarding-whotracksme-dialog' - whotracksme.js)`
- "Ok, I understand" `(whotracksme.js)`
- "What is WhoTracks.Me?" `(whotracksme.js)`

**Comment by smalluban** [comment]
#### "Enable now" - Notification for Opera browser:
#### "More ad blocking available" (Somewhere in onboarding for opera -serp?):

<img width="455" alt="Zrzut ekranu 2023-12-5 o 12 17 13" src="https://github.com/ghostery/ghostery-extension/assets/1906677/dca6cd25-fae1-4beb-a2d6-0033502e4e71">

#### "For more information read our full" (Somewhere in Privacy Policy)
#### "privacy policy" (???)

![Zrzut ekranu 2023-12-05 o 12 18 36 PM](https://github.com/ghostery/ghostery-extension/assets/1906677/1872c36d-d3de-42b3-ae28-8ea1e58f52df)

#### "Other" (category name)

<img width="382" alt="Zrzut ekranu 2023-12-5 o 12 19 54" src="https://github.com/ghostery/ghostery-extension/assets/1906677/cb5bc838-6354-4a00-a8e1-e142afedc28c">

#### "More information on $${0} methodology in Ghostery's Manifesto." (tag: 'ui-onboarding-whotracksme-dialog' - whotracksme.js)
#### "Ok, I understand" (whotracksme.js)
#### "What is WhoTracks.Me?" (whotracksme.js)

Leftover of not used view in the onboarding process - I'll make a PR with the cleanup.

**Comment by GRadziejewski** [comment]
Checked and updated.
