### ISSUE TITLE
Standby blocked by a phantom audio process

### ISSUE THREAD

**Issue by felix9743** [ghostery/ghostery-extension#1404]
## **Description:**
I noticed that my PC was strangely no longer active when my browser, Brave, was open. So I did some research and I deduced using the `configcfg requests` command that **ghostery** was the cause.

Indeed, It strangely created an **audio process** that is useless when I have, often an open Youtube tab but, this can happen with another site even if it is more rare. If I close this tab, the process disappears almost instantly.

I only noticed this strange phenomenon on **Brave** (I also have **Firefox**) and it's really very annoying. How do you know **what causes the problem and, most importantly, how to fix it?**

## **Versions:**
**Ghostery for browser,** version **8.12.4**
**Brave** version **1.60.125** Chromium: **119.0.6045.199** (Official Build) (64-bit)

## **Evidence:**
[Ghostery-configuration.zip](https://github.com/ghostery/ghostery-extension/files/13514779/Ghostery-configuration.zip)

![image](https://github.com/ghostery/ghostery-extension/assets/29979907/6c8e229d-d3f4-4e95-833e-bb7a6f29cb38)

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
