### ISSUE TITLE
YouTube doesn't remember watch history when not signed in

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#1405]
### Description
YouTube does not remember search history or homepage suggestions unless "Trust Site" is activated. The condition applies if the user is **_not_** logged into YouTube.

**When *not* logged into YouTube:** Ghostery makes YouTube forget all user settings and history with each browser restart. No ads show.

**When *not* logged into YouTube, but "Trust Site" is activated:** YouTube remembers the user's customizations, settings, watch history, and homepage suggestions. Ads show.

If the user disables the "Trust Website" setting, their preferences are forgotten with each browser restart.

This can be seen as a good thing from a tracking perspective; but from a casual user perspective, this is likely seen as unintended behavior.

### Steps to Reproduce

1. Open Firefox browser
2. Go to `youtube.com`
3. Watch a video; Disable autoplay videos in YouTube settings.
4. Restart Firefox browser
5. Notice autoplay does not remain disabled on YouTube homepage
6. Homepage suggestions are not influenced previous YouTube search history

### Versions
* Firefox
* Ghostery v.8.11.1
* OS: Windows 10

**Comment by SDunston** [comment]
Hello, are you still having this issue? Im still trying to reproduce with search history but no luck

**Comment by Wku059** [comment]
Hi,

I initiated this via Ghostery support. The problem persists. It applies to some other websites as well, as if Ghostery was blocking certain data or cookies from saving, hence "cleaning up" each time after the browser is restarted,

**Comment by smalluban** [comment]
The last platform migrated to v10.
