### ISSUE TITLE
Constant “Additional Permissions Requested” alert for malformed website URL

### ISSUE THREAD

**Issue by LeoNatan** [ghostery/ghostery-extension#1428]
Hello,

I’m not sure where to put this issue. It happens on Safari on iOS. From time to time, Safari pops up an “Additional Permissions Requested” bar on top of pages. Clicking on it, it’s always for the same malformed URL. I’m not sure under what conditions Safari pops it up, but as you can imagine, it’s very annoying. One way to consistently reproduce this is by opening the Ghostery extension settings, at which point, the bar shows up consistently. 

See attached video:

https://github.com/ghostery/ghostery-extension/assets/2270433/9c02bda9-1fde-421f-82a4-140370025183

I suspect it’s related to the slash at the end, it somehow confuses Safari. 

Thanks

**Comment by GRadziejewski** [comment]
@LeoNatan , thank you for bringing a new problem to our attention. However, I am currently having difficulty reproducing this problem on my site. Could you give more details on the steps to reproduce this problem? Is there anything specific I need to do beforehand?

**Comment by LeoNatan** [comment]
@GRadziejewski Unfortunately, I cannot. I have done no special steps to produce this issue. I just installed the extension and after a while, this happened. Perhaps it's an issue with the filter list for Israeli sites? Notice the rogue "\" in the URL it's presenting.

**Comment by GRadziejewski** [comment]
Please excuse the lack of response on my part. 
I have tried to reproduce this on iOS 17.4, together with our extension version 10.2.13. Unfortunately, further unsuccessfully. When I go directly to the page shown in the attachment (rep.erate.co.il), no page is loaded and Safari shows me "Not secure". I would like to ask whether you are still experiencing this problem. @LeoNatan?

**Comment by LeoNatan** [comment]
Hello,
Yes, it still reproduces.

![IMG_6244](https://github.com/ghostery/ghostery-extension/assets/2270433/5c50b7f1-ac52-4c80-8f3b-c5681b830c1d)

Could you please try opening an Israeli website such as https://www.ynet.co.il/ and try opening Ghostery there?

**Comment by chrmod** [comment]
Hi @LeoNatan - this issue is very hard to reproduce, I cannot get it on my setup but it reminds me another one that was triggering for unsplash.com.

Can you please try this https://github.com/ghostery/ghostery-extension/issues/1293#issuecomment-1740476358

**Comment by LeoNatan** [comment]
I’ve been clearing Safari history and data recently as workaround for issues in a different extension, and the issue has persisted.

**Comment by smalluban** [comment]
Fixed with #1517 . Feel free to reopen if still exists in v10.2.15+.

**Comment by LeoNatan** [comment]
Thank you, will test!

**Comment by LeoNatan** [comment]
Seems resolved. Good job!
