### ISSUE TITLE
Export/Import of Ghostery Browser Extension settings does not work on Android 

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1433]
**Description:**
Export/Import does not work. 
When I export the extension settings, a success message appears. But I cannot find any *.ghost file in the download folder. When I try to import (ghost file exported on PC), nothing happens.

**Preconditions:**
Create a *.ghost file on your computer and copy it to your Android device into the Download folder.

**Steps to Reproduce:**
1. Open Firefox
2. Open any website, for example https://www.ghostery.com/
3. Open Ghostery panel
4. Open Settings / Import & Export Settings
5. Click on Export Settings - success 
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/7b23dace-0ec0-4d59-976a-4be78e9564e8)

6. Click on Import Settings
7. Select the exported file from the computer - nothing happens
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/dd05c683-c21a-4a57-abb8-1827d91ce078)

**Expected Results:**
Export/Import of the settings must work the same way as on PC.

**Versions:**

	Browser: Firefox 121.0.1
	OS: Android 14
	GBE 8.12.5

	Browser: Firefox 121.0.1
	OS: Android 11
	GBE 8.12.5

**Comment by GitTheHellOutaHere** [comment]
Import failed for me yesterday. 

I exported extensions data from Firefox on my Mac and transferred the files to my new phone. 

But when I click Import and select the .ghost file, nothing happens - just returns to the import page as if I hadn't done anything - no confirmation of successful import. None of the settings change and the Global Blocklist doesn't have all the boxes checked to block everything. Fortunately, it only takes a minute to re-configure Ghostery manually. I have alerted [Ghostery Support.](https://www.ghostery.com/support)

At the same time I exported/imported data from two other extensions and they both imported properly.

Android 12
Firefox 119.0b5
Ghostery 8.12.5

**Comment by GitTheHellOutaHere** [comment]
Ghostery Support has confirmed the import failure. They should have posted that finding here.

```
We were able to replicate this and the issue can be followed here: https://github.com/ghostery/ghostery-extension/issues/1433

We are looking into it.
```

**Comment by smalluban** [comment]
We have discovered, that this is an issue in the Firefox implementation. We have disabled the feature for Android to not confuse users. 

I opened a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1877407

I'll let you know if there will be a bugfix and we will be able to enable this feature again.
