### ISSUE TITLE
How to disable Human Web

### ISSUE THREAD

**Issue by Raph22** [ghostery/ghostery-extension#1450]
Hello :)
How can I disable human web ?
<img width="487" alt="image" src="https://github.com/ghostery/ghostery-extension/assets/18127594/8b0384cf-72fb-4311-a573-dc49e090da7d">

Is that normal we can't change `enable_human_web` in https://github.com/ghostery/ghostery-extension/blob/main/extension-manifest-v2/app/panel/components/Settings/OptIn.jsx ?

**Comment by smalluban** [comment]
Yes, the human web is enabled when a user enables the extension.
