### ISSUE TITLE
Never Consent - streamline UX

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1454]
on this website/on all websites, it reverts to default at update-should we port the user setting and not ask again?

**Comment by kalinme** [comment]
simplified flow for never-consent proposition: https://www.figma.com/file/St3Uc4ey0MdcYuKIDR11ws/Ghostery-Web?type=design&node-id=123%3A16624&mode=design&t=V7EE7w9kbQ31tsSr-1
