### ISSUE TITLE
Feature request not an issue: add simple USER RULES option

### ISSUE THREAD

**Issue by Kees1958** [ghostery/ghostery-extension#1475]
Some smaller language area's may have some annoying adds networks, which can be simply blocked with
||addnetwork.nl^$third-party,script (or subdocument or xmlhhtprequest ) 

Please add a USER RULES section where the user can add some basic/simple ABP format block rules.

I don't mind limitations of say a maximum of 50 or 100 user rules and a limitation to the ABP-commands facilitated to svery simple ABP block rules

**Comment by chrmod** [comment]
Thank you for your feature request. We are working on it https://github.com/ghostery/ghostery-extension/pull/1354 
Hope to have this ready by the end of Q1. Stay tuned!
