### ISSUE TITLE
Ghostery ought to have a "Trust on all sites" button for each tracker.

### ISSUE THREAD

**Issue by hrasmussendk** [ghostery/ghostery-extension#148]
**Description**
Ghostery ought to have a "Trust on all sites" button for each tracker to prevent blocking the tracker on any site.

**Expected Behavior**
When pressed on one site the tracker should not be restricted ot blocked on any other site. Say I want to trust the Facebook social Like button, I would like to do so on all sites no matter where, to make me able to like a site I come across.

**Actual Behavior**
In the list of trackers (detailed view) there is three buttons for each tracker to either "Trust on this site", "Restrict on this site" and "Block on all sites", but no "Trust on all sites". 

**Steps to Reproduce**

1. In the browser, click the Ghostery toolbar button.
2. Clock the Detailed view tap
3. If collapsed, click Expand all
4. Move the mouse to a tracker in the right pane
5. When mouse moved, three trackers show up, "Trust on this site", "Restrict on this site" and "Block on all sites", but no "Trust on all sites": [O][Ø][X] 

### Versions

+ Browser: Chrome, Firefox 
+ OS: MacOS (I think Windows as well)
+ Node:
+ NPM:

**Comment by Aziz-Ghostery** [comment]
Hello: 
There is a way to trust or restrict a single tracker across all websites, here is how:
Click on Ghostery Icon
Click on Menu then Settings
From Global settings, let say you had everything blocked but you'd like to Trust/unblock "DoubleClick"
Use the search box on the right and type: DoubleClick" then press enter
The tracker will be displayed un-check box to unblock it/trust it 
All settings on this panel are across all Sites whereas settings actions on the detailed view Panel affect the current site only.

I hope this is helpful.

**Comment by christophertino** [comment]
@hrasmussendk This is something we've been aware of for some time.  Our current "allow" option is really a pass-through where the request can still get picked up by anti-tracking or ad-blocking.  We need essentially 3 states:  block, no-state, allow.  It's kind of confusing from a UI perspective, but our UX team has been kicking around some ideas. 

Our 8.4 release roadmap has a reworked tracker list that combines details from anti-tracking and ad-blocking into the main Ghostery list.  If all goes well, we should be able to add the "global allow" state to this design.

**Comment by klodoma** [comment]
+1

**Comment by AJerm** [comment]
Has this been added yet? I use a lot of sites with chat widgets like Intercom regularly and it's pain having to whitelist every one.

**Comment by christophertino** [comment]
Thanks for the reminder.  We're working on a related feature to allow you to whitelist specific urls in Anti-Tracking, which should help this issue. That should be ready in v8.4.1 next month.  

We're also working on a tighter integration of Anti-Tracking and the Ghostery tracker DB, so that the "allow" state in Ghostery is respected by both modules. This way we might not need to add that fourth "allow always" button. But we are still investigating.

**Comment by krishan** [comment]
Ghostery blocks "Honeybadger" by default, which is not really a tracker IMHO, but an error reporting tool (which I rely on heavily for web development). I'm aware that others may feel that "Honeybadger" is tracking them, so I have no problem with the default.

But having some way to globally allow a tools like "Honeybadger" on _all_ sites would be nice for those cases, where the line between "legitimate tool" and "tracker" is not so clear.

**Comment by MahatmaFatalError** [comment]
any news here? _"Trust on all sites"_ would be really great!

**Comment by christophertino** [comment]
Nothing yet, unfortunately. We're now looking to migrate our blocking over to `declarativeNetRequest`, as per the Chrome manifest v3 proposal. I'm hopeful that we'll be able to resolve this "trust on all sites" issue using [dynamic rules](https://developer.chrome.com/extensions/declarativeNetRequest).

**Comment by denzfox** [comment]
> Has this been added yet? I use a lot of sites with chat widgets like Intercom regularly and it's pain having to whitelist every one.

the Intercom chat app is still being blocked

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
