### ISSUE TITLE
Auto-update ghostery

### ISSUE THREAD

**Issue by wiseguy711** [ghostery/ghostery-extension#1481]
For the last few months Ghostery will not auto update in Firefox.  I have to update it manually. The automatic update is not working .. Anyone know why. I asked their customer support, and they wrote to about:config and make sure some sets are true and they are. Any ideas..

**Comment by 4yman-el** [comment]
Can you give more details (versions, sources...)?

**Comment by smalluban** [comment]
From our perspective, there is not much we can do. If the problem still exists, it must be the browser bug. The update process of the extension is done by the browser, not by the extension itself. 

We can recommend re-installing the extension or as a last resort re-install the browser. However, at first, please check if you use the latest version of Firefox.
