### ISSUE TITLE
Missing detailed settings in v10 (feature regression)

### ISSUE THREAD

**Issue by eliotcougar** [ghostery/ghostery-extension#1483]
1. It is no longer possible to fine-tune which trackers should or shouldn't be blocked on a specific site.
2. It is no longer possible to allow specific trackers (i.e. Google's, Yandex's) for all sites.

Old extension's detailed view with a search box was very convenient to power-users. The new extension has only bare-bones settings - either allow all or block all on a specific website. When a website breaks due to Ghostery it is usually possible to identify one specific tracker that has to be enabled on that one site without allowing all the other trackers.

That's a significant feature regression.

**Comment by smalluban** [comment]
Closing, as the feature is already released to all supported platforms.
