### ISSUE TITLE
random pop-up for the same question

### ISSUE THREAD

**Issue by stefansegers** [ghostery/ghostery-extension#1495]
Hi guys,

My safari plugin randomly pops-up with the question if Ghostery should be used for dumpert.nl
I uninstalled the plugin and installed back again, but error keeps coming and is really annoying.

It also does not matter what button you use, it keeps coming back.

In the screenshot you see the pop-up on Ghostery.com and asks about dumpert.nl

![Scherm­afbeelding 2024-03-05 om 16 55 53](https://github.com/ghostery/ghostery-extension/assets/55828944/ee3380a7-f969-495c-9492-6c45cc8d419d)

Is there something I have setup incorrectly?

**Comment by chrmod** [comment]
Hi @stefansegers - thank you for reporting this issue. This looks like a problem we see on Safari for quite some time. 
Here is a link to a partial solution https://github.com/ghostery/ghostery-extension/issues/1293#issuecomment-1740476358
Sadly, from all we know this is a Safari bug and we await a fix from Apple. 
Closing this issue as a duplicate, but if you have any more information, please comment on the other one.

**Comment by stefansegers** [comment]
Thanks for explaining.. I will give it a try 👍🏽

Stefan Segers

*Fotograaf*
Stefan Segers Fotografie | trouwshoot | familieshoot
Zoetermeer

📱   06-53338796
📧 ***@***.***
