### ISSUE TITLE
Extension may be corrupted

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1504]
**Description:**
On the extension tab, Ghostery Tracker & Ad Blocker - Privacy AdBlock, there is information "This extension may have been corrupted" after the installation

**Steps to Reproduce:**
1. Open Opera browser
2. Install Ghostery browser extension
3. Open opera://extensions
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/f48cce71-081d-42dd-8498-081361425599)

**Expected Results:**
After installation, the extension should function normally

**Versions:**

	GBE 10.2.13

**Comment by chrmod** [comment]
what's the installation source? opera extension store?

**Comment by GRadziejewski** [comment]
I tried to reproduce it but without success. Closing.

**Comment by Narzhan** [comment]
I'm still experiencing this issue on Opera 111.0.5168.61 on Win 11 with Ghostery version 10.3.11.
