### ISSUE TITLE
Ghostery doesn't work, if webcontent of an iframe shows cookie modal

### ISSUE THREAD

**Issue by ca-dsgn** [ghostery/ghostery-extension#1513]
Hi guys,

I just figured out that if a website contains an iframe, which shows a cookie modal (e.g. shown on google.com), the plugin doesn't block it. Is there an option to enable also blocking modals in iframes? If not, is it possible to enhance the plugin to do so? Thank you in advance for your response on this.

Best,
Chris

**Comment by chrmod** [comment]
Hi @ca-dsgn, thank you for your report. As far as I can tell this should work. Can you please provide examples? URLs and screenshots should help us to understand the problem.

**Comment by ca-dsgn** [comment]
Hi @chrmod,
sure, here is a screenshot:
<img width="1504" alt="Bildschirmfoto 2024-03-27 um 08 03 59" src="https://github.com/ghostery/ghostery-extension/assets/604636/9105a570-f702-4f65-95d3-c9e9aecf2dcb">
And the source code:
`<iframe src="https://www.google.com/search?igu=1&q=Wismar Weltkrieg 1945" id="google"></iframe>`

**Comment by ca-dsgn** [comment]
Here is also what the plugin shows:
<img width="583" alt="Bildschirmfoto 2024-03-27 um 08 05 46" src="https://github.com/ghostery/ghostery-extension/assets/604636/1cc477ae-0541-4a3a-a9f6-1b9ee4762bf4">

**Comment by chrmod** [comment]
Thank you for sharing!

Something definitely does not look right. I've tested myself and the cookie consent dialog is dismissed correctly thanks to Never-Consent. I'm passing this to @GRadziejewski so he can try to reproduce. 

In the meantime, could you please try to test it on a different browser, or with fresh Ghostery installation please?

**Comment by GRadziejewski** [comment]
After clearing the history and browser data + reinstalling the extension, I cannot reproduce this.

Checked on:

```
Browser: Chrome 123.0.6312.86
OS: Windows 10 Pro 
GBE 8.12.7

Browser: Firefox 124.0.1
OS: Windows 10 Pro 
GBE 8.12.7

Browser: Opera One 108.0.5067.40
OS: Windows 10 Pro
GBE 10.2.14

Browser: Safari 17.4 (19618.1.15.11.12)
OS: macOS Ventura 14.4
GBE 10.2.14
```

**Comment by ca-dsgn** [comment]
@chrmod @GRadziejewski I removed the plugin from my Chrome Browser (on macOS Ventura) and readded it. After that I restarted Chrome and opened up the page with the iframe (Google URL inside the src attribute). I still get the cookie modal.

I also tested it on Firefox (latest version for macOS) with Ghostery. I have the same issue here.

**Comment by chrmod** [comment]
Oh, I see. This is an iframe with google.com inside. In this case I don't think Never-Consent can work. Let us investigate, maybe there is something we can do.

**Comment by chrmod** [comment]
@ca-dsgn can you please tell us more about your setup. It must be quite special, as you see google trackers reported on your local domain name `dev.higris`. 

From what we are able to determine, our features should work when loaded in the iframe and I cannot reproduce google cookie consent modal when loading google iframe in another page. So it must be something else going on here.

**Comment by chrmod** [comment]
Update - one of our developers was able to reproduce the problem on our side - we will look into it. Stay tuned!

**Comment by ca-dsgn** [comment]
@chrmod any updates on this?

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
