### ISSUE TITLE
Ghostery extension blocks network calls to OneTrust cookie banner

### ISSUE THREAD

**Issue by amandak25** [ghostery/ghostery-extension#1527]
Hello,

There are 2 users who installed Ghostery extension on their browser who cannot see OneTrust cookie banner. I discussed it internally and it seems that the error was already identified in 2022, and it was supposed to be whitelisted (ticket opened in 2022 : https://github.com/ghostery/ghostery-extension/issues/804) 

Could you please check if there is something to do on your side or on ours ? Tested on Google Chrome and Microsoft Edge (latest version).

Thank you for your help

**Comment by peteknowlton** [comment]
Thank you for the report. Can you please provide a url of affected page?

**Comment by chrmod** [comment]
@amandak25 thank you for your report. Can you please share a link to affected page?

**Comment by amandak25** [comment]
@chrmod thank you for your reply !
It is happening for all our websites, but please find below 3 of them so you can test :
https://staffshop.loreal.fr/
https://www.cerave.fr/
https://www.beaute.fr/

**Comment by amandak25** [comment]
Thank you @chrmod 

Howerver, I just learnt that it was not Ghostery 10. Please find below the information : 

Chrome Version 123.0.6312.123 
Edge Version 123.0.2420.81

Ghostery Version 8.12.8

**Comment by chrmod** [comment]
@amandak25 Ghostery 8 offers user choice to block OneTrust, maybe this is what is happening. By default, this should not be the case. Can you please provide a screenshot from the panel. 

@GRadziejewski can you try to reproduce?

**Comment by amandak25** [comment]
@chrmod Which panel are we talking about ?

**Comment by chrmod** [comment]
Sorry for not being clear. 
I've meant Ghostery panel like in the screenshot here https://github.com/ghostery/ghostery-extension/issues/1527#issuecomment-2051505719

**Comment by amandak25** [comment]
Please find the panel attached
<img width="783" alt="image (2)" src="https://github.com/ghostery/ghostery-extension/assets/166490090/fd379707-b86c-4565-b6a0-98e2ddbe6bc7">

**Comment by GRadziejewski** [comment]
Checked on the fresh installation:

```
Browser: Firefox 124.0.2
OS: Windows 10 Pro 
GBE 8.12.8

Browser: Chrome 123.0.6312.106
OS: Windows 10 Pro 
GBE 8.12.8
```
https://staffshop.loreal.fr/
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/af85182f-8fdf-40ed-9a9d-1c6d1b8b6bc0)

https://www.cerave.fr/
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/a8ff6d48-8918-46db-8e3f-0e1650cbb59d)

https://www.beaute.fr/
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/46f2f0c4-8acc-4710-a7c2-f71102a94c04)

Also I've checked Global Blocking and it looks like this:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/1cf06486-8fdb-4bb8-80fc-15e17ead3448)

**Comment by chrmod** [comment]
@amandak25 from your screenshots and ones from @GRadziejewski we can see that OneTrust is not blocked by the Ghostery extension.

Do verify we could check browser developer tools - in the network tab you should be able to confirm if network requests are blocked or not. 
<img width="1642" alt="Screenshot 2024-04-15 at 14 48 29" src="https://github.com/ghostery/ghostery-extension/assets/1228153/aa61b4b5-aff3-47a6-b8a5-14079b9b40bc">

What may be happening is the action of Ghostery feature [Never-Consent](https://www.ghostery.com/blog/never-consent-by-ghostery) - TLDR, Ghostery does not block CMPs but interact  with them (in the same way as a user would) in a way to opt-out from all tracking.

Do you think it may be the case? To verify you can check the state of OneTrust cookies.

**Comment by amandak25** [comment]
@chrmod Thank you for the feedback.

We checked and it seems that all cookies are dropped (others than Strictly Necessary)
<img width="947" alt="image (3)" src="https://github.com/ghostery/ghostery-extension/assets/166490090/cd2ab415-33f2-4d02-ae66-46a425549328">

**Comment by chrmod** [comment]
In this case, it looks like everything works correctly. Thank you for reporting and please keep us posted if you notice anything incorrect.

**Comment by amandak25** [comment]
Hello @chrmod , does it mean that you can see the cookie banner poping when you go on any of the websites listed ?

**Comment by chrmod** [comment]
The cookie banner may show up for a short moment of time, but then Never-Consent interacts with it as if user would decline consent for tracking.
