### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1539]
- [ ] 01 - [The invalid filter error is visible at all times.](https://github.com/ghostery/ghostery-extension/issues/1539#issuecomment-2059176064)

**Comment by GRadziejewski** [comment]
Issue no 01.

**Description**
When an incorrect filter is added, an error will appear. When an invalid filter is removed or fixed, the error will not disappear until the entire page is reloaded



**Steps to Reproduce**
1. Open chrome-extension://.../pages/settings/index.html
2. Click a few times on the version number
3. Add `|| reuters.com` as a custom filter
4. Click the Update button
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/4fe0bd94-1801-410b-8b28-8a226b1b47f3)

5. Delete `|| reuters.com` 
6. Click the Update button
7. Error is still visible
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/5cd5b179-4651-4f9e-9d65-7ed25d8f0c02)


**Expected results**
Once the incorrect filter has been removed or fixed, the error should disappear.

**Comment by smalluban** [comment]
@GRadziejewski Is this still valid?

**Comment by GRadziejewski** [comment]
Yes, it is still valid. In version 10.3.7 it looks like this:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/246375ab-e2a4-49cf-9fb3-bcfd173e3001)

**Comment by smalluban** [comment]
@GRadziejewski Please re-test the issue, I think with the latest refactor the bug should be fixed.

**Comment by smalluban** [comment]
Fixed on `main`
