### ISSUE TITLE
Typo in a translation on Ghosty icon

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1540]
**Description**
There is a typo in a translation when the mouse is focused on Ghosty icon

**Steps to Reproduce**

1. Open browser
2. Focus mouse on the Ghosty icon
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/fc5646ae-88b4-4ca1-9015-d0ac501ed84a)

3. There is "Przeglądaj wyniki **_wyszukiwana_** przez Ghostery"

**Expected results:**
There should be "Przeglądaj wyniki **_wyszukiwania_** przez Ghostery"

**Comment by smalluban** [comment]
Fixed with 69cc02f9ec34917415a56f7e38fd0536b5669245
