### ISSUE TITLE
Ghostery Extension No Longer Working

### ISSUE THREAD

**Issue by pengc99** [ghostery/ghostery-extension#1550]
Sometime within the past week the Ghostery extension is no longer blocking ads - I first noticed it on several web pages such as SlickDeals where now i'm getting presented with a sidebar full of ads as if I was not running Ghostery . When I open the Ghostery panel, it doesn't show any trackers / advertising as blocked and it all shows as "Unidentified"

![image](https://github.com/ghostery/ghostery-extension/assets/356292/836fbc31-6e30-4971-bda0-846912b05230)

I have tried to update my tracker list several times and still not getting any blocking. Not sure what is going on or what is causing this, perhaps a malformed blocklist?

**Comment by philipp-classen** [comment]
Thanks for reporting! I cannot reproduce myself, but from the screenshot it looks like a bug.

From the looks of the screenshot, I tagged it as Chrome (hope I guessed right?). However, we also got a recent report for Opera, so it is not clear if it is isolated to Chrome.

**Comment by pengc99** [comment]
I just double checked on my computers and I don't see this issue anymore. Ads and trackers are now being correctly picked up in my browser plug-in for Chrome and it is behaving as expected. 

I just checked the version number of my Ghostery plugin and it is 8.12.9 running on Chrome 124.0.6367.61

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
