### ISSUE TITLE
[QA] The tooltip disappears too quickly and a longer description cannot be read

### ISSUE THREAD

**Issue by smalluban** [ghostery/ghostery-extension#1556]
**Description**
The tooltip disappears too quickly and the description cannot be read.

**Steps to Reproduce**

1. Open chrome-extension://.../pages/settings/index.html
2. Open Trackers
3. Hover mouse on the icon "i" for Essential  (or any other category with a long description)
4. Wait for the tooltip

https://github.com/ghostery/ghostery-extension/assets/40433708/f8fb8208-7295-4827-8d25-82088e0c005b

**Expected results:**
The tooltip should be displayed 3–4 seconds longer to allow the user to read a longer description.

**Comment by smalluban** [comment]
I extended hiding to 5 seconds.

**Comment by GRadziejewski** [comment]
Checked. Fixed.


https://github.com/ghostery/ghostery-extension/assets/40433708/765a2961-4340-432d-8643-45498f46c09f
