### ISSUE TITLE
[QA] The sizes of the description columns are not fixed

### ISSUE THREAD

**Issue by smalluban** [ghostery/ghostery-extension#1557]
**Description**
The sizes of the description columns are not fixed, which can lead to a situation where once the category description is 90% and the organisation description 10%, in another situation the total opposite.

**Steps to Reproduce**

1. Open chrome-extension://.../pages/settings/index.html
2. Open Trackers
3. Look for example, Didomi and open for more details

![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/f5b7659c-da98-4222-8164-667d0492be5c)

4. Look for example, ADARA Analytics and open for more details

![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/ecda05e6-5f34-4eb7-91c0-f013f981b196)

**Expected results:**
The sizes of the description columns should be fixed in such a way that the whole is more consistent.

**Comment by smalluban** [comment]
Should be fixed now

**Comment by GRadziejewski** [comment]
Checked. Fixed.


![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/c9366a61-9c48-40f2-ad7b-f6478cb18043)



![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/7285e09b-bc8f-485b-a225-790ed0eb278f)




![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/532e7256-288f-44ed-b24a-cd402532560d)




![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/d2b92507-988b-4333-8957-647a47ab5bb9)




![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/a458dc18-94a5-41f5-9072-4d07cd70f91f)




![Image](https://github.com/ghostery/ghostery-extension/assets/40433708/623425fd-0623-455f-925f-a0ae0eeb7016)
