### ISSUE TITLE
[QA] The Ghostery panel appears a few seconds after clicking on the icon

### ISSUE THREAD

**Issue by smalluban** [ghostery/ghostery-extension#1559]
**Description**
When I press the Ghosty icon, the panel appears after a few seconds 

**Steps to Reproduce**

1. Open any website, for example https://www.youtube.com/
2. Click on the Ghosty icon

https://github.com/ghostery/ghostery-extension/assets/40433708/a6008efe-d5e6-4080-af81-ae242a54adbe

**Expected results:**
The Ghostery panel should be visible in less than a few seconds after clicking the icon

**Comment by smalluban** [comment]
I had a hard time reproducing, but still I tried to not wait for some of the data (there is a simple change in the logic). You can check it out if it is faster for you now.

**Comment by GRadziejewski** [comment]
Much faster. Fixed for me.


https://github.com/ghostery/ghostery-extension/assets/40433708/65fa8fc5-eeb8-4f98-8a72-2cedbe102693
