### ISSUE TITLE
Ghostery blocking reCaptcha on Firefox

### ISSUE THREAD

**Issue by jbarnicle** [ghostery/ghostery-extension#1567]
Ghostery is activly blocking access to www.recaptcha.net causing bot detection to fail.

<img width="1552" alt="Screen Shot 2024-04-29 at 1 55 56 PM" src="https://github.com/ghostery/ghostery-extension/assets/737400/8dfc1795-16e2-42de-953a-9d0d63c341bf">

**Comment by chrmod** [comment]
@jbarnicle thank you for your report - can you please share some details. Which version of Ghostery extension are you using, what's your browser and what it the affected website.

**Comment by smalluban** [comment]
The last platform migrated to v10.
