### ISSUE TITLE
Extension crashes on Firefox: TypeError: c.app is undefined

### ISSUE THREAD

**Issue by raaaahman** [ghostery/ghostery-extension#1573]
## What happened?

While working on my front-end development projects, I noticed an error message in the console:

> TypeError: c.app is undefined

This message is also printed when I visit any web page, and I can't open the Ghostery panel by clicking on the Ghostery icon in my browser's toolbar.

Desactivating the Ghostery extension removes the message.

## Software versions

Ghostery Firefox Extension 8.12.9
Mozilla Firefox 125.0.3 (64bit)
Ubuntu 22.04.4 LTS

**Comment by chrmod** [comment]
Thank you for the report, it is much appreciated. Does this happen on localhost domains only? Can you please share anything specific to your setup that can you think may be triggering the problem?
Can you please try to re-install the Ghostery extension and see if the problem goes away?

**Comment by chrmod** [comment]
@GRadziejewski please try to re-produce

**Comment by GRadziejewski** [comment]
The only error which I can see on Firefox 126.0b9 / Windows 10

`TypeError: can't convert undefined to object 4 panel_react.js:797:227357`

![image](https://github.com/ghostery/ghostery-extension/assets/40433708/ad30ec81-da14-427c-bac6-c767137eb7ac)

**Comment by raaaahman** [comment]
>  Does this happen on localhost domains only?

It did happen with any web page / domain.

With a fresh install I can now open the Ghostery panel, and the original error message disappears.

Hoxever, I have now another error message:

> Content-Security-Policy : The page’s settings blocked a JavaScript eval (script-src) from being executed because it violates the following directive: “script-src https://github.githubassets.com” (Missing 'unsafe-eval')

**Comment by chrmod** [comment]
Good to hear that the previous problems are gone.

The other ones that you've just reported reminded me about alternative scriptlet injection method. Lets me try to reproduce and get back to you.

Just to be clear, besides the console logs, there are no problems with the websites themselves?

**Comment by chrmod** [comment]
This should solve a part of the problem https://github.com/ghostery/adblocker/pull/3942
It will be a part of a release 8.12.10 - that we hope to ship very soon.

However we still have to update autoconsent library which happens to have the same issue. 

Closing this issue for now. Many thanks!

**Comment by chrmod** [comment]
We've found and fixed the problem with Never-Consent. 

Fix is here https://github.com/ghostery/ghostery-extension/pull/1581

Will be included with the release.
