### ISSUE TITLE
Can't open link on Mail.ru

### ISSUE THREAD

**Issue by valodka** [ghostery/ghostery-extension#159]
###URL(s) where the issue occurs
https://e.mail.ru/messages/inbox/

##Describe the issue
Open https://e.mail.ru/messages/inbox/
Open any letter with external link.
Click on link in letter.
New window can't open.

###Versions
Browser/version: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 IP

Ghostery 8.2.3

**Comment by Aziz-Ghostery** [comment]
@valodka I just created an account on mail.ru
On Windows 10 and both Chrome V68.0.3440.106 (64-bit), and FF V61.0.2 (64-bit)
Installed Ghostery with all trackers blocked and all products enabled (default)
Opened Ghostery Account verification email and Clicked on every link they all opened without any problems.
![mail ru link click issue](https://user-images.githubusercontent.com/28308149/44157632-ec913f00-a080-11e8-9786-c87b4053689c.PNG)
