### ISSUE TITLE
When the add-on is paused, the trackers are still blocked.

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1640]
**Description**
When the Ghostery is paused (site is trusted), trackers are still blocked. They are still blocked even after 5 minutes  (sometimes more).
(on macOS the situation is much better, only a simple reload of the website is sufficient)

**Steps to Reproduce**

1. Open any website, for example https://www.aarp.org/
2. Open Ghostery panel and click on the "Trust this site" button
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/d17c8f40-addf-47e1-ab3d-48a2943c8778)

3. Site is trusted and reloaded - trackers are blocked
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/7d2f0db7-9050-414c-908c-91e2656f5799)

4. Wait ~5 min (sometimes more) and reloaded the website - trackers are not blocked

**Expected results:**
When Ghostery is paused (the site is trusted), any trackers cannot be modified or blocked.

**Versions:**
```
Browser: Safari 17.5.1
OS: iOS 17.5.1
GBE 10.3.5
```

**Comment by smalluban** [comment]
It looks like technically everything is right, and there is nothing we can do on Safari to make it "faster". However, there is an issue about how to provide some feedback to users, and this process may take a lot of time.

Closing in favor of #1645
