### ISSUE TITLE
Feedback from DNR update

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1645]
Some operations like Trusting a site, Trusting a tracker, Pausing Ghostery, Toggling Ad-Blocking/Anti-Tracking/Never-Consent, require a DNR update. Those updates take time and on a slower hardware (mobile) and in Sarafi take take even few minutes.

We need to provide feedback to the users of those function so they understand that browser needs time to apply the requested changes.  

It will fix:
* https://github.com/ghostery/ghostery-extension/issues/1640
* https://github.com/ghostery/ghostery-extension/issues/1625

**Comment by smalluban** [comment]
After a deep dive into how Safari on iOS enables and disables DNR rules, sadly, I have no outcome. 

The only technical feedback that we can get, is to what for the promise from `chrome.declarativeNetRequest.*`, but at most I had a delay of 8-10 seconds (FYI in Chrome it's about 40-50ms). Still, it looks like the update is not finished somewhere in the native part, as a user must wait for the effect from 10 seconds to even 4-5 minutes (or by restarting Safari, tab, etc...). Regardless of the reason, we are not able to provide feedback for random delay. 

For now, I would close the issue. @GRadziejewski please re-open, if we have several support tickets about the subject. Then, it may mean that something else is wrong (or even we have some bug). For now, the code works as expected - the "only" problem is a delay.
