### ISSUE TITLE
Adding a new site to adjust protection doesn't work

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1678]
**Description**
Clicking "Add" button to add a new website to adjust protection, doesn't work.

**Steps to Reproduce**
1. Open chrome-extension://.../pages/settings/index.html
2. Open Websites tab
3. Click on "Add" button

https://github.com/ghostery/ghostery-extension/assets/40433708/84ee66f4-e390-44b5-b98a-13ddc2f8d886

**Expected results**
Adding a new site to adjust protection must work

**Versions**
```
Browser: Chrome 126.0.6478.62
OS: Windows 10
GBE 10.3.9

Browser: Opera 111.0.5168.25
OS: Windows 10
GBE 10.3.9
```

**Comment by smalluban** [comment]
Fixes with https://github.com/ghostery/ghostery-extension/commit/545cbae5ea9eb1e68184cb4950cb467707c26e0a

**Comment by GRadziejewski** [comment]
Fixed.
