### ISSUE TITLE
Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#1687]
Ghostery 10.3.9 error details:
```
Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.
```

Originally reported here: https://github.com/ghostery/ghostery-extension/issues/1653#issuecomment-2181754066

I have also seen it once after an extension update, but did not notice any problems. Afterwards, I could not reproduce.

**Comment by smalluban** [comment]
It is the browser artefact, generated in the first moment of loading extension:

<img width="345" alt="Zrzut ekranu 2024-06-25 o 09 14 15" src="https://github.com/ghostery/ghostery-extension/assets/1906677/d3d626ff-4501-40b3-bece-c307400ad131">

I think it would be possible to re-produce the error, if the user uses an unpacked extension from the file system, and tries to load again the extension with that directory already created. However, I couldn't reproduce it.
