### ISSUE TITLE
Conflicts with https everywhere

### ISSUE THREAD

**Issue by michaldybczak** [ghostery/ghostery-extension#17]
### Description

I got notification about extension error on google chrome. I went to extension page and I saw this error message (translated roughly from my native language):

_Extension didn't redirect web call to https://domain.com/ads.html because other extension (HTTPS Everywhere) redirected it to https://www.domain.com/ads.html._

Here is the screen:
![screenshot_20180329_100255](https://user-images.githubusercontent.com/10132958/38077179-5c935574-3338-11e8-86c8-1ec492a29ab0.png)

### Expected Behavior 

No errors.

### Actual Behavior 

As described above

### Steps to Reproduce

I've been running ghostery with HTTPS Everywhere since few weeks and this error showed just now, so I'm not sure how to reproduce it. I don't get it (so far) on Chromium although I have synced it with the same account.

### Versions

+ Browser: Google Chrome 63.0.3239.132 (64-bit)
+ OS: Manjaro Linux
+ Node:?
+ NPM:?

**Comment by trickpattyFH20** [comment]
looking at the the webRequest API docs, it seems like this might not be fixable.
https://developer.chrome.com/extensions/webRequest#implementation

> Only one extension is allowed to redirect a request or modify a header at a time. If more than one extension attempts to modify the request, the most recently installed extension wins and all others are ignored. An extension is not notified if its instruction to modify or redirect has been ignored.

based on this [superuser discussion](https://superuser.com/questions/925524/repeating-chrome-extension-error-failed-to-redirect) It seems like one potential workaround could be to exclude specific domains from HTTPS Everywhere.

does anyone have any other ideas on how to address this? @jsignanini @chrmod @christophertino  ?

**Comment by ghostwords** [comment]
This sounds like the same issue as https://github.com/EFForg/https-everywhere/issues/14961#issuecomment-378595156.

**Comment by michaldybczak** [comment]
Yes, it looks like this is the same issue and it was posted 8 days sooner and has more attention so I guess my thread can be closed. There is no need to duplicate topics and it's better to focus on one.

The error message happens rarely (I've seen it twice so far) and it doesn't affect any functionality so it's not a big problem but as stated on the other thread, chrome error messages are raising a red flag and the error is applied to ghostery so it doesn't look good.
