### ISSUE TITLE
Where is the opt-out?

### ISSUE THREAD

**Issue by Kees1958** [ghostery/ghostery-extension#1701]
I have not used Ghostery for a while. I am now trying it againg to see how the custom filters (hidden) option works (great ntil now). 

But I remember a telemetry opt-out option in previosus versions. Where is it?

**Comment by chrmod** [comment]
Hi @Kees1958 the new version of Ghostery removed all extended telemetry signals, consequently the switch was also removed. 

We're very happy you have found the custom filters :) Please note that it does not support all features yet, specifically scriplets are not working, but the basic network and other cosmetic filters should work just fine.

**Comment by Kees1958** [comment]
@chrmod 

RE: TELEMETRY: 
Thanks for explaining. From a marketing point of view I had expected this (positive) change to get more attention (or did I completely overlooked it)?

RE: FEATURES of simple custom rules
Are you sure you want to provide such advanced funtionality (like scriptlet injection) for a tool which has "simple"  in its name?

With three cosmetic filter rules (and  URL DNR like rules) rules I can hide everything I need on websites with relatively low visitor count or from languages with a limited number of users. Everything which is more complex than below three cosmetic filter rules, should be dealt with filter authors and code writers (IMO):
 
domain.name##div[class*="identifyer of object to be hidden"]
domain.name##div[id*="identifyer of object to be hidden"]
domain.name##div[data*="identifyer of object to be hidden"]

Applying the above rules  requires some basic HTML knowledge and familirization usinhg the right-click-inspect option of yur browser. Dor a "simple" user rule editor, those three cosmetic hiding rules are in the grey zone (of being in scope or out of bound for the projected use-cases).
