### ISSUE TITLE
Consent management does not remove grey/shadow overlay

### ISSUE THREAD

**Issue by Kees1958** [ghostery/ghostery-extension#1702]
Website https://www.kabel24.nl/solar-kabel-4mm-zwart-5-meter-met-mc4-connectoren/

Two questions: 

1. Please fix problem with consent management (cookie popup is blocked but the overlay preventing the user to proceed NOT)

2. Please bring back the old -per website - option to disable (trus) or enable all ffilter categories (and  allow user to set the default levels per categaory again). The old GUI was so much better.

**Comment by chrmod** [comment]
Hi @Kees1958 thank you for reporting the broken page. Here is a fix - should go live by Tomorrow morning https://github.com/ghostery/broken-page-reports/pull/714

**Comment by chrmod** [comment]
@Kees1958 when it comes to Ghostery customisations. You can still trust the full website from the panel:
<img width="345" alt="Screenshot 2024-06-28 at 12 54 58" src="https://github.com/ghostery/ghostery-extension/assets/1228153/c812456b-5114-4593-b4c8-569e995f5fbd">
Key difference to Ghostery 8 is that now trusting is time scoped, so it goes back to safe defaults after a period of time.

You can also decide to trust individual activities per website with use of exceptions - it works pretty much the same as in Ghostery 8:
<img width="351" alt="Screenshot 2024-06-28 at 12 59 14" src="https://github.com/ghostery/ghostery-extension/assets/1228153/19b4c966-ff5b-4d6f-b1f8-bee1c6485c8b">


The toggling of whole categories is indeed gone, but it has a very good reason. Ghostery 10, blocks pretty much all trackers from all categories by default, without breaking functionalities that come from the companies behind them, like comments widgets or audio/video players. 

We appreciate your contribution. Please keep sending us feedback on Github or at support@ghostery.com.
