### ISSUE TITLE
Outdated information on ghostery website about telemetry 

### ISSUE THREAD

**Issue by Kees1958** [ghostery/ghostery-extension#1703]
@chrmod posted here

 [Where is the opt-out? #1701](https://github.com/ghostery/ghostery-extension/issues/1701) 

that Ghostery does not collect telemetry anymore, while on the website's privacy policy section I telemetr y it states that basic usage stats are collected 

https://www.ghostery.com/privacy-policy

**Comment by smalluban** [comment]
@chrmod posted "all extended":
> ...Ghostery removed all extended telemetry signals, consequently the switch was also removed

Basic telemetry, including ping active signals, is still sent out.
