### ISSUE TITLE
New tab with information about the uninstallation process is not opened

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1708]
**Description**
Clicking on the Ghosty icon to open the full info page initially does not open it. I have to open all the tabs and add a new one - after that a new tab from the add-on opens. 
In addition, if you click the extension icon several times, exactly that many new tabs will open.

**Steps to Reproduce**
1. Open any website, for example: https://ghostery.com
2. Open browser settings
3. Click on the Ghosty icon
4. Nothing happens
5. Open all tabs and click on the '+' icon
6. A new tab will appear with the information from "Uninstall Ghostery".

https://github.com/ghostery/ghostery-extension/assets/40433708/a0507f94-5037-45ec-8caf-b13dd76b27af

**Expected results**
Clicking on the Ghosty icon to open the full info page should open a new tab with.

**Versions**
```
Browser: Safari
OS: iOS 17.5.1
GBE 10.3.12 (179)
```

**Comment by smalluban** [comment]
It must be a Safari iOS bug related to the event listener triggered when the "window" view is not active - it is done by clicking on the native menu element, not on the web page.

I found that behavior too, but from the code perspective, there is nothing else we can do.

**Comment by GRadziejewski** [comment]
OK. 
The issue will not be fixed.
