### ISSUE TITLE
Trusting vs Pausing

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1716]
Decisions to make:
* [x] naming - "Trust this site" stays
* [ ] colors - change to functional color yellow in ON state
* [x] time options - remain in existing order
* [ ] update explainers on the time options
This site will be trusted for 1 hour
This site will be trusted for 1 day
This site will always be trusted. You can change this at any time in Ghostery settings to stop trackers and ads from tracking you around the web.

**Comment by smalluban** [comment]
![Image](https://github.com/ghostery/ghostery-extension/assets/1906677/380ea93e-a002-492d-9f7d-3b5b115c9e9e)

The was no "yellow" color in the Ghostery Panel Design System. I took one from the Ghostery Web Design System - `warning-500`. However, the color is too light to use white text color, I switched to `gray-700`.

Please confirm the choice.

**Comment by smalluban** [comment]
Also, I think the contrast here is also bad... especially on the toggle. However, in that subject, I would re-think if we should switch completely to the normal toggle, which applies the "exception", not a "trusted/blocked" one.

![Image](https://github.com/ghostery/ghostery-extension/assets/1906677/59255630-ca6d-4ab3-8209-fa36f8c2580f)
![Image](https://github.com/ghostery/ghostery-extension/assets/1906677/1b18426e-4e38-4873-b81b-048dc68b21a8)

**Comment by smalluban** [comment]
I made a draft PR with a package label, you should be able to test out the current changes on your machine if this is better for you.

**Comment by GRadziejewski** [comment]
Yellow - it looks wrong. The previous colour - green, looks much better.

I have found something like this: https://www.figma.com/design/0HIwg2OfZmw4hKyVl6f7kQ/Ghostery-Panel?node-id=1871-11148&t=x4Qjug7NEldzyA0i-4
From which, maybe the blue colour would be good for the pause state?
![image](https://github.com/user-attachments/assets/f8d8aecf-e379-4acf-9277-f8bf1170f927)


Or we can go with this orange colour: https://www.figma.com/design/ZDePWBimq04bD90s3QkaC3/Ghostery-Prototypes?node-id=1-57&t=x4Qjug7NEldzyA0i-4
![image](https://github.com/user-attachments/assets/73001cec-19b4-4e5d-a327-0b2dcec6eeb2)


Or, we could go with some colour from our website colour palette: https://www.figma.com/design/bDQ8eglnrxg8O4lpqPXwai/Ghostery-Web-Design-System?node-id=9-611&t=x4Qjug7NEldzyA0i-4

**Comment by philipp-classen** [comment]
The yellow in the PR would be okay for me, but I do not hold a strong opinion.  

One comment unrelated to the color. When switching back and forth between simple and detailed view, the page loses its trusted state. Perhaps it is expected in this PR; if not, these would be steps to reproduce:

1. Go to any page (e.g. spiegel.de)
2. Go to detailed view
3. Trust any activity (e.g. Google Tag)
4. Trust this site
(Now the Site is trusted and yellow)
5. Go to simple view
(Now the Site is no longer trusted)

**Comment by smalluban** [comment]
I found when working on regional filters  that somehow nested records might be cleared. I suppose this is a bug. Working on it.

However, this is only on main (not yet released).

**Comment by smalluban** [comment]
@philipp-classen I made a fix in hybrids - https://github.com/ghostery/ghostery-extension/pull/1737

**Comment by philipp-classen** [comment]
> @philipp-classen I made a fix in hybrids - #1737

Confirmed. That fixes it.
