### ISSUE TITLE
Custom filters: User facing interface

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1717]
Custom filters UI is no hidden in the "developer menu" in **Privacy Protection** tab of Ghostery settings. 

Without new design we cannot introduce new tab in the settings so need to squeeze the Custom Filters somewhere on the current tab. Privacy Protection seems to be a best candidate. 

The UI should not change much as this is a power user feature. We need some simple explanation what can be done and what cannot. 

Aspects to take care of:
* should we link to external documentation? Currently we link to AdGuard's but maybe it is not best to link to another adlocker.
* add a checkbox to trust "trusted scriptlets"
* explain that scriptlets are not working yet. We can say they are coming soon. 
* should we should DNR output or it is fine if it remains hidden under the developer menu?

**Comment by smalluban** [comment]
I prepared a branch, in which I moved the feature to the Privacy protection section. @chrmod You can take it over from here if you want to change the copy etc.

https://github.com/ghostery/ghostery-extension/pull/1734
