### ISSUE TITLE
Trust site does not work

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1719]
Affected website: https://www.llcooljams.com/

**Comment by philipp-classen** [comment]
Could be a duplicate of https://github.com/ghostery/ghostery-extension/issues/1690

With the master version (plus https://github.com/ghostery/ghostery-extension/pull/1713), it works for me.

**Comment by philipp-classen** [comment]
Confirmed. Closing it as a duplicate of https://github.com/ghostery/ghostery-extension/issues/1690
