### ISSUE TITLE
GTM is not blocked when added to blocked exceptions

### ISSUE THREAD

**Issue by smalluban** [ghostery/ghostery-extension#1720]
The current GTM script is loaded from URL: `https://www.googletagmanager.com/gtag/js`

The TrackerDB has only one filter defined here https://github.com/ghostery/trackerdb/blob/main/db/patterns/google_tag_manager.eno

> ||googletagmanager.com/gtm.js^$3p

As it could be just the TrackerDB issue, I pointing it out here, as from the user perspective the feature does not work in the extension. The TrackerDB is just a database for those trackers. 

When trying to add GTM to blocked exceptions, the requests are still passed through.

Also, I found that we have duplicated rules for GTM in DNR lists:

`dnr-ads`:

> {"id":47597,"action":{"type":"block"},"condition": {"urlFilter":"||googletagmanager.com^","domainType":"thirdParty","isUrlFilterCaseSensitive":false},"priority":2}

`dnr-tracking`:

> {"id":3365,"action":{"type":"block"},"condition":{"urlFilter":"||googletagmanager.com^","isUrlFilterCaseSensitive":false},"priority":1}

The tracking is even wider, as it does not set `domainType` to `thirdParty`. 

However, we have a few rules, which just allow GTM for specific domains (`dnr-ads`):

> {"id":56080,"action":{"type":"allow"},"condition":{"urlFilter":"||googletagmanager.com^","initiatorDomains":["dev.miuiflash.com","djxmaza.in","thecubexguide.com","jytechs.in"],"resourceTypes":["script"],"isUrlFilterCaseSensitive":false},"priority":100226}

Should we add `allow` rules to the `dnr-ads` or `dnr-tracking` in the first place?

**Comment by philipp-classen** [comment]
We are trying to improve the Google Tag Manager rules in TrackerDB, started here: https://github.com/ghostery/trackerdb/pull/378

With this PR, the `https://www.googletagmanager.com/gtag/js` requests should be matched as advertising (no longer essential): https://github.com/ghostery/trackerdb/pull/382

Ideally, TrackerDB should also classify the requests that are really essential as essential. Hopefully, that solves some of these problems in the extension as well.

**Comment by smalluban** [comment]
I see an update in TrackerDB. As we don't plan to do more on the subject, I am closing the issue.
