### ISSUE TITLE
DNR API mistakenly blocks requests across extensions (up to Chrome 127)

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#1742]
Ghostery should not be able to [block requests from other extensions](https://github.com/w3c/webextensions/issues/369#issuecomment-2188561403). A fix [will be part of Chrome 128](https://chromiumdash.appspot.com/commit/486d638e6977dad73bd207dc914df9319afac152), but earlier versions of Chrome are affected.

There is not much that we can do in Ghostery, since it is a bug in Chrome (and all Chromium forks). When the fix hits Chrome Stable, it should be fixed. So, this ticket is mostly for documentation.

Examples:
* HubSpot Sales extension: https://github.com/ghostery/broken-page-reports/issues/765

**Comment by smalluban** [comment]
The current production version of Chrome is 131 (4 versions ahead). I think it is safe to close the issue. It still will be searchable for information purposes.
