### ISSUE TITLE
update descriptions for all extension stores- July 2024

### ISSUE THREAD

**Issue by mdsandu** [ghostery/ghostery-extension#1753]
Let's use the new era of G10 and update all extension descriptions. They are SEO optimized per store. [Find them here](https://hackmd.io/UL1xofOuTmejdXTceWNEzA)

- on every store English version and full localizations for German and French should be updated
- short descriptions remain the same - no update needed (e.g. Polish, Korean, etc) 

- [x] Opera store, mark date of update 
- [x] Edge store, mark date of update 
- [x] Chrome web store, mark date of update 
- [x] Apple App Store, mark date of update 
- [x] Firefox, mark date of update

**Comment by smalluban** [comment]
App Store updated with the upcoming 10.3.14, I'll mark when it will go live.

**Comment by smalluban** [comment]
@chrmod I think the rest platform must have a new package uploaded first to be able to touch the descriptions, so please update them next week when pushing v10.3.14

**Comment by chrmod** [comment]
All descriptions submitted for review on 2024-07-22
