### ISSUE TITLE
Install cannot complete on macOS Safari

### ISSUE THREAD

**Issue by luraess** [ghostery/ghostery-extension#1761]
After switching to the new Ghostery on macOS Sonoma, the install cannot complete due to the missing "Open Safari Preferences ->" button on the Ghostery App splash screen:

<img width="1012" alt="Screenshot 2024-07-23 at 22 59 18" src="https://github.com/user-attachments/assets/30e273a1-3db7-4e2c-83e2-0e3b81fa9f9f">

This makes it impossible to install and activate the extension. The extension correctly installed from AppStore.

This occurs on:
- macOS Sonoma 14.5
- Safari Version 17.5 (19618.2.12.11.6)

**Comment by GRadziejewski** [comment]
Hi @luraess, thank you for your ticket. I see the ticket in our support system, so I've responded to you with step-by-step instructions on how to install and activate our extension. If you experience any problems, please write back either here on GH or by email.

**Comment by luraess** [comment]
Thanks @GRadziejewski for your helpful reply. I could finalise the install. For some reason, the Ghostery extension was not showing up in the extension tab in the Safari preferences, nor as greyed icon next to the tab bar. Now, however, it worked. Closing this issue.

**Comment by GRadziejewski** [comment]
Thank you for the information!
