### ISSUE TITLE
Support Arc Browser

### ISSUE THREAD

**Issue by harusakura924** [ghostery/ghostery-extension#1763]
Question:
I installed the Ghostery extension using Arc Browser. After installation, when I click on Ghostery, a blank window pops up.

![2024-07-24 23_57_04-設定](https://github.com/user-attachments/assets/67770c86-0872-4c0f-9b50-46e2dd3acaf8)

Expectation:
After installing the Ghostery extension, when I click on Ghostery, a window displaying the Ghostery dashboard should appear, just like how other extensions use windows to display their content.

Notes:
Arc Browser is built on the Chromium Engine.
Arc Version 1.11.3(39079)
Chromium Engine Version 126.0.6478.183
Operating System Version: Windows 11 Pro 23H2
OS Build: 22631.3880

Arc Browser is a modern web browser developed by The Browser Company, aimed at improving users' web browsing experience.

**Comment by chrmod** [comment]
Hi @harusakura924 - thank you for reporting. This is an Arc browser issue, specifically Arc for Windows. Ghostery works perfectly fine in all chromium based browser and Arc is no exception. In this case this is an Arc bug, so please report to their team. (we see similar bugs in early days of Arc for MacOS and typically Arc team were resolving them fast).
