### ISSUE TITLE
Ghostery macOS Safari extension not installing

### ISSUE THREAD

**Issue by davidhlawrence** [ghostery/ghostery-extension#1764]
I was just forced to upgrade to the new version of Ghostery but it's not installing the extension in Safari. The app opens but there's no link to open the Safari Preference Panel. See attached screenshot. How do I fix this? I'm on macOS 12.7.5. Thanks!

<img width="395" alt="Screen Shot 2024-07-29 at 9 24 05 AM" src="https://github.com/user-attachments/assets/c8737612-6839-4bb3-8eaa-624cf399c974">

**Comment by GRadziejewski** [comment]
Hi @davidhlawrence ,
 
Thanks for reaching out to Ghostery!
 
Please follow the steps to install our extension on Safari: 
1. Open https://www.ghostery.com/ghostery-ad-blocker-safari
2. Click on "Get Ghostery for Safari" 
3. The App Store should be opened. Ghostery Privacy Ad Blocker should be visible.
![351678849-4c4de2af-8c49-4fe4-b2bc-ef1acea05ce5](https://github.com/user-attachments/assets/084408f9-8fea-4105-9d4e-263f9f88b327)

4. Click the cloud icon to download and install
![351684870-7a562e25-7f08-4f0d-bcf1-db439bc16bee](https://github.com/user-attachments/assets/fd5a7dc0-13f5-4a7d-8d5d-b4f2154b5e27)

5. Go to your Safari browser. The Ghostery icon should be visible on the left side of the address bar. There should be a grey icon with a yellow triangle.
![351700139-7b439e59-3f26-45c6-8f90-67d9b2f7a15b](https://github.com/user-attachments/assets/b4d45fc0-b57c-4c44-bf6b-0d23eb6e773e)

6. Click the Ghostery icon. A pop-up should be visible. Click on "Always Allow on Every Website".
![351679458-1471a231-52d1-4dad-a74b-cad19b8ab6d1](https://github.com/user-attachments/assets/ccf4f77a-612e-4c35-9aba-d79641b57e4d)

7. A second pop-up appears. Click on "Always Allow on Every Website"
![351679628-2f289287-9c29-407b-98aa-fe686ad50e60](https://github.com/user-attachments/assets/2c2d7969-a527-473f-ad00-a9310a39a0e8)

8. Reload the website. The Ghostery icon should be blue with a red circle.
![351700504-2914f16d-e18a-4c86-8608-b4cf5a27e205](https://github.com/user-attachments/assets/f936bc64-c5a1-4fd6-a40c-c7705fc6991c)

9. Click the Ghostery icon. A pop-up asking you to enable Ghostery appears. Click on "Enable Ghostery".
![351698431-ef5c9fb9-4181-4026-b9c6-fc4c4f55ef75](https://github.com/user-attachments/assets/8dc11027-cdee-487d-acf1-354d62c286dd)

10. A new tab opens. Click on "Enable Ghostery".
![351698699-0c157d4a-a6f1-474d-b9d1-b35a235b3ca9](https://github.com/user-attachments/assets/6a11fcfe-7510-431d-a8b1-6f8fa6e47e71)

11. Reload the website. Click on the Ghostery icon. Ghostery panel should be visible with enabled functionality.
![351679903-ae124891-485d-4396-99b2-b5b29744498f](https://github.com/user-attachments/assets/14b34bdd-6a96-4dce-a5a1-6383c91f9773)

Ghostery is now ready to protect you while browsing the web.
 
Here for any other questions.
 
Best,
Ghostery Support

**Comment by GRadziejewski** [comment]
I also responded to a ticket on our support channel.

**Comment by davidhlawrence** [comment]
Thank you for the reply. Please look at the attached screenshot. **There is no link in the app to install the extension.**

The new version of the app is broken. Please fix. Thanks!
<img width="395" alt="Screen Shot 2024-07-29 at 9 24 05 AM" src="https://github.com/user-attachments/assets/b0a2b10e-d752-484d-ae5e-8195bec4ae81">

**Comment by GRadziejewski** [comment]
There is no need for a link here, it is already installed. If you could check your browser to see if you have it there. If you open Safari -> Settings -> Extensions, our extension should be installed there. 

![image](https://github.com/user-attachments/assets/94589d5b-6737-45a0-9adc-b503a64ca6ee)

**Comment by davidhlawrence** [comment]
It is **not** in the extensions panel. I've reverted to version 10.2.6 which is working fine.

**Version 10.3.14 is broken on macOS Monterey. Please fix.**

Thanks!

**Comment by GRadziejewski** [comment]
We are supporting macOS 12+ so it should be working on your side. Can you share a screenshot of your Safari settings to check if the browser can see our browser extension? Are there any errors?

***

If you refer to the attached screen, there were previously steps showing how to enable Ghostery. 
In a previous version (10.3.11), it looks like this on macOS:
![image](https://github.com/user-attachments/assets/1b99055b-688a-4610-8ff6-64f15be3e9e0)

With the latest version (10.3.14), it looks like this:
![image](https://github.com/user-attachments/assets/ac1f6b5e-ee6c-479a-9fc3-14a0287bd2b2)

On iOS as a reference (10.3.14), it looks like this:
![image](https://github.com/user-attachments/assets/9a0d2e9e-6c3e-44cc-a9cd-f33806d1deac)

**Comment by davidhlawrence** [comment]
Hello,

I just moved version 10.2.16 to the desktop and reinstalled 10.3.14. I also updated Safari to version 17.6.

This time the extension automatically installed and is running properly. You can go ahead and close this case. Thanks for your help!

--David

**Comment by GRadziejewski** [comment]
Thank you for the information!

**Comment by davidhlawrence** [comment]
Hi Ghostery folks,

Your extension updated and broke again in Safari 17.6 for macOS Monterey 12.7.5.

Please take a look and fix. Thanks!

**Comment by davidhlawrence** [comment]
Hi Ghostery support, 

Ghostery v10.4.1 is broken again on macOS Monterey 12.7.5 Safari 17.6.

Please fix, thanks!

**Comment by GRadziejewski** [comment]
Hi @davidhlawrence, I am really sorry about that.
I have just tested the production version and as far as I can see, everything works as it should. Can I ask you kindly to reinstall and see if this has made any difference?

**Comment by davidhlawrence** [comment]
Just reinstalled 10.4.2 and it's working fine again. I don't know why it sometimes breaks. When it does, rolling back to 10.2.16 always works. It's all very odd. Thanks for your help and hopefully it's now stable.

**Comment by levin-lab** [comment]
Hello, I'm having the same issue. Safari Version 17.6 (17618.3.11.11.7, 17618). macOS Monterey 12.7.5. Ghostery Version 10.4.15 (50). Extension not showing in Safari extension prefs. Thanks.
<img width="512" alt="image" src="https://github.com/user-attachments/assets/a8254645-868f-4a88-b90c-9e449d7f98cb">

**Comment by levin-lab** [comment]
just updated to Monterey 12.7.6, deleted and re-installed Ghostery and it works.
