### ISSUE TITLE
Detailed view: update selective blocking tooltip

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#1772]
Tooltip over selective blocking icon should be a summary of the adjustment once applied (fine to keep the current tooltip when no adjustments)

Possible statuses (same as in tracker details and in selective blocking dialog):
* Blocked on all sites
* Blocked on this site
* Allowed on all sites
* Allowed on this site

**Comment by smalluban** [comment]
Fixed with 1021935f58aa6665659c772a99bf62ec499fd585
