### ISSUE TITLE
It's not always possible to set the default protection status

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1779]
**Description**
After the attempt to revert the protection status to the default state, it's not possible for most cases. (Go to 35 sec of the video)

**Frequency**
8/10

Scenario 2
**Steps to Reproduce**
1. Open any website, for example https://www.espn.com/
2. Open Ghostery panel no Detailed view
3. Open details for any tracker, for example Adobe Audience Manager
4. Click on "Blocked on all websites" button to open protection status
5. Click on "Trust on this website" button
6. Go back to the tracker details and click on the cog wheel
7. Ghostery Settings should be open with focus on this tracker details
8. Refresh the site
9. Set focus on the Trackers tab. Set filtering by Adjusted view.
10. Change protection status to the default (blocked)

https://github.com/user-attachments/assets/08171ffd-044f-4f59-bb22-c1d2d0d395f9

**Expected results**
There should be always possibility to revert protection status to the default.

**Versions**
```
Browser: Chrome 127.0.6533.89
OS: Windows 10
GBE 10.3.16

Browser: Safari 17.6 (19618.3.11.11.5)
OS: macOS 14.6 (23G8Q)
GBE 10.3.16

Browser: Firefox 128.0.3
OS: Windows 11
GBE 10.3.16
```

**Comment by smalluban** [comment]
As it seems to be odd, this is current production behavior. We need to stick with adjusted flag as long as there are some domain exceptions.
