### ISSUE TITLE
A link to open Safari preferences on macOS is missing

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1781]
**Description**
A link to open Safari preferences on macOS is missing.

**Steps to Reproduce**
1. Install the extension
2. Open the splash screen
![image](https://github.com/user-attachments/assets/09fe1516-7e75-443c-b0a4-71f3baaa1cd4)

**Expected results**
It should look like this on macOS
![image](https://github.com/user-attachments/assets/1b99055b-688a-4610-8ff6-64f15be3e9e0)

**Versions**
```
Browser: Safari 17.6 (19618.3.11.11.5)
OS: macOS 14.6 (23G8Q)
GBE 10.3.16
```

**Comment by smalluban** [comment]
@GRadziejewski Please try to confirm if the bug is already in production - as it is already on 10.3.14. This view is generated with data, which comes from the native part. It wasn't touched for a long time.

**Comment by GRadziejewski** [comment]
@smalluban Yes, this is a production problem. The last version where this was correct was 10.3.11. With the next version, the problem described still occurs.
It has also been checked and confirmed here: https://github.com/ghostery/ghostery-extension/issues/1764#issuecomment-2259827175

**Comment by smalluban** [comment]
Fixed in above commit.

**Comment by GRadziejewski** [comment]
Checked. Fixed.
