### ISSUE TITLE
Enabled Ghostery extension leads to loss if icon on multiple web-sites

### ISSUE THREAD

**Issue by Snysnym** [ghostery/ghostery-extension#1785]
**Description:**

After enabling Ghostery extension, icons on multiple web-sites are not showing until Ghostery is disabled.

**Environment:**
1. Device: PC
2. Browser: Google Chrome version 126 (bug can be found on all versions from 126.0.6478.118 and up)
3. OS: Windows 10 Pro, Version 22H2
4. Ghostery: version 10.3.16

**CASE 1:**

**Steps:**
1. Open Google Chrome browser
2. Enable Ghostery extension
3. Open [www.gitlab.com](http://www.gitlab.com/) and authorize there
4. Open an excisting issue

**Actual Result (AR):**

![Снимок экрана (1541)](https://github.com/user-attachments/assets/b068fff1-7547-44aa-85c6-e7c833d443da)

**Expected Result (ER) (Ghostery off)**

![Снимок экрана (1542)](https://github.com/user-attachments/assets/81f6ceea-a094-4d27-94c6-e1a5247b29f9)

**CASE 2:**

**Steps:**
1. Open Google Chrome browser
2. Enable Ghostery extension
3. Open site www.habr.com 
4. Scroll down until `Новости` or `News` label appeares

**Actual Result (AR):**

![Снимок экрана (1544)](https://github.com/user-attachments/assets/e49861aa-3e3a-44e0-9dfc-1cb31fb6e305)

**Expected Result (ER) (Ghostery off)**

![Снимок экрана (1545)](https://github.com/user-attachments/assets/30c42bb0-9142-4268-b10b-b80aaa89bae2)

**Additional information:**

Bug appeared starting from 6th of July 2024, not seen before this date

**Comment by bvogel** [comment]
I'm facing the same issue, disabling the adblocker currently is the only solution I found. I can't seem to find a way to add an exception to allow https://gitlab.com/assets/icon_anchor-297aa9b0225eff3d6d0da74ce042a0ed5575b92aa66b7109a5e060a795b42e36.svg (as an example)

**Comment by chrmod** [comment]
Thank you for reporting. We've identified the source of the problem which comes from a platform limitation https://github.com/w3c/webextensions/issues/493 
For now, we can only mitigate the full problem, but the fix for gitlab is a a way!

**Comment by GRadziejewski** [comment]
@Snysnym, @bvogel there is a new version. I've checked on my side and I can see that the problem has been fixed. If you can check on your side if everything is working properly, that would be great. Thank you!

**Comment by bvogel** [comment]
Thank you I can confirm it is fixed now.

**Comment by chrmod** [comment]
Amazing! Thank you once again for your help!
