### ISSUE TITLE
AdBlock wall - mutationObserver.observe error

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1796]
There is an error:

![image](https://github.com/user-attachments/assets/ab7ca1bb-bbcd-43dc-8318-04c75a1f992e)

```
Firefox 129.0
Windows 10
GBE: https://github.com/ghostery/ghostery-extension/pull/1790
```

**Comment by smalluban** [comment]
PR closed

**Comment by smalluban** [comment]
It looks like this bug is not related to the testing environment (the closed PR).

**Comment by smalluban** [comment]
The error was thrown by the code in `/content_scripts/youtube.js`:

```js
document.addEventListener('DOMContentLoaded', () => {
  observer.observe(document.body, ...);
});
```

From technical point of view, it is not possible that `document.body` is not available in `DOMContentLoaded` event callback. If the error existed, it must have been related to scriptlets injected into the YT page. 

I cannot reproduce the error anymore.
