### ISSUE TITLE
Ticking the checkboxes to block items from miscellaneous category, only the last will be saved

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1816]
**Description**
When ticking the boxes to block sites listed in the miscellaneous category in the global blocking settings, only the last site will be saved.

**Steps to Reproduce**
1. Open any website, for example https://www.nytimes.com/
2. Click on the kebab
3. Open Extension/ Ghostery panel
4. Open Global Blocking
5. Scroll down to the Miscellaneous category and open it
6. Block few first items on the list
![image](https://github.com/user-attachments/assets/961b56f3-1e73-4563-8c47-35a11724d5df)

7. Close the Ghostery panel and open it again
8. Only the last blocked item is actually blocked
![image](https://github.com/user-attachments/assets/4d3a1fd7-69f2-4022-957e-1ae29d08ae0a)

**Expected results**
When the checkboxes are ticked to block sites listed in the miscellaneous category, all of them must be saved.

Versions
```
Firefox
Android 14
GBE 8.12.13
```

**Comment by smalluban** [comment]
The last platform migrated to v10.
