### ISSUE TITLE
In landscape view, you cannot scroll to the bottom

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1828]
**Description**
When switched to the landscape view, it is not possible to scroll and see all the information available on the panel.

**Steps to Reproduce**
1. Open any website, for example https://www.aarp.org/
2. Open Ghostery panel and select detailed view
3. Rotate the smartphone to horizontal view
4. Try to scroll to the bottom
5. Open the menu and try to scroll to the bottom

https://github.com/user-attachments/assets/09bd3435-5605-4ad5-9ea6-f7405d062bf7

https://github.com/user-attachments/assets/95032485-c58c-4894-b9cc-ab3275c5b387

**Expected results**
You should be able to see all the available information in the Ghostery panel, as well as all the menu options, in landscape and portrait views.

Versions
```
GBE 10.4.1
```

**Comment by smalluban** [comment]
Fixed in `10.4.4`
