### ISSUE TITLE
Adding a regional list for Persian sites

### ISSUE THREAD

**Issue by MasterKia** [ghostery/ghostery-extension#1853]
Hi, is it possible for you to add this list for Persian sites to the default lists?
https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlocker.txt

![image](https://github.com/user-attachments/assets/d030296d-1988-4f48-98a4-e75c64d92d8c)

It is already used by uBlock Origin, AdGuard and other content blockers.

**Comment by seia-soto** [comment]
Hi @MasterKia ,

Thank you for the suggestion. I've proposed an update to our system and I expect the filter list will be available in near future releases.

Best
