### ISSUE TITLE
Sponsored ads on the Google

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1861]
**Description**
Sponsored ads are visible on the Google search page.

**Steps to Reproduce**
1. Make sure to check "Allow access to search page results"
![image](https://github.com/user-attachments/assets/bb99e94c-a36a-4a9e-a342-28725d37d01e)
2. Open https://www.google.com
3. Type any search query, for example "samsung"
4. Sponsored ads are visible
![image](https://github.com/user-attachments/assets/b23f14ff-d513-497b-a245-a6c654f264ce)

**Expected results**
Sponsored ads shouldn't be visible on the Google search page.

Versions
```
Browser: Opera 113.0.5230.62
OS: Windows 10
GBE 10.4.3
```

**Comment by chrmod** [comment]
@GRadziejewski I cannot reproduce. Please check once again as this sounds like a mission critical problem

**Comment by smalluban** [comment]
I can't reproduce with the current `main`. For me, it looks like the extension was still not "allowed" on SERPs - the panel screenshot shows no found trackers. It must have been a browser glitch.
