### ISSUE TITLE
Cookie pop-up  on Google 

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1862]
**Description**
Cookie pop-up is not hidden on the Google page.

**Steps to Reproduce**
1. Make sure to check "Allow access to search page results"
![image](https://github.com/user-attachments/assets/bb99e94c-a36a-4a9e-a342-28725d37d01e)
2. Open https://www.google.com
![image](https://github.com/user-attachments/assets/ceb88de8-ea75-4018-beb8-3d864bcbce61)

**Expected results**
Cookie pop-up must be hidden on the Google page.

Versions
```
Browser: Opera 113.0.5230.62
OS: Windows 10
GBE 10.4.3
```

**Comment by smalluban** [comment]
Can't reproduce with current `main`. After onboarding, I enabled SERPs, open google.com - no popup, trackers are blocked.
