### ISSUE TITLE
Add translations for new "utlity" category

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#1885]
Background: The "essential" category in TrackerDB as been [renamed as "utility"](https://github.com/ghostery/trackerdb/pull/423/files).

Two places where we need to provide translations:

1. Ghostery settings (first entries that used to be "Essentials" has no label)
![Screenshot 2024-09-17 at 12-12-30 Ghostery settings](https://github.com/user-attachments/assets/6f66ab23-0168-4568-bac4-de8e5a12baaf)

2. Panel (first entries that used to be "Essentials" has no label)
![panel](https://github.com/user-attachments/assets/34711c09-861f-4e3f-9883-e14dcc09191e)

**Comment by philipp-classen** [comment]
Setting it to "Bug", since after pulling the latest TrackerDB version, it also affects the production version.

**Comment by philipp-classen** [comment]
The production problem should be solved, since we temporarily rolled back the TrackerDB change: https://github.com/ghostery/trackerdb/pull/424

**Comment by philipp-classen** [comment]
> Categories, which are nouns, are written in the popular form, like `comments` or `extensions`. We should go with `utilities` rather than `utility`.
> 
> @philipp-classen @chrmod @mdsandu ?

I tried to keep it consistent with the other categories. All singular, with the exception of "extensions":
https://github.com/ghostery/trackerdb/tree/main/db/categories

**Comment by mdsandu** [comment]
Utilities is what we suggested in the first place. Not sure how it turned into "Utility"
