### ISSUE TITLE
Blocks Google AdWords remarketing even when to configured to allow every tracker

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [ghostery/ghostery-extension#19]
### Description

I use Ghostery to detect and list installed trackers, not to block them. Thus it is configured to accept every tracker.
But I notice an error in the Google Chrome console saying "net::ERR_BLOCKED_BY_CLIENT" which is typical of a network request being blocked by an Ad blocker

https://googleads.g.doubleclick.net/pagead/viewthroughconversion/866289170/?random=1522398994693&cv=9&fst=1522398994693&num=1&guid=ON&resp=GooglemKTybQhCsO&u_h=900&u_w=1600&u_ah=900&u_aw=1538&u_cd=24&u_his=7&u_tz=120&u_java=false&u_nplug=4&u_nmime=5&gtm=G3r&sendb=1&frm=0&url=https%3A%2F%2Fwww.resoneo.com%2F&tiba=RESONEO%20-%20Conseil%20en%20strat%C3%A9gie%20et%20marketing%20pour%20l%27e-business&async=1&rfmt=3&fmt=4
 net::ERR_BLOCKED_BY_CLIENT

The Ghostery panels says no tag were blocked. But this isn't what happens here

### Expected Behavior 

Don't block any tag when configured to accept all

### Actual Behavior 

At least AdWords remarketing hits are being blocked on https://www.resoneo.com/ 

### Steps to Reproduce

1. configure Ghostery to accept all trackers in a blank new Chrome profile without any other extension
2. open Google Chrome Console
3. Visit https://www.resoneo.com/ 
4. https://googleads.g.doubleclick.net/pagead/viewthroughconversion/866289170/?random=1522398994693&cv=9&fst=1522398994693&num=1&guid=ON&resp=GooglemKTybQhCsO&u_h=900&u_w=1600&u_ah=900&u_aw=1538&u_cd=24&u_his=7&u_tz=120&u_java=false&u_nplug=4&u_nmime=5&gtm=G3r&sendb=1&frm=0&url=https%3A%2F%2Fwww.resoneo.com%2F&tiba=RESONEO%20-%20Conseil%20en%20strat%C3%A9gie%20et%20marketing%20pour%20l%27e-business&async=1&rfmt=3&fmt=4 
is canceled
as well as 
https://www.google.com/ads/ga-audiences?v=1&aip=1&t=sr&_r=4&tid=UA-806633-1&cid=890926785.1522398754&jid=362213292&_v=j66&z=1861897420

with net::ERR_BLOCKED_BY_CLIENT 
5. look at Ghostery panel : saying no tracker blocked

If you go to https://www.reddit.com/ you get way more trackers being blocked

### Versions
Ghostery 8.1.0
![ghostery sole extension 2018-03-30_10-39-12](https://user-images.githubusercontent.com/282461/38131705-63ecabce-3408-11e8-883b-da4e493ba298.png)
![ghostery settings and console 2018-03-30_10-38-05](https://user-images.githubusercontent.com/282461/38131706-640c25a8-3408-11e8-9c87-2fa9383e4830.png)

+ Browser: Version 65.0.3325.181 (Build officiel) (64 bits)
+ OS: Windows 10 64
+ Node:
+ NPM:

**Comment by trickpattyFH20** [comment]
@googleanalyticsresoneo in the screenshot you shared it looks like Ad-Blocking is enabled. Can you try disabling it by clicking on the purple stop sign in the Ghostery panel and toggling off, then try that page again?

**Comment by googleanalyticsresoneo** [comment]
@trickpattyFH20 
Pretty confusing double levels of configuration !
Looks better now, but why that message "blocked:0" while 3 other options may fire blocking strategies !

What about enhancing the configuration / options ?

Thanks!

![ghoserty without intelligent blocking 2018-03-30_17-24-03](https://user-images.githubusercontent.com/282461/38143119-5b23bd98-343f-11e8-85a0-ea6c18e5c3b3.png)

**Comment by trickpattyFH20** [comment]
@googleanalyticsresoneo 
agreed, the enhanced settings are a bit confusing in their current state

there are already some UI changes implemented that we plan to release soon. the changes should make it more clear what's happening with the additional ad-block and anti-tracking settings
