### ISSUE TITLE
Youtube keeps going back to Light Mode when Ghostery is Active.

### ISSUE THREAD

**Issue by ChakraaThePanda** [ghostery/ghostery-extension#196]
### Description

I am not sure how often it resets exactly, sometimes it's within the minute, other times it could take up to a few hours, but when navigating on Youtube with Ghostery, the light theme keeps coming back even if I put the dark mode on. It no longer does it if I turn off the extension.

### Expected Behavior 

Keep my Dark Theme on Youtube.

### Actual Behavior 

Doesn't keep the dark theme, goes back to light theme.

### Steps to Reproduce

1. Get on Youtube
2. Activate the Dark Theme
3. Navigate out of Youtube or within Youtube. The Dark Theme will come back.

### Versions

+ Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
+ OS: Windows 10

**Comment by christophertino** [comment]
@ChakraaThePanda can you verify this is still happening? I've been trying to reproduce but haven't had any luck.  Thanks.

**Comment by ChakraaThePanda** [comment]
It is still happening for me everyday.On Nov 27, 2018 17:11, Christopher Tino <notifications@github.com> wrote:@ChakraaThePanda can you verify this is still happening? I've been trying to reproduce but haven't had any luck.  Thanks.

**Comment by ChakraaThePanda** [comment]
And not just on my browser at home. Happens at work as well.On Nov 27, 2018 17:11, Christopher Tino <notifications@github.com> wrote:@ChakraaThePanda can you verify this is still happening? I've been trying to reproduce but haven't had any luck.  Thanks.

**Comment by christophertino** [comment]
Alright, thanks for the update.  I'll keep trying to reproduce.

**Comment by lasithalakmal** [comment]
This might be helpfull
https://www.youtube.com/watch?v=ahgct_SV9uc&ab_channel=AwesomeTutes
