### ISSUE TITLE
Preroll video ads triggered on YouTube in Safari when clicking links or when reloading via link in address bar. 

### ISSUE THREAD

**Issue by AdamGhst** [ghostery/ghostery-extension#1963]
1. Going to a video via YouTube.com and using the YouTube search tool does not trigger preroll ads when starting a video.
2. Clicking through a link triggers a preroll video ad when starting the video.
3. Reloading the video by clicking the address bar and confirming triggers an ad with the page reload in Safari.
4. Quick fix/Workaround: using the reload button in Safari does not trigger the preroll ad.

**Comment by smalluban** [comment]
Fixed with #1977 and #2033
