### ISSUE TITLE
Why ghostery try to connect to 10.0.4.162 or 10.0.5.141 ?

### ISSUE THREAD

**Issue by ContribOpenSource** [ghostery/ghostery-extension#199]
### Description

With extension v8.2.4, I noticed today that it try to connect to 10.0.4.162 or 10.0.5.141, why ?
If this extension is disabled in my browser, there is no request to previous IPs anymore, so it seems to be triggered by ghostery !?

### Expected Behavior 

No request to internal network addresses.

### Actual Behavior 

TCP request sent to previous IPs.

### Steps to Reproduce

1. launch browser
2. wait 2 minutes
3. look at network traffic

### Versions

+ Browser: chromium 65

**Comment by christophertino** [comment]
This issue should be fixed now. Please let us know if you are still seeing those network calls. 

There was a bad header redirect on https://ghostery-sign.ghostery.com/config, which is part of our proxy network.  We use this for our Human Web and Anti-Tracking features.  We deployed an update to our backend last week to clean it up.
