### ISSUE TITLE
Firefox - This Addon could not be installed because it has not been verified.

### ISSUE THREAD

**Issue by PetrusVermaak** [ghostery/ghostery-extension#2]
Firefox 58.0.2 (64-bit)
Windows 10 Pro, build 1709 16299.125

Tried to install ghostery-firefox-v8.1.0.xpi from github.

**Comment by creesch** [comment]
You do need to get it either from AMO if it is signed or use the firefox developer version which allows unsigned extensions to be installed.

**Comment by chrmod** [comment]
With Firefox Developer Edition or Nightly you need to enable unsigned addons with `xpinstall.signatures.required` preference set to `false` in `about:config` page. You can also use Mozilla's `web-ext` https://github.com/mozilla/web-ext project to uninstall it as a temporal addon.

@trickpattyFH20 maybe we should also add signed addon to github release download list?

**Comment by trickpattyFH20** [comment]
closing this issue for now. reach out on [gitter](https://gitter.im/ghostery/ghostery-extension) for any further questions on how to install a dev extension in FF
