### ISSUE TITLE
UI: Translation Adjustment Request

### ISSUE THREAD

**Issue by Dimi-GE** [ghostery/ghostery-extension#2083]
Description from a user:
"There is a little error in the translation of the Pause function in French: see the joined .JPG file. The word "gauche" should be "restantes". In English the word "left" here is the past participle of the verb "to leave", not the "left hand", as it is translated. There should be a space between the number and "min", for the number of minutes left on the pause."

Link to Transifex:
https://app.transifex.com/ghostery-inc/ghostery-dnr-extension/translate/#fr/develop-en-json?q=text%3Aleft

Screenshot:

![image](https://github.com/user-attachments/assets/cd201d44-e754-4441-a2c2-14fbacddc8ac)

**Comment by smalluban** [comment]
The phrase was updated by @mdsandu in Transifex. It will be pushed automatically with the next release.
