### ISSUE TITLE
Ghostery for Edge version 8.2.4 enhanced anti-tracking block open a ppt online file on Edge

### ISSUE THREAD

**Issue by JianunChen** [ghostery/ghostery-extension#209]
### Description

[Description of the bug or feature]
When the user enabled anti-tracking on edge, the user can't open a ppt file online with O365

### Expected Behavior 
Open a ppt online file successful

Here is request header:
POST https://ppc-powerpoint.officeapps.live.com/pods/PowerPoint.ashx?openEarly=true HTTP/1.1
Origin: https://ppc-powerpoint.officeapps.live.com
Referer: https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=Other&postMessageToken=967F989E-20B1-0000-B051-5C7603223485&fs=68990&hid=967F989E-20B1-0000-B051-5C7603223485&fileGetUrlBool=true
Accept: */*
Accept-Language: en-US,en;q=0.5
Content-Type: application/json; charset=utf-8
DevicePixelRatio: 1.25
Pid: _._._.84f98045-7a29-c39d-bcf9-61b4f3222887-.-.-.
PodSID: _._._.84f98045-7a29-c39d-bcf9-61b4f3222887-.-.-.
si: 
SlideHeight: 683
SlideWidth: 1575
X-OfficeVersion: 16.0.11010.37552
X-PageUrl: https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=Other&postMessageToken=967F989E-20B1-0000-B051-5C7603223485&fs=68990&hid=967F989E-20B1-0000-B051-5C7603223485&fileGetUrlBool=true
X-UserSessionId: d7d13dee-3591-4988-b096-cfec30a125f8
X-UserType: WOPI
X-WacCluster: PP3
X-WacNoAuth: 1
X-xhr: 1
Accept-Encoding: gzip, deflate, br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Host: ppc-powerpoint.officeapps.live.com
Content-Length: 56
Connection: Keep-Alive
Cache-Control: no-cache
Cookie: PP3-ARRAffinity=0899b86992e172fa8691f02b4ef0df1f186654f5622a62f597219c5e3c3bfb64; BIGipCookie=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000; DcLcid=ui=1033&data=1033; MSCC=63675171278

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 5439
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
P3P: CP="CAO DSP COR ADMa DEV CONi TELi CUR PSA PSD TAI IVDi OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR"
Set-Cookie: 
X-CorrelationId: 99d4f1f6-3c90-40d8-b7b8-c75d85286bab
X-UserSessionId: d7d13dee-3591-4988-b096-cfec30a125f8
Strict-Transport-Security: max-age=31536000
Timing-Allow-Origin: *
X-OfficeFE: BY3PEPF00000BB1
X-OfficeVersion: 16.0.11010.37552
X-OfficeCluster: PP3
Access-Control-Allow-Origin: https://ppc-powerpoint.officeapps.live.com
Access-Control-Expose-Headers: si, esid, X-EndSession, X-CorrelationID, X-OfficeFE, X-NewKey, Pid, SlideWidth, SlideHeight
Content-Disposition: attachment
X-PodInstance: by3pepf00000bbe
X-BootTelemetry: {"documentFlushTime":1539574635648,"downloadStartMs":1539574634742,"downloadEndMs":1539574635336,"downloadSize":68990,"incDownload":false,"bootStartMs":1539574634742,"bootEndMs":1539574635633,"officeAppEndpoint":"PP3","officeServerVersion":"16.0.11010.37552","downloadCorrelation":"b21b7a3d-e98c-4745-9c15-cf8fbf86d87b"}
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-GetCellServerTelemetry: {"OpenEarlyServerReceivedTime":"1539574635148","OpenEarlyServerFoundBaseDocTime":"1539574635633","OpenEarlyServerEndTime":"1539574635648"}
X-OFFICEFD: BY3PEPF00000BA2
X-MSEdge-Ref: Ref A: 283D650C1AED4DA69181FE2CFF0EB1ED Ref B: TYO01EDGE1110 Ref C: 2018-10-15T03:37:15Z
Date: Mon, 15 Oct 2018 03:37:14 GMT

[What you expected to happen]
It remove many request header then open ppt file failed on edge.

Here is the request header after enable anti-tracking on edge:
POST http://chaxu-ws.fareast.corp.microsoft.com/pods/PowerPoint.ashx?openEarly=true HTTP/1.1
Origin: http://chaxu-ws.fareast.corp.microsoft.com
Referer: http://chaxu-ws.fareast.corp.microsoft.com/pods/ppt.aspx?wdPodsUrl=http%3A%2F%2Fchaxu-ws.fareast.corp.microsoft.com%2Fpods%2F&wdPopsUrl=http%3A%2F%2Fchaxu-ws.fareast.corp.microsoft.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=test_thumbnail.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&wdOrigin=BlueChicken&postMessageToken=852f0480-eb85-4e31-9b6e-6effeb4cc9b6&hid=852f0480-eb85-4e31-9b6e-6effeb4cc9b6&fileGetUrlBool=true
Accept: */*
Accept-Language: en-US,en;q=0.5
Content-Type: application/json; charset=utf-8
DevicePixelRatio: 1.25
Pid: _._._.292b9fa5-3c56-dcbd-e98c-94786f4ae649-.-.-.
PodSID: _._._.292b9fa5-3c56-dcbd-e98c-94786f4ae649-.-.-.
si: 
SlideHeight: 608
SlideWidth: 1575
X-OfficeVersion: 16.0.10928.30000
X-PageUrl: http://chaxu-ws.fareast.corp.microsoft.com/pods/ppt.aspx?wdPodsUrl=http%3A%2F%2Fchaxu-ws.fareast.corp.microsoft.com%2Fpods%2F&wdPopsUrl=http%3A%2F%2Fchaxu-ws.fareast.corp.microsoft.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=test_thumbnail.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&wdOrigin=BlueChicken&postMessageToken=852f0480-eb85-4e31-9b6e-6effeb4cc9b6&hid=852f0480-eb85-4e31-9b6e-6effeb4cc9b6&fileGetUrlBool=true
X-UserSessionId: bd9abeb6-9319-4c12-8af6-208fe01c752a
X-UserType: WOPI
X-WacCluster: DC2
X-WacNoAuth: 1
X-xhr: 1
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Content-Length: 56
Host: chaxu-ws.fareast.corp.microsoft.com
Connection: Keep-Alive
Pragma: no-cache
Cookie: MicrosoftApplicationsTelemetryDeviceId=346f445d-871b-4263-96fb-0432b14975e3; MicrosoftApplicationsTelemetryFirstLaunchTime=2018-10-15T09:31:38.759Z; PptRibbon.Home=1536138%7C-1%7C141; DC2-ARRAffinity=c5b6ce9dcaf9bcd1491290817f1869fc69ec1bd81727ba0b3c138a4e769f49ea; DcLcid=ui=1033&data=1033; path=anonymous; ODSIAuth=GN=R3Vlc3Q=&SN=MjY2Nzc4MDU=&IT=NTI0ODQzNzk0NTI1MzQyNjM5NQ==&PU=MjY2Nzc4MDU=&SR=YW5vbnltb3Vz&TZ=MTExOQ==&SA=RmFsc2U=&LE=RmFsc2U=&AG=VHJ1ZQ==&RH=1i8Wh7wpT8P8Y__2zpBL3nm73mXbGkqCE_auN_ZiVvs=; wachost=chaxu-ws.fareast.corp.microsoft.com; BIGipCookie=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 7467
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Expires: -1
Server: Microsoft-IIS/10.0
P3P: CP="CAO DSP COR ADMa DEV CONi TELi CUR PSA PSD TAI IVDi OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR"
Set-Cookie: 
X-CorrelationId: 9bdece0d-672b-428b-b4f6-1f398dc34270
X-UserSessionId: bd9abeb6-9319-4c12-8af6-208fe01c752a
Strict-Transport-Security: max-age=31536000
Timing-Allow-Origin: *
X-OfficeFE: CHAXU-WS
X-OfficeVersion: 16.0.10928.30000
X-OfficeCluster: DC2
Access-Control-Allow-Origin: http://chaxu-ws.fareast.corp.microsoft.com
Access-Control-Expose-Headers: si, esid, X-EndSession, X-CorrelationID, X-OfficeFE, X-NewKey, Pid, SlideWidth, SlideHeight
X-PodInstance: CHAXU-WS
X-Content-Type-Options: nosniff
X-Download-Options: noopen
Content-Disposition: attachment
X-LastPodRCLocation: CHAXU-WS
X-BootTelemetry: {"documentFlushTime":1539595936009,"downloadStartMs":1539595927286,"downloadEndMs":1539595927372,"downloadSize":717086,"incDownload":true,"bootStartMs":1539595927286,"bootEndMs":1539595935981,"officeAppEndpoint":"DC2","officeServerVersion":"16.0.10928.30000"}
X-GetCellServerTelemetry: {"OpenEarlyServerReceivedTime":"1539595928101","OpenEarlyServerFoundBaseDocTime":"1539595935981","OpenEarlyServerEndTime":"1539595936009"}
X-OFFICEFD: CHAXU-WS
Date: Mon, 15 Oct 2018 09:32:15 GMT

### Actual Behavior 

[What actually happened]

### Steps to Reproduce

1. [First Step]
Open a ppt online file on edge with O365
2. [Second Step]
Show error dialog
3. [and so on...]

### Versions

+ Browser:
Ghostery for Edge version 8.2.4
+ OS: 
+ Node:
+ NPM:

**Comment by JianunChen** [comment]
Thanks for your quick response, could you help to share the request header of open early, X-UserSessionId and page url to me?


For clarify:

My ghostery version is: Ghostery for Edge version 8.2.4

[cid:6421e48f-3f8f-4d69-99a2-51da955d1259]


Below is request header of open early with Anti-tracking enabled and disabled:


1. With anti-tracking, it remove many header

1.1 Here is the request url:

https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=DocLib&postMessageToken=79C3999E-D083-0000-B067-D80337D1C32A&fs=69212&hid=79C3999E-D083-0000-B067-D80337D1C32A&fileGetUrlBool=true


1.2 Screenshot of open ppt file on edge

[cid:41ca1741-3daa-494f-b07e-495ca8074bf1]


1.3 Here is the request header of open early, attathed the fiddler trace, it removed all the request header after Referer.

[cid:3d516ef5-3100-4f59-90c0-8102177d725e]

2. without anti-tracking:
2.1 request url
https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=Other&postMessageToken=C1C3999E-10C4-0000-B067-DE920F2379E9&fs=69212&hid=C1C3999E-10C4-0000-B067-DE920F2379E9&fileGetUrlBool=true

2.2 Screenshot of open ppt file on edge
[cid:dd393c4e-db44-4b57-9eb8-520c4bddf06f]

2.3 Here is the request header of open early, attathed the fiddler trace.
[cid:78ba3dc6-d4ee-4db4-aa39-279d9f5ba8a8]

Thanks,
Jiankun
________________________________

**Comment by JianunChen** [comment]
Reply again with the screenshot and attachment.

Thanks for your quick response, could you help to share the request header of open early, X-UserSessionId and page url to me?

For clarify:
My ghostery version is: Ghostery for Edge version 8.2.4
![pastedimage](https://user-images.githubusercontent.com/44161715/47194252-36501b80-d389-11e8-8a66-bf7705ed7097.png)

Below is request header of open early with Anti-tracking enabled and disabled:

1. With anti-tracking, it remove many header
1.1 Here is the request url:
https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=DocLib&postMessageToken=79C3999E-D083-0000-B067-D80337D1C32A&fs=69212&hid=79C3999E-D083-0000-B067-D80337D1C32A&fileGetUrlBool=true

1.2 Screenshot of open ppt file on edge

![pastedimage](https://user-images.githubusercontent.com/44161715/47194269-49fb8200-d389-11e8-83fd-008741c2d5be.png)

1.3 Here is the request header of open early, attached the fiddler trace, it removed all the request header after Referer.

![pastedimage](https://user-images.githubusercontent.com/44161715/47194285-541d8080-d389-11e8-81ae-1f8b0acf1b48.png)

2. without anti-tracking:
2.1 request url
https://ppc-powerpoint.officeapps.live.com/pods/ppt.aspx?wdPodsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2Fpods%2F&wdPopsUrl=https%3A%2F%2Fppc-powerpoint.officeapps.live.com%2F&fastBoot=true&sw=1260&sh=487&thPanel=540&ro=false&NoAuth=1&fileName=Presentation111.pptx&wdoverrides=devicepixelratio:1.25,RenderGifSlideShow:true&ui=en-US&rs=en-US&mscc=1&wdFR=1&wdOrigin=Other&postMessageToken=C1C3999E-10C4-0000-B067-DE920F2379E9&fs=69212&hid=C1C3999E-10C4-0000-B067-DE920F2379E9&fileGetUrlBool=true

2.2 Screenshot of open ppt file on edge

![pastedimage](https://user-images.githubusercontent.com/44161715/47194292-597acb00-d389-11e8-9e2f-d21c2b77d090.png)

2.3 Here is the request header of open early

![pastedimage](https://user-images.githubusercontent.com/44161715/47194298-5f70ac00-d389-11e8-882c-232712e8bf7f.png)

Attachment: Request header:
[RequestHeaderWithoutAntiTracking.txt](https://github.com/ghostery/ghostery-extension/files/2494282/RequestHeaderWithoutAntiTracking.txt)

[RequestHeaderWithAntiTracking.txt](https://github.com/ghostery/ghostery-extension/files/2494283/RequestHeaderWithAntiTracking.txt)

Thanks,
Jiankun

**Comment by JianunChen** [comment]
@Aziz-Ghostery @trickpattyFH20 

Do you have any update? please let me know if you need more information. thanks

**Comment by christophertino** [comment]
@JianunChen could you update to Ghostery 8.2.5 and let us know if this is still happening? We have not been able to reproduce the issue.

**Comment by CXuesong** [comment]
Actually the problem exists when I'm on Ghostery 8.3.1. It scrubs most of the headers of the following two requests:
```
https://*-powerpoint.officeapps.live.com/pods/PowerPoint.ashx?openEarly=true
https://*-powerpoint.officeapps.live.com/pods/PowerPoint.ashx?dSlide=true
```
And this causes PowerPoint Online being unable to start. You may see this in Fiddler when you open a presentation in PowerPoint Online.

[Request headers - Original.txt](https://github.com/ghostery/ghostery-extension/files/2995965/Request.headers.-.Original.txt)
[Request headers - Ghostery.txt](https://github.com/ghostery/ghostery-extension/files/2995966/Request.headers.-.Ghostery.txt)

I'm not sure why but somehow Ghostery thinks these two requests are trackers. Please take a look at it. Thanks!

**Comment by smalluban** [comment]
Edge platform migrated to v10. Feel free to re-open if the issue is still valid.
