### ISSUE TITLE
Bug: Uncaught TypeError: Cannot read property 'href' of null  at u (content_script_bundle.js:1)

### ISSUE THREAD

**Issue by vHeemstra** [ghostery/ghostery-extension#214]
### Description of bug

When using JSFiddle, my browser's console shows uncaught TypeErrors from the Ghostery extension script whenever I click after one of these characters `(`,`)`,`[`,`]`,`}`,`}` (when it's the last character on the line) in the editor field.

_NB: I've seen it in other situations/on other websites happening as well, but this is just an example._

### Expected Behavior 

Nothing / No errors in the console

### Actual Behavior 

The console shows this error: `Uncaught TypeError: Cannot read property 'href' of null
 at u (content_script_bundle.js:1)`. It occurs at line 1, character 26556 (`e.target.parentNode.href`).

### Steps to Reproduce

1. Go to [this small JSFiddle example](http://jsfiddle.net/mnrj4qyo/)
2. Open your browser's console
3. Click at the line endings after the characters

### Versions

+ Browser: Chrome version 69.0.3497.100 (64bits)
+ OS: Windows 10 Pro
+ Node: version 6.9.1
+ NPM: version 3.10.9

**Comment by philipp-classen** [comment]
Thank you for the bug report, I get the same error.

This is the code that throws:
https://github.com/cliqz-oss/browser-core/blob/master/modules/core/sources/content.es#L224

**Comment by philipp-classen** [comment]
Should be fixed in the next release.

**Comment by jordanranson** [comment]
When will that be? This is still an issue.

**Comment by christophertino** [comment]
@jordanranson We released v8.2.5 today which should fix the issue.  Please update and let us know.

**Comment by jordanranson** [comment]
@christophertino Seems to be good now! Thanks for the hard work guys.
