### ISSUE TITLE
Can't open links since 8.2.5 on Chrome: "pop-up blocked"

### ISSUE THREAD

**Issue by TiTi** [ghostery/ghostery-extension#254]
### Description

Last update today or yesterday broke a lot of links in my Chrome, either left or middle clic.
A message "pop-up blocked" appears in the url toolbar.

I have no other choice but to disable Ghostery for now 😢 

It affects a lots of websites. Sometimes the link is working somehow.
Steps to reproduce I'm submitting always fail.

It works fine (as usual) when deactivating Ghostery.

Important note:
I'm using Chrome beta (but never had issue with ghostery before)

[pop-ups are blocked by default in Chrome]

### Expected Behavior 

Url is opened, either in current tab (left click) or another (middle click)

### Actual Behavior 

A message "pop-up blocked" appears in the url toolbar.

### Steps to Reproduce

1. Go to a website like https://www.qwant.com/?q=ghostery&t=web 
2. Left click a search result
(it works fine when deactivating Ghostery)

Other sample: 
1. Go to imgur.com
2. Click any image/gif with left click: it works
3. Go back to home page
4. Click any image/gif with middle click: it doesn't work
(it works fine when deactivating Ghostery)

### Versions

+ Browser: Chrome Version 71.0.3578.62 (Official Build) beta
+ OS: Windows 10

**Comment by meredy** [comment]
I experience the same issue, but seemingly only since 8.2.6 was released

**Comment by joeczucha** [comment]
I'm experiencing the same issue, but with a strange caveat:

I have an iMac in my office and a Macbook Pro at home. I'm running Chrome Version 71.0.3578.80 on both and have recently restarted both browsers/machines. To test, I'm running in "incognito mode" with Ghostery (version 8.2.6) as the only active extension on both.

On the iMac - if I visit www.bbc.co.uk, hold CMD and click a link, I get "Pop up blocked". 

On the MBP - if I do the same, the link opens in a new tab without issue.

Disabling Ghostery on the iMac causes it to function in the same way as the MBP (i.e. the new tab opens).

I thought that I may have just previously white-listed the site but the same thing happens on Wikipedia, Amazon etc. so I don't think that's the case.

Sorry that I don't have more insight but I figured that I'd let you know, just in case I can provide some logs or anything to help work out what's different between the two machines.

**Comment by TiTi** [comment]
I don't have the issue anymore with Chrome Version 72.0.3626.17 (Official Build) beta (64-bit)
Ghostery in version 8.2.6

I suppose it was a Chrome issue?

**Comment by doktorJung** [comment]
I'm just encountering this issue with Version 71.0.3578.98 (Official Build) (64-bit), and I see no updates available.  I hope I can get 72 soon!

**Comment by DanielRuf** [comment]
> I'm just encountering this issue with Version 71.0.3578.98 (Official Build) (64-bit), and I see no updates available. I hope I can get 72 soon!

You have to get Chrome beta or test the Canary version.

https://www.google.com/intl/de_ALL/chrome/beta/
https://www.google.com/intl/de_ALL/chrome/canary/

**Comment by doktorJung** [comment]
Thanks, I might give it a try!

**Comment by Sn-a-ke** [comment]
ghostery - 8.2.6
Browser: chrome - 71.0.3578.98 (Official Build) (64-bit)
OS: win7(64)

-same behavior

**Comment by aloker** [comment]
Same problem here. I'd appreciate a solution that does not require me to wait for Chrome 72 (29/1/19) or install a beta version.

**Comment by jingtra** [comment]
Same problem here.

**Comment by TiTi** [comment]
https://www.androidpolice.com/2019/01/10/chromes-pop-up-blocker-is-going-haywire-if-youre-using-certain-extensions/

**Comment by doktorJung** [comment]
Here's the Chromium ticket I opened a while back, it's being investigated as mentioned in the article above: https://bugs.chromium.org/p/chromium/issues/detail?id=918268

(It was sorta dismissed as a Ghostery issue at first, but there's movement on it now!)

**Comment by doktorJung** [comment]
They're rolled back an experiment, so restarting Chrome should resolve the issue once it propagates.

https://bugs.chromium.org/p/chromium/issues/detail?id=918268#c36
