### ISSUE TITLE
webRequest header access changes in Chrome 72

### ISSUE THREAD

**Issue by clarkduvall** [ghostery/ghostery-extension#264]
It looks like Ghostery is accessing or modifying headers that will not be available by default in Chrome 72 (currently on the dev channel). These include:

Request headers:
- Accept-Language
- Accept-Encoding
- Cookie
- Referer

Response headers:
- Set-Cookie

To access these headers you will need to add 'extraHeaders' in the extraInfoSpec of the relevant webRequest listeners.

See the post on the chromium-extensions Google Group for more info: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/vYIaeezZwfQ

**Comment by christophertino** [comment]
@clarkduvall thanks for the heads up.  It looks like Chrome 72 is due out on Jan 29th so we'll need to get this resolved before then.
