### ISSUE TITLE
Ghostery blocking input-file select

### ISSUE THREAD

**Issue by PINHOf** [ghostery/ghostery-extension#314]
### Description

Ghostery is blocking the input-file HTML preventing the user from selecting a file.
By desactivating completly the extension, it works.

You can see the bug here: https://streamable.com/rqxyz

### Versions

+ Browser: Version 71.0.3578.98 (Official Build) (64-bit)
+ OS: Windows 10 64 bits

**Comment by ChakraaThePanda** [comment]
I will have to disable the addon until it is fixed as it's doing this issue and https://github.com/ghostery/ghostery-extension/issues/313 since the last update, and I can't work without them.

**Comment by wlycdgrfromflatiron** [comment]
Thank you very much for taking the time to report this issue. We are able to reproduce and are looking into it.

**Comment by philipp-classen** [comment]
Some update. We could narrow it down to sending a message from the content script to the background and back again. @sammacbeth created a minimal extension to reproduce:

https://gist.github.com/sammacbeth/96b938d94d49451020fdfba7e80c57d8

If you want to support, please let us know if you can reproduce with it as well.

It appears that Ghostery is not the only extension affected by the problem. Further information can be found in the discussions on the Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=918268

**Comment by wlycdgrfromflatiron** [comment]
I am able to reproduce using Sam's minimal extension after changing the type attribute of the input element to "file" (when it's "upload", clicking the button does not open an input file select dialog regardless of whether extension is present).

**Comment by philipp-classen** [comment]
It is interesting that not all systems are affected. On two Linux machines that I could test so far, everything is alright (Chrome 71.0.3578.98, one running Ubuntu 18.04, the other Arch Linux). I also tried Chromium in different versions, but could not reproduce any of the issues so far.

We had no recent Ghostery releases (8.2.6 was released on Nov 30th). I also do not see a Chrome release (last stable release is from Dec 14th). Some reports say that they were hit by the problem after upgrading to Chrome 71.

Firefox is also not affected.

**Comment by xhc1** [comment]
checked Chrome + ghostery this url:

https://ulozto.net/sem

result - by click "Select files" no popup appears

chrome + disabled ghostery (totally turned off, disabled in extensions)
result - working

firefox and chromium works with ghostery enabled

**Comment by xhc1** [comment]
kindly weird because this issue I found today morning, I am pretty sure few days it worked (on same machine without update-changes)

**Comment by philipp-classen** [comment]
There were updates on the Chrome issue (https://bugs.chromium.org/p/chromium/issues/detail?id=918268 ).

It seems the regression got introduced in Chrome by a recent experiment. That would explain why some extensions (not only Ghostery) suddenly started breaking, and why not all users were affected.

Let's hope it gets fixed soon. At this point, I think it is best for us to wait. (Theoretically, we might be able to workaround it by disabling all responses from the background script, but that would be quite a hack. I would not recommend it, as it could have unexpected side-effects.)

**Comment by philipp-classen** [comment]
Good news. The Chrome team will roll back their experiment (https://bugs.chromium.org/p/chromium/issues/detail?id=918268).

That should fix it.

**Comment by philipp-classen** [comment]
For all user that are affected. The Chrome fix will be rolled out in the next hours. You will have to manually restart the browser. This is the official announcement:
https://productforums.google.com/forum/#!topic/chrome/fOXX61ZDP4w

@sammacbeth Kudos to Sam for narrowing it down with that minimal example! That bug affected quite a lot of people, not only Ghostery user. With that example, the Chrome team was able to quickly reproduce it on their end and track it down.

**Comment by xhc1** [comment]
confirmed on linux, working again ...... no manually update-changes, just restarted browser, little bit ghostlike - this chrome's experiments cant be under user control, horrors ...
