### ISSUE TITLE
Feature Request: Hide PurpleBox (by default)

### ISSUE THREAD

**Issue by DaveJarvis** [ghostery/ghostery-extension#340]
### Description

Ghostery shows a purple box when browsing.

### Expected Behavior 

Ghostery does not show a purple box when browsing.

### Actual Behavior 

Ghostery shows a purple box when browsing.

### Steps to Reproduce

1. Visit a web site.

### Versions

+ Browser: Firefox
+ OS: Arch Linux

### Additional Details

Please provide functionality to disable the purple box as it is obtrusive (covers web page content).

![purplebox](https://user-images.githubusercontent.com/2131950/52888418-6f7a7b80-3130-11e9-8662-ee77d179a5c4.png)

**Comment by DaveJarvis** [comment]
On a technical note, if you ever decide to change the colour of the purple box, then its name is rendered meaningless. You may wish to rename it to something like "TrackerBox" or such.

**Comment by christophertino** [comment]
You should be able to disable the purple box via the settings menu.  Ghostery menu (top right) > Settings > Purple Box > Show the purple box in the corner of my browser. 

Fun Ghostery Fact:  Years ago, the original Ghostery team worked out of a very small room that had purple walls, which they called "The Purple Box".  We've kept that name in modern iterations of Ghostery as a wink and nod to the old crew.

**Comment by DaveJarvis** [comment]
> Fun Ghostery Fact: Years ago, the original Ghostery team worked out of a very small room that had purple walls, which they called "The Purple Box". We've kept that name in modern iterations of Ghostery as a wink and nod to the old crew.

That would make a nice addition to the header comment of the class file.

> Ghostery menu (top right) > Settings > Purple Box > Show the purple box in the corner of my browser.

Is this not available through the **Add-ons Manager**? That is:

1. Visit **about:addons**
1. Click **Preferences** for Ghostery
1. ???

Anyway, the default behaviour should mirror AdBlock Plus and uBlock Origin: don't overlay content (i.e., a purple box) on any web page **by default**. I could not find the setting using Ghostery 8 on Firefox and have uninstalled the add-on.
