### ISSUE TITLE
Wish: Mention ghostery as FOSS software

### ISSUE THREAD

**Issue by maverick74** [ghostery/ghostery-extension#341]
This is not a bug or a feature request (so if you want to close it I won't mind :)

I would just like to mention I would very much like to see ghostery more "advertised" as a FOSS project. Maybe with a link to github as well.

I say this because, beside the blog post of opensourcing ghostery, I could not find anything else about it and I really believe it's worth mentioning that it is proudly open-source!

**Comment by maverick74** [comment]
Since this is now closed, I'll shoot an off-topic question I could not find the answer to:

Is the new cliqz search engine also open-source?

**Comment by remusao** [comment]
> Since this is now closed, I'll shoot an off-topic question I could not find the answer to:
> 
> Is the new cliqz search engine also open-source?

Hey @maverick74,

By "new cliqz search engine", are you referring to https://beta.cliqz.com/?

**Comment by maverick74** [comment]
@remusao yes, I'm referring to that one.

I'm sorry for the (complete) off-topic, but I could not found info about it anywhere

**Comment by remusao** [comment]
> @remusao yes, I'm referring to that one.
> 
> I'm sorry for the (complete) off-topic, but I could not found info about it anywhere

No worries, I simply wanted to make sure I understood your question correctly before attempting an answer. As you know, at Cliqz and Ghostery we believe privacy is a fundamental human right and that's at the core of any technology we build. We have published multiple papers on privacy, given many talks and disclosed responsibly numerous privacy and security vulnerabilities in all major browsers[1]. The Cliqz browser, where quick search lives (a.k.a. what we call [the dropdown](https://0x65.dev/blog/2019-12-11/the-pivot-that-excited-mozilla-and-google.html)), is completely open source for desktop[2], iOS[3] and Android[4]. That is the code that runs on your machine and you can inspect it.

In the backend, we have open sourced many things we have built see [5], [6], but the search ranking itself is not open source. We have ambitious plans around the area of ranking transparency, but it's too soon to share anything. Meanwhile, feel free to read more about how we build things on our tech blog[7].

[1] [https://www.0x65.dev/pages/dissemination-cliqz.html](https://www.0x65.dev/pages/dissemination-cliqz.html)
[2] [https://github.com/cliqz-oss/browser-f](https://github.com/cliqz-oss/browser-f) and [https://github.com/cliqz-oss/browser-core](https://github.com/cliqz-oss/browser-core)
[3] [https://github.com/cliqz/user-agent-ios](https://github.com/cliqz/user-agent-ios)
[4] [https://github.com/cliqz/daisy](https://github.com/cliqz/daisy)
[5] [https://github.com/cliqz-oss/](https://github.com/cliqz-oss/)
[6] [https://github.com/cliqz/](https://github.com/cliqz/)
[7] [https://www.0x65.dev/](https://www.0x65.dev/)

**Comment by maverick74** [comment]
Your answer brings good news but, as an open-source guy, I would love if it was 100% open source.

I believe that in the public eye open-source is what equals private. And beside searx (which is a meta search engine) and gigablast (which is a search engine about which I don't dare to talk about) we have nothing really good, independent, trusty and open-source ( not to mention based on EU ground)

I understand that being open is bad for business ( or so say DuckDuckGo ), but it would also brings a key feature that others don't have and that pleases public eye.

I'll keep an eye on news about it :)

**Comment by remusao** [comment]
@maverick74 When it comes to search engines, I believe it's important to think about what open-source would mean. Are we talking about opening the data (the index), or the code populating the index, or the core searching logic, or the results ranking algorithms, or the infrastructure running the search, or... There are many things which make a search engine. In the end, I think it's important the understand what open-sourcing would even mean, and what benefits it would bring; there are potentially multiple valid answers to this question.

We [wrote at length](https://0x65.dev/blog/2019-12-01/the-world-needs-cliqz-the-world-needs-more-search-engines.html) about the issues with Google being an information monopoly, which I think is relevant to your question. And in the end the biggest issues are not about the search being open-source or not; we're talking about so much data that literally no one would be able to do anything with it (if it were to be opened).

Rather, we are now exploring ways to bring more transparency and diversity to the ranking logic, which I think is one of the most promising ways to "fix" the current search situation. In the meanwhile we will continue to open-source more and more of the building blocks which we develop to build our search.

**Comment by maverick74** [comment]
I don't think the index would be important to be open.

A small comparison: I would value and I think the important is having "the machine" open, the product is not that important. The "machine" could always produce more product.
Users knowing they can look into the machine freely and check for privacy issues is a way they can get confidence and trust in the machine (even if 99,9% of them would never do it).

So, I think, if the machine is not "evil" (and there's no other external influences), then it's product can't be evil either.

>In the meanwhile we will continue to open-source more and more of the building blocks which we develop to build our search.

This is very good news! Thanks
