### ISSUE TITLE
Question: How to suppress first run page

### ISSUE THREAD

**Issue by pmurley** [ghostery/ghostery-extension#342]
I'm trying to do some research which involves stateless crawling with Chrome on many distributed machines, and I'd like to have Ghostery running in each browser. I am having an issue because the first-run page always pops up. Is there a simple way to disable first run/update pages programmatically in the extension code somewhere?

Thanks!

**Comment by christophertino** [comment]
You can disable that popup in background.js 

https://github.com/ghostery/ghostery-extension/blob/fc0827ad162a59f8a57a0058b09dc6daeebc3050/src/background.js#L1750

You would then have to build the extension and load it in Chrome with Developer Mode enabled (chrome://extensions/)

**Comment by pmurley** [comment]
Awesome, thanks so much!
