### ISSUE TITLE
Browser shuts down while Ghostery is enabled.

### ISSUE THREAD

**Issue by SabinStargem** [ghostery/ghostery-extension#356]
Firefox Quantum started to have issues today, with some tabs not responding to search inputs.  I shut down my browser, and then tried starting it up.  Every time, the browser would open briefly before shutting down.  After several tries, I entered the browser's safemode and began switching off my extensions to find the cause.

Ghostery was the cause of my troubles.  After successfully opening my browser without Ghostery enabled, I tried to turn on Ghostery - which immediately closed it.

Until the problem gets fixed, I am going to keep Ghostery disabled.  Is there a log file?  My report is too vague to be very useful.

**Comment by christophertino** [comment]
We've been getting similar reports since this morning.  It seems to be related to the FF 65.0.2 release on Windows. 

You can try debugging Ghostery in FF at about:debugging if you can get it to open up before it crashes.

**Comment by christophertino** [comment]
Could you try to uninstall and reinstall Ghostery via about:addons?  This looks to have worked for another user.

**Comment by slosha69** [comment]
Firefox crashes pretty quickly when opening it, so what I did is just delete the ghostery file from with the extensions folder of my profile folder. Everything is running fine now, without ghostery of course.

**Comment by christophertino** [comment]
Here's the Bugzilla ticket we're working from:

https://bugzilla.mozilla.org/show_bug.cgi?id=1535589

If anyone is about to generate a crash report for this issue in `about:crashes` please send us the crash ID or add to the bugzilla ticket.

**Comment by SabinStargem** [comment]
Reinstalling definitely doesn't work.   About: crashes doesn't list any recent crashes.    The browser closes too quickly to do any debugging.

**Comment by christophertino** [comment]
Are you running Avast anti-virus by any chance?

**Comment by SabinStargem** [comment]
Yup.

**Comment by christophertino** [comment]
Does temporarily disabling Avast from the system tray allow FF to boot up normally with Ghostery? The Mozilla devs think there may be a correlation.   

Another user reported that the issue went away after updating to FF 66.

**Comment by SabinStargem** [comment]
Huh.  Disabling Avast did the trick, and I can now start up with Ghostery enabled.

Good.  :)

**Comment by christophertino** [comment]
This issue seems to have been resolved with a definition update from Avast/AVG. We're still not entirely sure what happened.
