### ISSUE TITLE
Uncaught TypeError: c.querySelectorAll on every page

### ISSUE THREAD

**Issue by AaronLavers** [ghostery/ghostery-extension#406]
### Description

When Ghostery extension is enabled in Chrome 75.0.3770.100, every page returns a massive string of identical errors:

` content_script_bundle.js:16 Uncaught TypeError: c.querySelectorAll is not a function at MutationObserver.<anonymous> (content_script_bundle.js:16)
`

The script it's experiencing the error in appears to be related to Cliqz - which appears to be a browser that I don't have on this machine.

### Expected Behavior 

I'd expect these errors to not be present, before today they did not appear.

### Actual Behavior 

On some pages where dynamic content loads in lists, this error can duplicate itself thousands of times.

### Steps to Reproduce

1. Go to any website in Chrome with the Ghostery extension running
2. Open console
3. The error will be present

4. When the plugin is paused or disabled and the page is reloaded, these errors are not present

### Versions

+ Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit)
+ OS: Windows 10 Creator

**Comment by VdeJong** [comment]
I encounter the same issue on macOS Mojave and the same chrome version.

**Comment by remusao** [comment]
Hi @AaronLavers @VdeJong, thanks for your report. We were able to identify and fix this issue and we will ship it with an update ASAP.

**Comment by MarkoSulamagi** [comment]
Hi @remusao. Any thoughts on when the fix will be shipped? :)

**Comment by remusao** [comment]
@MarkoSulamagi, the fix was tested and released upstream in `browser-core` and now needs to be shipped via a new Ghostery extension release. @christophertino will know better about the precise release schedule.

**Comment by kaiwa** [comment]
I'm going to remove ghostery for now till the fix is released. I'm a web dev and can't work if errors are popping up in the console constantly.

**Comment by Jormosaurusrex** [comment]
Please, please fix this.  It makes my work almost impossible.

**Comment by simoozzay** [comment]
Any update on the update @christophertino?
Have to agree with @kaiwa and sadly have to deactivate ghostery until the fix is released.

**Comment by christophertino** [comment]
@simoozzay We are scrambling to squeeze a few more bugs into this release and then hopefully get everything into testing tomorrow.  Apologies for the delay.

**Comment by AaronLavers** [comment]
Appreciate it guys :)

**Comment by simoozzay** [comment]
Thx @christophertino for the info, appreciate it! Would like to use ghostery again soon ;) 
Aaand btw keep up your great work, you're doing great with ghostery. Love this tool!

**Comment by WesselKroos** [comment]
Btw, for the webdevelopers using chrome. You can filter out the console errors in the meantime:
![image](https://user-images.githubusercontent.com/31220528/61483567-5c006480-a99d-11e9-9408-da9b3701f977.png)

**Comment by jaewonYoon** [comment]
For the frontend developer who are suffering not visible your elements,
I had same issues c.querySelectorAll is not function.....
however In my case, problem was my whole <div> elements has class start with 'ad'  display none. 
after I change class name start with keywords 'ad' to something like 'co' or 'biz'  
problem fixed .  

I know it's just tricky solution, but hope this might help some developers

**Comment by christophertino** [comment]
Ghostery 8.4.1 was approved and published to the Chrome store today.  Please let us know if this issue is still occurring.  Thanks!

**Comment by AaronLavers** [comment]
Appears to be resolved on Chrome 76.0.3809.100 (Official Build) (Win 64-bit)
