### ISSUE TITLE
Ghostery breaks Outlook Web Access

### ISSUE THREAD

**Issue by requiemmg** [ghostery/ghostery-extension#412]
### Description

My work Outlook Web Access Account suddenly (around 2 or 3 months ago) started to throw generic errors. ("Unexpected error sending mail" or "Error 413 network connection not found") All email I sent to external adresses were rejected as Spam by an external mail-relay. This didd not happen when using Outlook (Full Client), another browser or when disabling Ghostery.

### Expected Behavior 

Normal usageof OWA.
Source code of email sent without ghostery looks like this:
[![Bild image004r4jy7.png auf abload.de](https://abload.de/img/image004r4jy7.png)](https://abload.de/image.php?img=image004r4jy7.png)

### Actual Behavior 

OWA functionality impaired, Mails being sent rejected as Spam. Source code of sent mails modified:
[![Bild image006tzjzi.png auf abload.de](https://abload.de/img/image006tzjzi.png)](https://abload.de/image.php?img=image006tzjzi.png)

There has been a related but not quite similar (closed) issue last year:
https://github.com/ghostery/ghostery-extension/issues/132

### Steps to Reproduce

Not sure if happens with all OWA accounts. In my case:
Login to OWA, compose and send a mail.

### Versions

+ Browser: Firefox 68.0 (happened with previous Versions)
+ OS: Windows 10 x64 v 1903
+ Node: ?
+ NPM: ?

**Comment by christophertino** [comment]
This is related to #381 which was fixed in v8.4.1 for Firefox. It's currently pending review from Mozilla and should be available within the next few days.

**Comment by christophertino** [comment]
Fixed in v8.4.2
