### ISSUE TITLE
Block Google Tracking

### ISSUE THREAD

**Issue by gurgun-dayioglu** [ghostery/ghostery-extension#413]
### Description
Description: After clicking on any search result displayed by Google there seems to be a GET request to Google before it starts loading the webpage.

### Actual Behavior 

[When clicked on a link such as: https://tr-tr.facebook.com/ it first makes a GET request to https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjb9Py0xKzjAhWMFMAKHe6iAMYQFjAAegQIBhAC&url=https%3A%2F%2Ftr-tr.facebook.com%2F&usg=AOvVaw1xWwTSqg3_5X67lB-gwH6- which is considered as a tracking request made to Google explained further by EFF [here](https://www.eff.org/deeplinks/2018/10/privacy-badger-now-fights-more-sneaky-google-tracking)

**Comment by gurgun-dayioglu** [comment]
Closing since it doesn't seem like the type of protection Ghostery would offer

**Comment by christophertino** [comment]
Correct, our focus is primarily on third-party tracking. We would only intercept these link shims (or ping trackers) if they were being sent off to a third party.
