### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by michaelnordmeyer** [ghostery/ghostery-extension#42]
This code doesn’t have Safari support. Old ghostery versions up to 5.4.11 supported Safari.

Do you have an pointers on how to re-introduce Safari support? Are you interested to get Safari support into this code base at all?

**Comment by michaelnordmeyer** [comment]
There was a closed-source iOS Safari content blocker called Peace created by Marco Arment. It used Ghostery as a backend.

After two successful days on the app store, Marco removed it from the app store with consent from Ghostery (see: https://marco.org/2015/09/18/just-doesnt-feel-good and https://marco.org/2015/09/16/peace-content-blocker). After some time he gave the source code to Ghostery, which he mentioned on some podcast. But they never released the source.

I think Safari content blockers on iOS and macOS are about the same. So if you have access to Peace’s source code with a proper license, you could use it for a start.

**Comment by christophertino** [comment]
I remember the Peace app, that was a crazy couple of days.  To your point, we are currently in the process of building a new Ghostery iOS app using content blockers.  It's based on the Firefox code base.  You can see that code [here](https://github.com/cliqz-oss/cliqz-ios). 

The tentative release date for this and a similar Android app is early June. So far we've had success getting the Ghostery tracker list to display in iOS using content blockers.

**Comment by dwaite** [comment]
@christophertino Is that the correct codebase? I didn't see mention of `SFContentBlockerManager` in the code; instead it looks like it is doing script injection by wrapping WebKit.

**Comment by christophertino** [comment]
@dwaite yes, that is the working repository for the new Ghostery iOS browser.  Our devs came up with a way to use the Content Blocker but still allow users to see the Ghostery tracker list, which is of course our major feature.  If you'd like more info feel free to open an issue on that repo and they'll be happy to help.  We're also looking for Test Flight testers if you're interested. 

cc: @naira-cliqz

**Comment by naira-cliqz** [comment]
@dwaite SFContentBlockerManager is for MacOS, for iOS content blocker works based on WKContentRuleList, which we use. Added UserScripts are for another reason, not for contentBlocking. New Safari extension with SFContentBlockerManager is coming soon :)

**Comment by christophertino** [comment]
The Ghostery Lite app extension source code for Safari is available here: 

[https://github.com/ghostery/GhosterySafari](https://github.com/ghostery/GhosterySafari)
