### ISSUE TITLE
Ghostery Firefox crept up to 900MB RAM usage

### ISSUE THREAD

**Issue by artscoop** [ghostery/ghostery-extension#434]
### Description

The Ghostery plugin for Firefox ate up to a stable 900MB of RAM. Happened while using only one open tab (Tweetdeck) in Firefox 69 Linux.

### Expected Behavior 

The Ghostery plugin should not leak, duplicate, or indefinitely accumulate data on dynamic pages.

### Actual Behavior 

The Ghostery plugin took 900+MB of RAM. Deactivating the plugin made the WebExtensions process go back to 150MB.

### Steps to Reproduce

1. Open the TweetDeck website with your Twitter account.
2. Scroll, play content, really play with the website for some time, maybe 15 minutes or more.
3. Watch the WebExtensions process RAM usage
4. Deactivate Ghostery
5. Wait 15 seconds
6. Watch the WebExtensions process RAM usage

### Versions

+ Browser: Firefox 69.0.1 Linux x86-64
+ OS: Manjaro (Arch) Linux
+ Node: 11.15.0 (?)
+ NPM: 6.10.1 (?)

**Comment by christophertino** [comment]
This may be related to a Firefox OOM bug originally reported on Windows:

https://bugzilla.mozilla.org/show_bug.cgi?id=1519123

We haven't had any luck reproducing it, but perhaps looking at Linux may provide some insight. Thanks for reporting.

**Comment by christophertino** [comment]
Could you please try updating to Ghostery 8.4.2 and let us know if you are still seeing this memory issue?

**Comment by artscoop** [comment]
Hello, after 2 days trying Ghostery on two computers (Firefox 70 Linux), I couldn't reach 20MB RAM usage after playing with a few pages. Better, the average memory usage for the extension seems to wander around 13MB (10.7 after a garbage collection).
That's a really great job you all did on this 👌

**Comment by christophertino** [comment]
That's great to hear. Thanks again for reporting.  Please let us know if you come across any other issues.
