### ISSUE TITLE
www.rlslog.net popup windows trackers not blocked by Ghostery

### ISSUE THREAD

**Issue by qarqun** [ghostery/ghostery-extension#448]
### Description

popup ad windows still appear even though ghostery extension have set to block all trackers.

### Expected Behavior 

[What you expected to happen]

suppose popup windows blocked. looks like some trackers missed by ghostery.

[What actually happened]

### Steps to Reproduce

1. Open this URL: http://www.rlslog.net/
2. Click in the search text field.
3. Ads popup windows will appear.

### Versions

+ Browser: Firefox 69.0
+ OS: Windows 10 Pro Version 1903
+ Node: 64 bit
+ NPM:
Ghostery for Firefox version 8.4.2

**Comment by qarqun** [comment]
Please block this:

`http://35.224.227.218/*`
`http://35.224.227.218/NjQxNDM1OTEwNjA5LzY0MTQzNzM1NzI4Ni8wZW9jenFvdm5k`
`http://35.224.227.218/MjM3NzY2ODg5MTA3LzIzNzc2ODMzNTc4NC8wbTlpa3Jxbndp`

`http://35.224.227.218/script/s2iurl.php?stamat=m%7C%2C%2CQ2ESIhZnoGU3BZ9GH0dEdHP3xP.afc%2CnYDQXbyFsILaWL_zscGxJoaxd6Y6fMqZ0RcRt1MjnqhmqHrOzBqfYzxdbeNS0HbMcDa1zK9KKNEejV9rzz0yuq8Rj5BMk0DAmWsn7fttSIY5AGVLcBe75cl0v8pB0qf5eiQPl_E65IqHn4i3lisoUaufUVxPBz22EFcve7pQNcRoD9UYojOtKrvJCF024pcK8kVfx9NwBcVcIx0hDeWxkVsQabP9sm2YeFXFeQNr72zH3PtbW-fEmvN11grHQFm1smaOdJJegTb_u1S4CzMhcVGzcxykjNiF1wakLoaB6qSGc3yf5PfCout_JCWivfCPqXs5GvckKOU6uQueM7Gx-WVib-27UcAUchGeP-8Q9aGTnpJAffrDJt8psSTufgdOYZBV3xws59cHy_aT0IcAeZ9Ohd1Gh1DOLNg7m9PfT9H-x3SfshWgfSwDoe7shwEf_-jx9DS-rN5b-JLkWV9XZg%2C%2C`


`https://push.aarth.net/?cid=eKZTk&sub2=15687161522945057579119251623467124&sub3=1730411&a=358&c=39&ci=139&sub8=MY`

`https://c.leadtracs.com/?a=358&c=39&E=fv5fUfRDZIY%3d&s1=358&s2=15687161522945057579119251623467124&s3=1730411`

`https://invol.co/aff_m?offer_id=100739&aff_id=114758&source=deeplink_generator&aff_sub=7-blua4g8l119cklqtvve0&aff_sub2=358&aff_sub3=1730411`

`https://shopee.prf.hn/click/camref:1011l7zKx/adref:31391/pubref:efe8b9f12d394b42b4d5bfc90c80228c`

**Comment by christophertino** [comment]
Relates to #22

**Comment by smalluban** [comment]
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.
