### ISSUE TITLE
Ghostery findings not showing correctly in Firefox when launched from overflow menu

### ISSUE THREAD

**Issue by ondrahlavac** [ghostery/ghostery-extension#449]
### Description

In the browser toolbar, when Ghostery icon is moved to the overflow menu in Firefox, the detailed view is broken and won't show due to lack of space.
See attached images.

**Correct view:**
![Image](https://user-images.githubusercontent.com/510361/64869972-bc7cec80-d642-11e9-92e7-eeaf5a4ff04f.png)
**Ghostery moved to *Overflow menu***
![Image](https://user-images.githubusercontent.com/510361/64869982-bf77dd00-d642-11e9-9dfd-e6d29a7c9d79.png)
**Ghostery findings window opened from the *Overflow menu***
![Image](https://user-images.githubusercontent.com/510361/64869990-c30b6400-d642-11e9-9dc2-5930d1487757.png)

### Expected Behavior 

Ghostery should either have a responsive layout or display outside of the overflow menu container.

### Actual Behavior 

Ghostery displays its findings dialog inside of the *overflow menu* container/dialog, thus making half of it unreadable.
See attached images.

### Steps to Reproduce

1. Open customize toolbar in firefox
2. Move Ghostery icon to the overflow menu
3. Save the toolbar layout
4. Open overflow menu (>>)
5. Click on Ghostery icon

### Versions

+ Browser: 70.0b5 64-bit
+ OS: Win10
+ Node: n/a
+ NPM: n/a

**Comment by babant** [comment]
Same thing happens in FF 69.0 (64-bit)

**Comment by babant** [comment]
Not a problem for me. Just thought you should know about it. ;-)

**Comment by christophertino** [comment]
Thanks for reporting.  This has been a known issue for a little while. We have plans to pull out the old Foundation framework and when we do, we'll make the panel view responsive.

**Comment by spbuda** [comment]
How can you label this "feature enhancement" when the feature doesn't work in its current state? That seems pretty short sighted to me. I mean, I guess it's maybe technically true, but that's a completely ludicrous labeling.

**Comment by SilverSaw** [comment]
I just want to remind that this is still an issue today !

**Comment by shinykari** [comment]
This is still an issue, using Firefox 95.0.2 on Mac OSX 12.1

**Comment by CyberK744** [comment]
Hi, just to remind that this is still an issue with Firefox 102.0b6 (64-bit) on Windows 11 (64-bit)

**Comment by chrmod** [comment]
FYI We're working on a new Ghostery panel. Which will scale properly to smaller sizes.

**Comment by smalluban** [comment]
Firefox has been updated to v10.
