### ISSUE TITLE
firefox startup problem

### ISSUE THREAD

**Issue by geofflau** [ghostery/ghostery-extension#465]
### Description
Ghostery now opening its home page automatically

### Expected Behavior 

It not to open automatically on browser startup

### Actual Behavior 

Ghostery now opening its home page as an additional window every single time on Firefox startup

### Steps to Reproduce

1. start up Firefox
2. [Second Step]
3. [and so on...]

### Versions

+ Browser: Firefox 68.2.0esr
+ OS: 10.11
+ Node:
+ NPM:

**Comment by christophertino** [comment]
Related to #456 which is fixed in v8.4.3. Unfortunately, that release is still pending Firefox review.

**Comment by christophertino** [comment]
This should be fixed in v8.4.5 which was approved today by AMO.  Please let us know if you still see this issue.
