### ISSUE TITLE
Trusting the "localhost" site doesn't work

### ISSUE THREAD

**Issue by gdoron** [ghostery/ghostery-extension#470]
### Description

I trust localhost:3000, getting OK green color. Refresh the page and my resources are back on blocked.

### Versions

+ Browser: 78.0.3904.87
+ OS: MacOS

**Comment by christophertino** [comment]
It looks like the port number is messing up the whitelist URL matching. It seems to work fine with just `localhost`.  I'll get a bug ticket made up for this. 

As a suggestion to help in the meantime, you could set up Apache locally with a Reverse Proxy and give your application a test URL instead of localhost.  

```
<VirtualHost *:80>
    DocumentRoot "PATH/TO/PROJECT"
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
    ServerName yourdevsite.test
</VirtualHost>
```

**Comment by gdoron** [comment]
If you can point me to the regrex place, I'll try to fix it and open a PR.
@christophertino

**Comment by christophertino** [comment]
Thanks for the offer!  Take a look at `checkSiteWhitelist` here https://github.com/ghostery/ghostery-extension/blob/7a2d7083a290ff06a546077953d16193dcb65a4c/src/classes/Policy.js#L64

I'm guessing the url parser in that function (`processUrl`) doesn't like localhost.

**Comment by EoinGriffin-AI** [comment]
As a workaround until the bug is fixed, as long as you know the port number it's possible to manually enter that into the settings:
![image](https://user-images.githubusercontent.com/6333375/72115826-28274b80-32fd-11ea-8c1c-25874b8b3b80.png)

**Comment by Haraldson** [comment]
@EoinGriffin-AI Where’s this setting now? Or does it only apply for the Plus version?
