### ISSUE TITLE
Blockadblock

### ISSUE THREAD

**Issue by reginaspectrlor** [ghostery/ghostery-extension#478]
Blockadblock attacked again, ghostery don't bypass the wall.

**Comment by remusao** [comment]
Hi @reginaspectrlor,

Could you please provide more details about the issue?

Thanks

**Comment by reginaspectrlor** [comment]
It's simple, sites using blockadblock are blocking ghostery from acessing them.

**Comment by reginaspectrlor** [comment]
for example - https://pipocas.tv/

**Comment by remusao** [comment]
Thanks! I will have a look.

**Comment by reginaspectrlor** [comment]
Thank you.

**Comment by remusao** [comment]
@reginaspectrlor the bug was identified and a fix is being deployed right now. The issue was in our rules builder so this will not require an update of the extension. Things should fix themselves for you in up to a few hours. Thanks again for reporting the issue!

**Comment by reginaspectrlor** [comment]
Thank you, 

Ghostery have plans to add something in the near future to take care of "cookie warnings" and popups?

**Comment by remusao** [comment]
@reginaspectrlor We have been developing a new feature called `autoconsent` which is currently only available in [Cliqz browser](https://cliqz.com/en/magazine/cookie-pop-up-blocker-cliqz-automatically-denies-consent-requests). It allows to both hide cookie notices but also *automatically opt you out of all categories* on websites you visit! Multiple users already requested this feature for Ghostery and we have been discussing it internally; we will keep you posted!

**Comment by reginaspectrlor** [comment]
So the popup plague is discarded in ghostery, you avoided that one.

So you are developing a half adblocker in that manner...2030 eta?

You could drop in benchmarks if you add more feautures. lol
