### ISSUE TITLE
Nónio - PT users

### ISSUE THREAD

**Issue by reginaspectrlor** [ghostery/ghostery-extension#479]
In March 2017 came the first news about the Nónio platform.

Some of the largest national media groups have teamed up to create a single sign-in platform, Nónio, to "deliver more personalized content with more security and quality."

In order for this to happen, adherent websites need to collect and store vast amounts of data from each reader. In this transitional period, adhering websites are asking each reader to register on this platform to begin data collection.

By registering, the Nónio platform will have access to a huge set of personal data. Registration can be done using external service credentials or the usual email.

If you choose the social network option, you'll need to share the following information: name, profile photo, email address, date of birth and location, or if you choose email, you will need to submit your name, gender and date of birth. The sign up process is very simple because the platform needs to have a large readership in a short time so that by early 2018 it will have enough strength to end the transition period and force everyone to join the system as planned .

That is, in the near future, if Nónio is successful, he will only be able to read articles after registration.

The reader MUST NOT register with Nónio for three main reasons:

Privacy violation
Violation of the General European Data Protection Regulation (GDPR)
Bubble filter effect.
Privacy violation
A reading of Nónio's privacy policy , this platform violates your privacy because it collects through cookies and other fingerprinting techniques the following data: the IP address of each session, date and time of access to the article, web browser version and system. operating system, screen resolution, location data, Wifi access points, canvas signature, and more.

It is currently possible to unify these signatures / fingerprints even using different web browsers on different platforms . See demo with some data that can be obtained .

The platform will collect and store all the history of the articles you read from the participating websites . As stated on the official page:

"Using the Internet and its services necessarily implies the transmission of information at international level. Therefore, by relating to us and by consenting to the communication of data to third parties, you acknowledge that you know and consent to the processing of data. on this scale "

That is, all this data can be accessed by third parties. Even if the reader wishes to delete his / her data, it will only be deleted or anonymized one year after the registration has been deactivated by the user. In the world of Big Data, there is no anonymous data (read article where examples of database de-anomization are given).

From the analysis of these data it is possible to infer for example: political affiliation, religion, purchasing power, emotional state, sleep patterns. For more details, see the Corporate Survey Report and the Working Paper How Companies Use Personal Data Against People .

These websites already violate the privacy of the reader by providing third party trackers such as Facebook, Google and some data brokers like BlueKai, DataLogix, etc ....

Visiting some of the adhering websites with a Firefox browser and with only the uBlock Scope extension, the following results were recorded. To validate the results we used the Webbkoll and PrivacyScore tools.

Website | 3rd party requests(*) | First Party cookies | Third party cookies
-- | -- | -- | --
publico.pt | 105/39 | 28 | 22
expresso.sapo.pt | 177/40 | 15 | 30
rr.sapo.pt | 50/25 | 20 | 18
blitz.pt | 129/40 | 14 | 28
visao.pt | 383/39 | 14 | 28
expressoemprego.pt | 78/18 | 8 | 14
exameinformatica.pt | 102/35 | 14 | 28
cmjornal.pt | 227/79 | 29 | 74
record.pt | 288/106 | 29 | 130
jornaldenegocios.pt | 210/71 | 19 | 90
sabado.pt | 206/71 | 20 | 64
tsf.pt | 199/73 | 29 | 52
jn.pt | 251/85 | 27 | 56
dn.pt | 202/71 | 26 | 47
ojogo.pt | 313/92 | 32 | 71
dinheirovivo.pt | 164/69 | 22 | 53
radiocomercial.iol.pt | 67/28 | 8 | 8
maisfutebol.iol.pt | 136/43 | 11 | 14

(*) Total number of requests to external domains / number of unique domains

Violation of the General European Data Protection Regulation (GDPR)
All data provided to us or collected by us in accordance with this Privacy Policy will be deleted or anonymized one year after the registration has been deactivated by you.
This sentence is taken from Nónio's Privacy Policy which is a violation of Art. 17 GDPR Right to erasure (the right to be forgotten) .

This violation may result in a fine of up to 4% of the annual revenue of the groups involved.

Bubble filter / echo chamber effect
We collect information about you with your explicit consent so that we can provide you with a personalized news delivery service according to your preferences, which forms the core of our services.
The more the reader interacts with this platform, the more data it receives about itself, and as a result, it will have an increasingly detailed reading tastes profile. Because the purpose / business model of the platform is to be as long as possible on the platform, the longer the exposure to advertising, more and more targeted articles will only be recommended from a certain point of view.

The reader over time will be inside an echo chamber. You are not exposed to information contrary to your preferences that could challenge or broaden your view of the world.

This phenomenon is called Eli Pariser "bubble filters". Viewing your Ted Talk is recommended - Eli Pariser: Be careful with bubble filters online

Secundary effects
In addition to the two problems mentioned, other no less important problems must be explained. From the analysis of these data, it is possible to infer the tastes of the Portuguese population, in order to maximize profits, more low journalistic articles (clickbait articles generate more traffic / revenue) will be written, leading to the decay of this noble profession. As a result, a population with less access to quality information does not make correct decisions, leading to the gradual decay of democratic regimes.

In short and as Zeynep Tufekci points out in her recent Ted Talk, we are creating a dystopia just to make people click on ads.

List of adherent websites by each group:

Renaissance Media Group :
Renaissance Radios, RFM , MegaHits , Yes
Company :
SIC Group
Express Newspapers
ACTIVE Magazines, Blitz , Guys , Guys Decorating , Vision , Exam , Computer Exam , Tv More , Telenovelas
Job Express Portals
Cofina :
Morning Mail Newspapers, Record , Business
Flash Magazines, Lives , Maximum , Saturday
Online Job Portals, CM Classifieds , That Machine
Global Media :
TSF Radios
Newspaper Newspapers , Daily Newspapers , The Game , Cash Money
Motor Magazines 24 , Men's Health , N-TV , Evasions , Around the World , Magazine News , Them
Media Capital :
TVI Group
Commercial Radios, City FM , M80 , Smooth FM , Vodafone FM
IOL Portal, Fußball , Auto Portal , Lux , Selfie
Sonaecom:
Public Newspaper

Filters for ublock - https://nonio.pt/antinonio.txt

If you can add this to ghostery would be helpful.

**Comment by christophertino** [comment]
Relates to #22
