### ISSUE TITLE
Suggestion: Remove the Purple Box and unify the panels

### ISSUE THREAD

**Issue by ghost** [ghostery/ghostery-extension#482]
# Description
This was originally a suggestion for the deletion of Purple Box that's turned on by default, sits on the bottom right side of the web page concealing elements from time to time (usually a "Customer Interaction" widget), and aims to show trackers at a glance after clicking on it.

I want this to be more of a discussion with the devs rather than a request. As it’s them who’s going to make the decision at the end.

However, it's not hard to see that it has similar functionality as Ghostery's "detailed" panel that shows all the trackers which I also think could be the default, unified panel as clicking on modules such as Ghostery Rewards even once automatically defaults to the detailed view already and stays there.

**Comment by lachlan-00** [comment]
The purple box should be removed completely; it's absolutely useless.

**Comment by christophertino** [comment]
Thanks for the feedback. I just had to double check the code because I thought we had disabled the purplebox by default for new installs. I know we had talked about it internally before we launched Ghostery 8. 

We do have users who like the purplebox as a site diagnostic tool. But we should check to see how big that group is, and revisit the on/off-by-default discussion.

cc @adamarielaboy for UX discovery

**Comment by gurgunday** [comment]
> We do have users who like the purplebox as a site diagnostic tool.

Hi, it’s just a suggestion based on this sentence but maybe it would be better if anything related to website diagnostics was moved to Ghostery Insights like the purple box. Casual users who wish to see a generalized view of a webpage would just open the Ghostery panel to check.

**Comment by philipp-classen** [comment]
Update: since release 8.6.0, the purple box (Tracker-Tally) is an opt-in feature (https://github.com/ghostery/ghostery-extension/releases/tag/v8.6.0). For new installations, it is now disabled.

**Comment by chrmod** [comment]
Closing the issue for now as Tracker Telly is now opt-in
