### ISSUE TITLE
Problem with explicit proxy

### ISSUE THREAD

**Issue by gagzou** [ghostery/ghostery-extension#502]
### Description
**This problem is only on chrome** (not on Firefox or Edge).

All plugin options are disabled (normally, no filtering).
With certain websites (google drive for example), the chrome plugin blocks certain scripts.
Chrome does not respond to http 407 requests (proxy identification).
By disabling the plugin completely (Chrome control panel), the scripts on the page are loaded.

Problem also on twitter and amazon prime.

### Expected Behavior 

In explicit mode, the script must not be blocked by the plugin.

### Actual Behavior 

![ghostery](https://user-images.githubusercontent.com/61595839/75568554-c6a97080-5a53-11ea-9c0f-fafce3bcf3b3.jpg)

### Steps to Reproduce

1. connect google drive or twitter with explicit proxy.
2. open the developer window and check the various scripts in the network tab.

### Versions

+ Browser: Chrome
+ OS:  Windows 10

**Comment by christophertino** [comment]
What's strange is that those requests are first-party and shouldn't be affected by Ghostery. Our webRequest pipeline should ignore them.  It's possible that implementing [webRequest.onAuthRequired](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired) could help.
