### ISSUE TITLE
Ghostery for Chrome 8.4.7 fails to recognize Matomo Tracker in some websites while recogninizing it in others

### ISSUE THREAD

**Issue by luisAtMonday** [ghostery/ghostery-extension#513]
### Description

I'm one of the web developers working on these 3 sites, all for the same client:

https://www.dieversicherer.de/versicherer
https://gdv.de/de
https://en.gdv.de/

All of these sites have Matomo-Tracking built in, with the expected script in the head of each site:

<script type="text/javascript" async defer src="//analytic.gdv.de/matomo.js"></script>

### Expected Behavior 

Ghostery recognizes the "matomo.js" in the script source and blockes the Tracker on all sites

### Actual Behavior 

The Tracker is only being blocked on dieversicherer.de
On the other 2 sites the Tracker isn't being recongnized.

### Steps to Reproduce

1. Go to each of the sites

### Versions

+ Browser: Google Chrome Version 80.0.3987.132
+ OS: Mac OS 10.14.6
+ Node: 6.9.2
+ NPM: 3.10.9

**Comment by grgnday** [comment]
For me, it caught the one in the first website. However, I can confirm that nothing is shown on the other ones.

**Comment by christophertino** [comment]
This is because Ghostery considers `analytic.gdv.de/matomo.js` to be first party on https://gdv.de/de and https://en.gdv.de/.  By default Ghostery blocks third-party tracking.  You can enable first-party blocking in Settings > General Settings > uncheck "Allow trackers created by site owners".
