### ISSUE TITLE
Ghostery keeps removing elements/preventing them to load for trusted Localhost

### ISSUE THREAD

**Issue by JorgeSivil** [ghostery/ghostery-extension#515]
### Description

The extension in Firefox is removing a link tag from my page. It doesn't have ads or anything, it is just plain javascript.
I whitelisted localhost:8080 and localhost:9001 (webpack server), but the only way to get that script tag load is to pause Ghostery.
Interestingly it removes also the CSS link. I have no reference in my page for the word **listCollectionBottom--mobile-v2** and once I pause Ghostery, the elements get loaded.

```
<script src="//localhost:9001/dist/listCollectionBottom--mobile-v2.js?v=a213b8ad212a2856dfc7d7d27e2ddd9c" async=""></script>
<link rel="stylesheet" media="all" href="//localhost:9001/dist/listCollectionBottom--mobile-v2.css?v=b9395a4b3477b574da5daa2bdfc23688">
```

### Expected Behavior 

Whitelisting the page should not make any modifications to the page (i.e removing elements).

### Actual Behavior 

Page was missing some scripts and css elements in the HTML.

### Steps to Reproduce

1. Go to https://m.ranker.com/crowdranked-list/best-movie-characters-of-all-time?ref=foot
(you might have to log in and in the user menu click on "Mobile site")
2. Look for listCollectionBottom--mobile-v2  (it won't be there, script is lazy loaded but should not take more than 5 seconds)
3. Trust the site
4. Reload and look for listCollectionBottom--mobile-v2, now it will appear.

I need to know two things:

1. Why is listCollectionBottom--mobile-v2.js forbidden by Ghostery (couldn't find logs in the extension).
2. Why this Trust Site works for the top level domain but not for localhost.
![image](https://user-images.githubusercontent.com/12187148/77353187-4a870d80-6d1f-11ea-875d-0f24dc743cb1.png)
As you can see in the image, localhost:8080 is trusted, yet Ghostery is still removing that element.
3. Could it be that Ghostery has some kind of "intelligence" that when it sees a script loading some ad trackers then it stops the script from further running? Don't know if that's possible tho.

### Versions

+ Browser: 75.0b7 (64-bit)
+ OS: Ubuntu 20.04

**Comment by remusao** [comment]
Hi @JorgeSivil and thanks a lot for taking the time to open this issue,

May I ask you to try and disable only "advanced adblocking" instead of pausing Ghostery completely? I'd like to know if the issue comes specifically from the adblocker component (that is my guess for now).

Would you maybe be able to share a minimal HTML page which I can use on my side to reproduce this issue?

Last not least, the localhost whitelisting issue is already being discussed on here: https://github.com/ghostery/ghostery-extension/issues/470

Thanks a lot for your help!
Best,

**Comment by christophertino** [comment]
There's probably a few things happening here. The first is an issue with Trust Site and localhost:port (#470 as already mentioned) that has been released to all browsers but is still pending review in Firefox. You can check [this comment](https://github.com/ghostery/ghostery-extension/issues/470#issuecomment-572819067) for a temporary workaround. 

The listCollectionBottom--mobile-v2 script is most likely being caught by smart blocking.  It's meant to auto-block trackers that take longer than 5sec to load, but at times can be over aggressive.  In Ghostery, if you turn off the Light Bulb icon does it solve the issue?

**Comment by ibrahimBeladi** [comment]
I noticed that it do not take port into account, hence seeing localhost:port is unknown at each reload. Added the url manually through the setting solved my issue.

**Comment by JorgeSivil** [comment]
I have reinstalled Ghostery and checked for this

Toggling the 3 buttons (Smart blocking, etc) one at a time didn't make any effect. The script was still being blocked from being appended to the DOM.

But the good thing is now Trusting the site works as the script gets loaded correctly.

**Comment by christophertino** [comment]
Thanks for the updates.  I'll close this ticket but reach out if you have any other issues.
