### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getManifest' of undefined

### ISSUE THREAD

**Issue by bmblb** [ghostery/ghostery-extension#539]
### Description
Getting this exceptions on some pages:
```
Uncaught TypeError: Cannot read property 'getManifest' of undefined
```
No runtime? Please add a check?
![image](https://user-images.githubusercontent.com/45400762/80597074-037fec80-8a30-11ea-951b-416e933556e0.png)

[Description of the bug or feature]

### Expected Behavior
Ghostery should never throw. And ideally don't even use try/catch inside to avoid interfering with debugging tools.
[What you expected to happen]

### Steps to Reproduce

Cannot really specify steps to reproduce, happens on intranet site.

### Versions

+ Browser: Chrome, latest
+ OS: Windows 10
+ Node:
+ NPM:

**Comment by christophertino** [comment]
This may be a known issue on Chrome, see [this response](https://stackoverflow.com/a/44251624). Regardless, it might make sense to pull logging from our content script files anyway.

**Comment by smalluban** [comment]
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.
