### ISSUE TITLE
Feature Request: Smart Blocking should not block live chat widgets in the middle of using them

### ISSUE THREAD

**Issue by ghost** [ghostery/ghostery-extension#550]
### Description
It's pretty annoying that Ghostery's smart blocking is blocking live chat widgets in the first place since they have their own category and if the user wants to they can pretty much block them easily. Plus there is (at this time) tracking protection which is pretty powerful tool that could stop PII leaks. If Ghostery will block these maybe it should do it immediately as waiting until the user starts using the chat widget and then blocking it really messes with the experience from time to time.

### Expected Behavior
Some heuristics could be added that will prevent Ghostery from blocking the widget when the user starts interacting (like in the share buttons).

**Comment by smalluban** [comment]
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.
