### ISSUE TITLE
Homepage Blocking

### ISSUE THREAD

**Issue by BrokenShoeLace** [ghostery/ghostery-extension#556]
I use 

https://uk.news.yahoo.com/uk/

as my homepage with for my desktop and android phone. On both platforms, I need to reload the page in order for ghostery to block and ads. Have set restricted page.

Broswer: Firefox (always latest versions)

Is this a bug?

**Comment by gurgunday** [comment]
When you launch your browser, Ghostery doesn’t start immediately. If you look carefully it warms up for a split second which usually results in it missing some ads. Maybe that could be your problem?

**Comment by BrokenShoeLace** [comment]
Yeah, that sounds about right.

Thank you for your reply
