### ISSUE TITLE
Annoyance Request: Washington Post

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#558]
### Description
For those of us using **Ads + Trackers + Annoyances**:
Banner at the bottom of the screen takes up half the page upon scrolling.

### Steps to Reproduce

1. Go to `https://www.washingtonpost.com/nation/2020/05/26/amy-cooper-central-park/`
2. Scroll down.
3. https://postimg.cc/gallery/N5DFH8D

**Comment by gurgunday** [comment]
I’m really not sure but they’re probably using Fanboy’s Annoyances list. I can’t check atm but if that’s the case reporting it there could be better.

**Comment by yokoffing** [comment]
> I’m really not sure but they’re probably using Fanboy’s Annoyances list. I can’t check atm but if that’s the case reporting it there could be better.

To my knowledge, Ghostery has not disclosed how they are blocking annoyances.

**Comment by christophertino** [comment]
@remusao could you provide some insight here?

**Comment by remusao** [comment]
Hey, sorry for the delayed answer.

In a nutshell, Ghostery uses a mix of community-driven lists such as uBlock Origin annoyances or EasyList cookie, as well as some custom filters. We do not use Fanboy's annnoyances list at the moment, though.

@yokoffing Regarding the banner on washingtonpost.com, I have created a custom rule to handle it, it will be deployed to users before tomorrow.

Best,

**Comment by yokoffing** [comment]
@remusao, I always appreciate your insights on here and when I do run into you on Reddit!

As of the time me writing this, the banner still isn't blocked. I can check again in a few days.

**Comment by remusao** [comment]
Hey @yokoffing,

I checked and could reproduce that it does not work. It seems like there is a bug in the Ghostery extension source code (actually a typo), which breaks the selection of the custom presets from Ghostery... I already reached out to @christophertino to try and fix this ASAP. In the meanwhile, if you'd like to make it work on your side, you can open a debug console for the Ghostery extension (on Chrome: `: menu > More Tools > Extensions > Enable Developer Mode > click on Background.js for Ghostery extension`, then in `Console` you can enter the following: `CLIQZ.prefs.set('cliqz_adb_mode', 2)`; for Firefox you need to visit `about:debugging` in the URL bar, then `This Firefox` on the left, then `Inspect` on the Ghostery extension and paste the same command than for Chrome in the console). This will force the adblocker to use the `Ads + Trackers + Annoyances` preset.

Let me know if this does not work or if you need any extra details,
Best,

**Comment by yokoffing** [comment]
> It seems like there is a bug in the Ghostery extension source code (actually a typo), which breaks the selection of the custom presets from Ghostery.

@remusao, will this require a hard update to fix (e.g., Ghostery 8.5.1a or 8.5.2)?

> In the meanwhile, if you'd like to make it work on your side, you can open a debug console for the Ghostery extension

This works for me! The banner isn't on `https://www.washingtonpost.com/business/2020/06/30/paycheck-protection-program/`.

For Chrome, does entering `CLIQZ.prefs.set('cliqz_adb_mode', 2)` last perpetually or is this something I'd have to do every time I restart my browser? Also, does this setting get erased if I turn off Developer mode?

**Comment by remusao** [comment]
> @remusao, will this require a hard update to fix (e.g., Ghostery 8.5.1a or 8.5.2)?

Most likely yes. But the fix is very small so this could happen quickly if we move soon (@christophertino will know more about that).

> does entering CLIQZ.prefs.set('cliqz_adb_mode', 2) last perpetually or is this something I'd have to do every time I restart my browser

This is persisted across restarts.

> does this setting get erased if I turn off Developer mode?

No it will persist as well.

If you want to change between presets you can use the following:

* Switch to *ads only*: `CLIQZ.prefs.set('cliqz_adb_mode', 0)`
* Switch to *ads + trackers*: `CLIQZ.prefs.set('cliqz_adb_mode', 1)`
* Switch to *ads + trackers + annoyances*: `CLIQZ.prefs.set('cliqz_adb_mode', 2)`

Best,
