### ISSUE TITLE
Possible false positive with Adobe Test & Target rule (Facebook CDN)

### ISSUE THREAD

**Issue by steveluscher** [ghostery/ghostery-extension#560]
### Description

I have received a report of Ghostery blocking this resource. The block was made according to the ‘Adobe Test & Target’ rule:

```
https://static.xx.fbcdn.net/rsrc.php/v3/yM/r/MBOX6JqmhhS.js?_nc_x=yIsXPYraEd4
```

This is a resource from the Facebook CDN that, like many others like it, is critical for the operation of the website. Do you see anything about that file or that URL that would trigger that rule, and do you believe this to be a false positive that can be fixed?

### Expected Behavior

Resource should trigger no rule.

### Actual Behavior

Resource triggers the ‘Adobe Test & Target’ rule; gets blocked.

### Steps to Reproduce

1. Use Ghostery.
2. Load the Beta version of facebook.com.
3. Observe that `https://static.xx.fbcdn.net/rsrc.php/v3/yM/r/MBOX6JqmhhS.js?_nc_x=yIsXPYraEd4` triggers the ‘Adobe Test & Target’ rule; gets blocked.

**Comment by christophertino** [comment]
This looks like a false positive. Adobe Target uses something called `mbox` which we are catching in your Facebook CDN pattern. I'll get this cleaned up on our end. Thanks for reporting.

**Comment by steveluscher** [comment]
That's great news; thank you!

**Comment by smalluban** [comment]
Feel free to re-open if the issue is still valid. The only platform that is still on the v8 version is Firefox.
