### ISSUE TITLE
The add-on could not be downloaded because of a connection error (Firefox)

### ISSUE THREAD

**Issue by angelhair0** [ghostery/ghostery-extension#565]
### Description

When installing for Firefox, the extension downloads fully, and upon installation an Firefox error says "The add-on could not be downloaded because of a connection error"

### Expected Behavior

I expected the extension to successfully install, as the previous version successfully installed.

### Actual Behavior

Error after download/during install

### Steps to Reproduce

1. Download xpi or zip/open zip
2. Run installer
3. Error

### Versions

+ Browser: Firefox 76.0.1
+ OS: Mac 10.14.6
+ Node: ?
+ NPM: ?

**Comment by christophertino** [comment]
If you're attempting to load a Ghostery build from a GitHub release, you'll need to load it as a temporary add-on with [about:debugging](about:debugging#/runtime/this-firefox). Otherwise you have to install from the [Firefox store](https://addons.mozilla.org/en-US/firefox/addon/ghostery/).
