### ISSUE TITLE
Ghostery renders reCAPTCHA incapacitated

### ISSUE THREAD

**Issue by acicali** [ghostery/ghostery-extension#570]
### Description

Ghostery is blocking Google's reCAPTCHA on all websites

### Expected Behavior

Google's reCAPTCHA is a necessary evil for using many services. It is expected that it continues to function as usual.

### Actual Behavior

Google's reCAPTCHA is no longer working (as of today). Instead, the <noscript> version of reCAPTCHA loads and it does not appear to function correctly (that's Google's fault).

### Steps to Reproduce

1. Install the Ghostery Chrome extension
2. Visit whois.godaddy.com and attempt to lookup a domain (or any other site that relies on reCAPTCHA, as far as I can tell)
3. Frown sadly as you realize how terrible Google's fallback version of reCAPTCHA is. It's completely unusable.
4. Remove the Ghostery Chrome extension and reload the page
5. See the working reCAPTCHA again, yay! (but also see many ads and trackers, not yay!)

### Versions

+ Browser: 83.0.4103.116 (Official Build) (64-bit) (cohort: 83_61_Win)
+ OS: Windows 8.1 (Build 9600.18684)

**Comment by christophertino** [comment]
We've pushed a library update from our end to fix this issue. Can you double check and make sure that it's working now?

**Comment by acicali** [comment]
Seems to have done the trick - thanks @christophertino!
