### ISSUE TITLE
Breakage: Complex.com

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#573]
### Description

Blocking "Complex Media Network" in the Advertising category prevents `https://www.complex.com` from loading properly. `https://www.complex.com/pop-culture/2020/06/seth-rogen-issues-rips-those-criticizing-his-black-lives-matter-instagram-post`

### Expected Behavior
 `https://www.complex.com`

![unblocked 2](https://user-images.githubusercontent.com/11689349/86140673-1742e000-babf-11ea-8544-e872876f7f47.jpg)

`https://www.complex.com/pop-culture/2020/06/seth-rogen-issues-rips-those-criticizing-his-black-lives-matter-instagram-post`

![unblocked](https://user-images.githubusercontent.com/11689349/86140678-18740d00-babf-11ea-9af2-06a49b3679d2.jpg)

### Actual Behavior
 `https://www.complex.com`

![blocked 2](https://user-images.githubusercontent.com/11689349/86140736-29bd1980-babf-11ea-90ad-6bbb9d4e6ecf.jpg)

`https://www.complex.com/pop-culture/2020/06/seth-rogen-issues-rips-those-criticizing-his-black-lives-matter-instagram-post`

![Blocked](https://user-images.githubusercontent.com/11689349/86140740-2b86dd00-babf-11ea-8c7a-64332b46b292.jpg)

### Steps to Reproduce

1. Block "Complex Media Network" in the Advertising category. This breaks the page from loading properly.
2. Click "Trust on this site" for page to load properly.

### Versions

+ Browser: Vivaldi Stable
+ OS: Windows 10

**Comment by yokoffing** [comment]
We don't need to remove "Complex Media Network" in the Advertising category. But I am suggesting we had one of those notifications that alert the user that this tracker needs to be enabled for the site to work properly.

**Comment by christophertino** [comment]
I've added this as a first-party tracker for complex.com.  It's handled under General Settings > "Allow trackers created by site owners", which is enabled by default. That should cover the majority of Ghostery users. Thanks for reporting.
