### ISSUE TITLE
Ghostery is not blocking an element on this website

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [ghostery/ghostery-extension#579]
### Description

[Description of the bug or feature]

There is a message not being blocked by Ghostery on this website ```https://lanacion.com.ar```

### Expected Behavior

[What you expected to happen]

I have enabled ghostery annoyances filter and is not working (I would like to point out that AdBlock and AdGuard do not have this problem, even when annoyances filter is not used. This only happens with Ghostery, so I decided to open an issue)

### Actual Behavior

[What actually happened]

This is the annoying element not blocked

![Screen Shot 2020-07-07 at 10 39 59](https://user-images.githubusercontent.com/67610240/86790955-5fbe4880-c03f-11ea-863f-3166e74765b1.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### Versions

+ Browser: chrome (up to date)
+ OS: macos (up to date)
+ Node:
+ NPM:

**Comment by christophertino** [comment]
This should be fixed now in v8.5.2, which is live on Chrome, Opera and Edge, and pending review in Firefox.  This was related to #558 and fixed in https://github.com/ghostery/ghostery-extension/commit/415b4cbcbd5439856d736516306bce12f826c299
