### ISSUE TITLE
Please do not discriminate against contributing minors

### ISSUE THREAD

**Issue by Natureshadow** [ghostery/ghostery-extension#6]
Hi,

citing from your code of conduct:

> In particular, we don't tolerate behavior that excludes people in socially marginalized groups.

Please consider children and adolescents a socially marginalised group. By hosting the code exclusively on GitHub, all contributors under the age of 13 years are excluded, and under most jurisdictions, people under the age of 18 have a major legal hassle contributing that can be reduced to a minimum.

Therefore, in accordance with your code of conduct, please do at least one of the following, in order of preference:

1. Move the project to a platform that does not discriminate against minors
2. Mirror the project on such a platform, and maintain the mirror
3. Accept contributions (feature requests, bug reports, and patches) through a channel that does not require agreeing to any terms, apart from the project licence, at all, and document that in clear side (probably in the CONTRIBUTING file and a clear note on that in the code of conduct).

If you wonder why children should matter for your project: Obviously, children do use web browsers, and if you want to protect web users, you should also consider young users. In a free software world, all users are welcome contributors. In practice, we (at Teckids, the FOSS youth organisation) we regularly see contributing children, nad in a survey conducted among students between 10 and 15 years, more than two thirds stated they wish for being able to contribute to the software they use. You can find 

For further details, you might want to have a look at the following two FOSDEM talks:

https://fosdem.org/2018/schedule/event/education_im/
https://fosdem.org/2018/schedule/event/too_young_to_rock_n_roll/

Thanks for taking this serious,
Nik, as head of Teckids e.V., the free software youth organisation

-- 
Dominik George (1. Vorstandsvorsitzender, pädagogischer Leiter)
Teckids e.V. - Erkunden, Entdecken, Erfinden.
https://www.teckids.org/

**Comment by christophertino** [comment]
It’s an interesting point.  We can set up an email distribution and accept patches via email.  I can add that to CONTRIBUTING.

**Comment by Natureshadow** [comment]
Hi Christopher,

> It’s an interesting point.  We can set up an email distribution and accept patches via email.  I can add that to CONTRIBUTING.

That would be a very welcom (first) step ☺!

-nik

**Comment by dmckenna24** [comment]
Good idea, Nik! As a young and naive contributor myself, it is nice for more experienced people to recognize this important idea. I also believe that labeling various issues that are good for novices will be a useful tool to including more people. :)

**Comment by trickpattyFH20** [comment]
@dmckenna24 issues of that nature will be labeled "good first issue". first time contributors can filter by "is:open label:"good first issue"
