### ISSUE TITLE
Ghostery is blocking reCAPTCHA v3 API key in Chrome with recaptcha.net #584

### ISSUE THREAD

**Issue by bencmbrook** [ghostery/ghostery-extension#636]
I'm getting the exact same issue as in #584 but with `recaptcha.net` which is Google's alt URL for reCAPTCHA
(https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally)

_Originally posted by @bencmbrook in https://github.com/ghostery/ghostery-extension/issues/584#issuecomment-737612168_

**Comment by sammacbeth** [comment]
We've just updated our anti-tracking lists to hopefully fix this. Could you test it on your end?
