### ISSUE TITLE
Ghostery is blocking hCaptcha (sometimes?)

### ISSUE THREAD

**Issue by e271828-** [ghostery/ghostery-extension#645]
### Description

hCaptcha.com is a privacy-focused online security service running on a big chunk of the web.

### Expected Behavior

Should not block.

### Actual Behavior

Seems to sporadically block. This appears to be a similar Ghostery issue to https://github.com/ghostery/ghostery-extension/issues/584

### Steps to Reproduce

1. Install Ghostery
2. Visit third-party site embedding hCaptcha.com, e.g. https://captcha.firewall.team/

**Comment by e271828-** [comment]
@sammacbeth bumping this.

**Comment by sammacbeth** [comment]
@e271828- do you still see this getting blocked? Here I don't see any issues completing the captcha.

**Comment by e271828-** [comment]
It seemed to happen after some time, rather than immediately after installing Ghostery. Was still occurring a few weeks ago.

**Comment by GoblinLegislator** [comment]
Well next time remember url shown t be blocked in ghostery's details tab.
