### ISSUE TITLE
Ghostery 'Trust Site' still blocking ads

### ISSUE THREAD

**Issue by TheSuj** [ghostery/ghostery-extension#651]
### Description

Trust Site does not work on a "new tab" page for Tab for a Cause

### Expected Behavior

I have an app called "Tab for a Cause" which displays advertisements on the new tab page of google chrome. These advertisements generate money that is donated to charity. Obviously, Ghostery blocks ads, so I selected "Trust Site" for the new tab page, expecting the ads to show up. 

### Actual Behavior

The ads do not show up, even when the site is trusted. 

### Steps to Reproduce

1. Download the extension "Tab for a Cause" for chrome
2. Open a new tab, with Ghostery enabled.
3. Select "Trust Site" within Ghostery
4. Open another new tab, or refresh the current tab.

### Versions

+ Browser: Chrome
+ OS: MacOS Catalina
+ Node:
+ NPM:

**Comment by christophertino** [comment]
I spent some time trying to debug this recently. It's a strange case of being a `chrome-extension` page url with all of the content loading in an iframe. I haven't been able to fix it yet.

**Comment by TheSuj** [comment]
> I spent some time trying to debug this recently. It's a strange case of being a `chrome-extension` page url with all of the content loading in an iframe. I haven't been able to fix it yet.

Thanks for your help! I downloaded a secondary chrome extension that redirects me to the Tab for a Cause page as a webpage rather than a new tab page with no url. When Tab for a Cause is loaded as a normal webpage, Ghostery is able to trust it. It's annoying, but it works for now I guess.

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
