### ISSUE TITLE
Blocks ajax post requests

### ISSUE THREAD

**Issue by parthibeyond** [ghostery/ghostery-extension#670]
Some of our users are using ghostery for ad-blocking were facing trouble using our site. The extension is blocking the ajax requests [Only Post] in our web application. Is this the desired behaviour of Ghostery Addon? Or Is there any workaround for this? 

Should we identify ghostery & ask the user to turn it off?

**Comment by christophertino** [comment]
Can you provide the site URL and the URL of the request that is being blocked?

**Comment by parthibeyond** [comment]
Sure @christophertino. The details are 

Site URL - https://biblesforamerica.org/place-order/
Request URL - https://ops.bfa.org/api/v1/orders/send_sms_code.json

**Comment by christophertino** [comment]
Looks like a false positive for Adobe Analytics. I made the change on our end. It will be out in the next release (about a week or so).  In the meantime, look for Adobe Analytics under Site Analytics in Ghostery and set it to Trust on this Site.

**Comment by parthibeyond** [comment]
Will the mentioned change be propagated to all ghostery users without an addon update?

**Comment by christophertino** [comment]
It will require an extension update because we are moving to an updated database format (see #616).  This will happen automatically for users with extension auto-updating enabled, which is the majority of our users.

**Comment by parthibeyond** [comment]
Hi @christophertino, When is next release planned?

**Comment by christophertino** [comment]
We're wrapping up regression tests hopefully today. I'd like to get the build submitted to the stores by Weds or Thurs of this week.
