### ISSUE TITLE
8.5.5 un-categorized trackers?

### ISSUE THREAD

**Issue by yokoffing** [ghostery/ghostery-extension#692]
### Description

I noticed two blank categories in the bottom of the tracker listings in our Desktop Browser for awhile. I assumed it was something going that was still in the alpha/beta stage, except now I'm seeing on a fresh 8.5.5 build of Ghostery on Firefox.

Look below "Comments".

### Behavior

![2021-02-18](https://user-images.githubusercontent.com/11689349/108391800-0d9df200-71e0-11eb-8b97-f4bdc87f0137.png)

Is this peculiar to just me or are y'all seeing this too? @christophertino @chrmod

**Comment by christophertino** [comment]
Good catch.  Those are new tracker categories that must have come over from the merge with whotracks.me data. I'll ask our UX designer to make some icons for those

**Comment by yokoffing** [comment]
Please also note with these new categories that they do not have a description when you over over the "i".

**Comment by RejZoRSheep** [comment]
I've reported this ages ago too, was reassured it'll be fixed in next update and the bug is still here deep into 2022?! Ugh?!

**Comment by chrmod** [comment]
fixed by https://github.com/ghostery/ghostery-extension/pull/825
