### ISSUE TITLE
Advertising false positive: AerisWeather

### ISSUE THREAD

**Issue by jkoelndorfer** [ghostery/ghostery-extension#697]
### Description

Hi there! Thanks for producing an extension to block ads - you're doing important work!

I'm opening this issue because some AerisWeather users have reported that Ghostery is causing a breakage when they interact with our weather data and mapping APIs. I believe the reason we have been flagged is because some of our customers are advertisers who make use of our APIs in their own ad widgets. As you can imagine, weather data has an enormous number of applications, perhaps the most critical of which are emergency management applications that have safety implications for our end users. AerisWeather is not, itself, an advertising company. We don't track, store, or sell user data -- rather, we aggregate weather information and make it available via our APIs.

The domains that AerisWeather uses to provide weather data and imagery match `*.aerisapi.com`. Specific examples include `api.aerisapi.com`, `maps.aerisapi.com`, and `maps[1-4].aerisapi.com`.

### Expected Behavior

aerisapi.com domains are not blocked by Ghostery.

### Actual Behavior

aerisapi.com domains are blocked by the "Aeris Weather" advertising rule.

### Steps to Reproduce

1. In the Ghostery extension configuration, ensure the "Aeris Weather" rule is enabled and "Smart-Browsing" is disabled
2. Navigate to https://www.aerisweather.com/weather/maps/radar. Notice that no radar imagery is displayed.
3. Disable blocking for "Aeris Weather" and reload the page. Notice that radar imagery now appears.

(note: there are other domains for which Aeris API calls are blocked even with "Smart-Browsing" enabled)

### Versions

+ Browser: Firefox 85.0.2
+ OS: Linux
+ Extension: Ghostery for Firefox version 8.5.5

**Comment by jkoelndorfer** [comment]
Hi there! It's been a few months. Any update on this?

**Comment by christophertino** [comment]
Thanks for following up. I'll update the pattern on our end and move this out of the Advertising category.

**Comment by christophertino** [comment]
The db updated was released earlier this morning. You should see it today.
