### ISSUE TITLE
Since 15.4.2021 Ghostery causes Google Drive documents to misfunction (no line breaks, broken editing)

### ISSUE THREAD

**Issue by tarmot** [ghostery/ghostery-extension#705]
### Description

Documents opened in Google Docs or Google Slides present their text paragraphs without visible line breaks. In Google Docs, all text just runs off the right side of the page, each paragraph being one line in height. In Slides, text wraps but does not move to the next line, keeping all text areas one line in height. Pausing Ghostery or Trusting the site will remove this issue. This issue first appeared on 15th April 2021 on my machine. Before that, these editing tools worked fine.

**Comment by juanito-z** [comment]
The same problem occurred in our team, strangely enough it did not occur in all 17 employees, but only in 3 employees.
They uninstalled Ghostly Pluign completely and reinstalled it, then everything worked again. Do you have another workaround? @tarmot

**Comment by tarmot** [comment]
Actually, just reactivating the plugin on Google Drive sites now after several days causes no problems, so the issue may have been caused by some transient change in Google's service.
