### ISSUE TITLE
"Promised response from onMessage..." error

### ISSUE THREAD

**Issue by Sly-Little-Fox** [ghostery/ghostery-extension#707]
### Description

Weird error `Promised response from onMessage listener went out of scope` appears.

### Expected Behavior

Everything goes fine.

### Actual Behavior

Ghostery throws an error `Error: Promised response from onMessage listener went out of scope` on all pages.

### Steps to Reproduce

1. Go to https://ghostery.com
2. Open console
3. See weird errors coming from Ghostery. 

### Versions

+ Browser: Firefox 88.0.1
+ OS: Linux Xubuntu 20.04
+ Node: 14.15.5
+ NPM: 7.10.0

**Comment by badmansan** [comment]
Confirm this bug.

`Error: Promised response from onMessage listener went out of scope ... background.js:841:170`

Versions

- Browser: Firefox 88-89
- OS: Windows 7
- Ghostery 8.5.5

Any ideas?

**Comment by christophertino** [comment]
This sometimes occurs when the Tracker Tally (aka Purple Box) is removed from the page while trackers are still loading. Try disabling it under Settings > Tracker Tally.

**Comment by Sly-Little-Fox** [comment]
> This sometimes occurs when the Tracker Tally (aka Purple Box) is removed from the page while trackers are still loading. Try disabling it under Settings > Tracker Tally.

Ok, will test! ~~I removed Ghostery as it was slow...~~

**Comment by michi-s** [comment]
> This sometimes occurs when the Tracker Tally (aka Purple Box) is removed from the page while trackers are still loading. Try disabling it under Settings > Tracker Tally.

I have the same issue.

The Tracker-Tally is already disabled.

**Comment by philipp-classen** [comment]
Potentially related to the problem reported for Chrome recently: https://github.com/ghostery/ghostery-extension/issues/806; in its core, the warning on Chrome is about promises that are neither being resolved nor rejected.

I thought the Firefox issues harder to reproduce though: while the Chrome issue almost instantly triggers, it is more work to get it on Firefox. That worked for me:

* Go to `https://www.spiegel.de/`
* Wait for around three minutes

Now I got multiple of these warnings:
```
 Error: Promised response from onMessage listener went out of scope
 ```

Probably also one of the main sources of this discussion:
https://stackoverflow.com/questions/69506506/what-does-error-promised-response-from-onmessage-listener-went-out-of-scope-m

**Comment by Sly-Little-Fox** [comment]
This only took 1.5 years to be fixed

**Comment by sghostt** [comment]
Hey @Sly-Little-Fox, send an email to support@ghostery.com with the link to this GitHub issue so we can show our thanks for your report and feedback with a coupon code to try our Ghostery Contributor Status features. Thanks for using Ghostery :)

**Comment by Sly-Little-Fox** [comment]
> Hey @Sly-Little-Fox, send an email to [support@ghostery.com](mailto:support@ghostery.com) with the link to this GitHub issue so we can show our thanks for your report and feedback with a coupon code to try our Ghostery Contributor Status features. Thanks for using Ghostery :)

I no longer use Ghostery, so...
