### ISSUE TITLE
Broken Page https://www.theage.com.au/

### ISSUE THREAD

**Issue by sghostt** [ghostery/ghostery-extension#716]
### Description

The ad-blocking feature is breaking the website https://www.theage.com.au/ by hiding the article on the page when enabled

### Expected Behavior

When visiting https://www.theage.com.au/ an article should be displaying

### Actual Behavior

When visiting https://www.theage.com.au/ the article is hidden due to ad blocking

### Steps to Reproduce

1. Launch Chrome
2. Visit https://www.theage.com.au/
3. Article does not display (to fix, disable adblocking, and refresh the page)

### Versions

+ Browser: Chrome Version 92.0.4515.131
+ OS: Win 10
+ GBE 8.5.8

**Comment by chrmod** [comment]
Seems to work fine in Ghostery 8.7.0
