### ISSUE TITLE
GBE Blocking Paywall

### ISSUE THREAD

**Issue by sghostt** [ghostery/ghostery-extension#718]
### Description 

GBE is blocking a paywall on https://www.augsburger-allgemeine.de/augsburg/Augsburg-Zehn-Punkte-Plan-soll-die-Augsburger-Innenstadt-fit-fuer-die-Zukunft-machen-id60086356.html

### Expected Behavior

Visit [article](https://www.augsburger-allgemeine.de/augsburg/Augsburg-Zehn-Punkte-Plan-soll-die-Augsburger-Innenstadt-fit-fuer-die-Zukunft-machen-id60086356.html) and be able to see a paywall when scrolling down a bit

### Actual Behavior

Visit [article](https://www.augsburger-allgemeine.de/augsburg/Augsburg-Zehn-Punkte-Plan-soll-die-Augsburger-Innenstadt-fit-fuer-die-Zukunft-machen-id60086356.html) and no paywall is visible

### Steps to Reproduce

1. Visit [article](https://www.augsburger-allgemeine.de/augsburg/Augsburg-Zehn-Punkte-Plan-soll-die-Augsburger-Innenstadt-fit-fuer-die-Zukunft-machen-id60086356.html)
2. Unable to see a paywall
3. Pause Ghostery and refresh, paywall visible

### Versions

+ Browser: Chrome Version 92.0.4515.131
+ OS: win 10
+ GBE 8.5.8

### GBE Active:
![paywallGBEactive](https://user-images.githubusercontent.com/57185518/129375350-df5ab28e-9f9f-4ff6-8ee6-fa08838ce7ec.png)

### GBE Paused:
![paywallGBEinactive](https://user-images.githubusercontent.com/57185518/129375431-a20753bb-2d75-4e8d-9037-0a9e5890257f.png)

**Comment by philipp-classen** [comment]
Should be fixed in the latest block lists.
