### ISSUE TITLE
Tracker Category Missing icons

### ISSUE THREAD

**Issue by sghostt** [ghostery/ghostery-extension#719]
### Description

In the GBE tracker list menu, the bottom two tracker category icons are not displaying

### Steps to Reproduce

1. Click the GBE icon
2. Settings
3. Global Blocking
4. Scroll down to the bottom two categories
5. Icons not displaying

### Versions

+ GBE 8.5.8

### Screenshot:

![GBE](https://user-images.githubusercontent.com/57185518/129412062-66a1f63b-f0aa-4cf6-b669-5a27910793e0.png)

**Comment by yokoffing** [comment]
This was brought up in #692

**Comment by chrmod** [comment]
fixed by https://github.com/ghostery/ghostery-extension/pull/825
