### ISSUE TITLE
www.chd4.com

### ISSUE THREAD

**Issue by manirhossen** [ghostery/ghostery-extension#720]
Unable to login in **https://www.chd4.com/index.php**

Below message PoPup.

![image](https://user-images.githubusercontent.com/56219261/132088478-26a19312-894a-480d-b76e-3619958ddb93.png)

### Versions

+ Browser: Chrome
+ OS: Windows 11

**Comment by chrmod** [comment]
This website seems to be adblocker hostile. I'm afraid there is little we can do to change their mind. That said, I seems to load correctly ATM.
