### ISSUE TITLE
Left Panel Pushed Down-Long URL

### ISSUE THREAD

**Issue by sghostt** [ghostery/ghostery-extension#724]
### Description

When GBE 8.5.8 is open on a page with a long URL the left panel of the menu is pushed down

### Versions

+ Browser: Chrome Version 93.0.4577.82 (Official Build) (64-bit)
+ OS: Win 10
+ GBE 8.5.8

### Screenshot

![LeftPanelPush](https://user-images.githubusercontent.com/57185518/133848009-bb4ad398-6508-4e19-81eb-d1eac4500703.png)

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
