### ISSUE TITLE
Issue with scrolling on Canyon website

### ISSUE THREAD

**Issue by kospl** [ghostery/ghostery-extension#748]
### Description

Ghostery breaks page scrolling behaviour.

### Expected Behavior

Page scrolled after Ghostery blocks cookie banner.

### Actual Behavior

Ghostery blocks cookie banner but also page becomes not scrollable anymore.

### Steps to Reproduce

1. Open https://www.canyon.com/en-ua/
2. See cookie banner appears, and then got removed by Ghostery.
3. Try scroll page.
4. Vertical scroll is not working.

P.S. Looks like links on a page are not clickable too after cookie banner removed.

### Versions

+ Browser: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
+ OS: Windows 10
+ Ghostery extension: 8.6.1

**Comment by chrmod** [comment]
Thank you for reporting. Sadly this sometimes happen when removing annoyances like cookie banners. We will take a look if we can find a nice fix.

**Comment by chrmod** [comment]
With Ghostery 8.7.0 I cannot reproduce it any longer but I expect the problem was fixed on the community block list side.
