### ISSUE TITLE
Issue with scrolling on Withings website

### ISSUE THREAD

**Issue by kospl** [ghostery/ghostery-extension#749]
### Description

After cookie banner removed by Ghostery, page becomes not scrollable.

### Expected Behavior

Page can be scrolled.

### Actual Behavior

Page is stuck at the beginning and no scroll available.

### Steps to Reproduce

1. Open [Withings page](https://www.withings.com/ua/en/withings-move)
2. See Ghostery removes cookie banner
3. Try scroll page down

### Versions

+ Browser: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
+ OS: Windows 10
+ Ghostery version: 8.6.1

**Comment by chrmod** [comment]
This seems to be solved on the community block list side.
