### ISSUE TITLE
Issue with cookie banner on Make website

### ISSUE THREAD

**Issue by kospl** [ghostery/ghostery-extension#755]
### Description

When Ghostery is enabled, cookie banner is stuck on a page forever without any button to close. This is annoying and takes a place on a screen without any control to hide it. I read that they use cookies - now what, why this information is following me while I scroll a page?

### Expected Behavior

Expected behavior - there is any button to close cookie banner, example screenshot when Ghostery is disabled (with Decline and Accept buttons):
![image](https://user-images.githubusercontent.com/26386660/155178042-e0cb4ef5-fe71-4acc-abc8-5b355f09e2fa.png)

I can click _Decline_ and banner is gone:
![image](https://user-images.githubusercontent.com/26386660/155179799-48a73ee0-4937-4f6f-8bae-42d3ab3a9bfd.png)

### Actual Behavior

There is grey block "This website uses cookies to enhance the user experience." that is sticky at the bottom of a screen displayed on every page, without any controls to close:
![image](https://user-images.githubusercontent.com/26386660/155178105-7b8a6322-bb98-4915-a812-aea1d151c9e2.png)
![image](https://user-images.githubusercontent.com/26386660/155178430-489c564b-66bc-4b48-90e2-ae48feccc81c.png)

### Steps to Reproduce

1. Open https://www.make.com/en
2. Scroll page down

### Versions

+ Browser:  5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
+ OS: Windows 10
+ Ghostery extension: 8.6.1

**Comment by chrmod** [comment]
@kospl thank you for reporting. 

This should be fixed now on the easylist side. Thank you @ryanbr
