### ISSUE TITLE
AdBlocker blocks entire body

### ISSUE THREAD

**Issue by bennyborn** [ghostery/ghostery-extension#761]
Hi there, @remusao pointed out that my problem best belongs into this repository.

When visiting any of the following pages the entire body gets set to `display: none`

- https://www.rheinhessische.de/
- https://www.numero2.de/
- https://www.hunkler.de/
- https://www.obstbau.org/
- https://www.winzervereindeidesheim.de/
- https://contao-marketingsuite.com/

This is due to a list of CSS-selectors that is used to block certain elements. One of these selectors is `.cookie-bar-visible` which applies to the `body` of each aforementioned page if the Cookie-Consent is shown (seems to origin from the `Fanboy's Annoyance List`).

The Cookie-Consent is part of an extension for the CMS Contao. Being the author of this extension I can tell you that there are at least 10.000 more potential sites that are blocked this way so a general solution to those "lax" selectors would be needed.

**Comment by chrmod** [comment]
Rules like `.cookie-bar-visible` should probably not apply when placed on body. A better way to express them would be with `.cookie-bar-visible:not(body)`.

**Comment by chrmod** [comment]
This should be fixed in Ghostery 8.7.0. Thank you for reporting @bennyborn

**Comment by bennyborn** [comment]
Glad I could help! 😉
