### ISSUE TITLE
Consent managers should not be blocked

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#768]
As we put content managers in essentials category, they should not be blocked by default. This is sadly not the case if the community list provide a cosmetic filters to remove them. 

There are technical limitations to deal with this situation:
* Often it is not possible to match the cosmetic filters with a given 3rd party as CSS rules can be very generic.
* atm we have no way to update adblocker engine in a way to disable single rule only (but it should be possible)

**Comment by ryanbr** [comment]
Consent managers will include trackers (fingerprinting etc), maybe not block by default. But give an option for a user to block

**Comment by smalluban** [comment]
CMPs currently have a separate category, which can be selectively blocked by the user.
