### ISSUE TITLE
Always allow tracking redirects

### ISSUE THREAD

**Issue by mjmatthiesen** [ghostery/ghostery-extension#786]
### Description

With a recent change, I now get "ghostery prevented tracking redirect". That would be great, except ublock already does this.

### Expected Behaviour

I fixed the spelling of behaviour above. I would expect there to be a setting so I can disable this, but there's no clear setting.

### Actual Behaviour

I had to click, then click, then click some more and more.

**Comment by chrmod** [comment]
We should definitely allow users to disable this behavior and while implementing it we should update the design. 

On the redirect we could show WhoTracks.Me stats of the landing page.

**Comment by philipp-classen** [comment]
Test URL: https://techcrunch.com/2022/05/24/ddg-microsoft-tracking-blocking-limit/

**Comment by philipp-classen** [comment]
This is how the feature works:
1. For each requests, it will be [decided whether it should be blocked](https://github.com/ghostery/ghostery-extension/blob/c24ea1e63ef4e7d1bdfcaa00453d38dceaaf8ac9/src/classes/EventHandlers.js#L348). That is done with blockingWebrequestAPI (beforeRequest).
2. In case of a redirect, the request will be blocked and then immediately (with `setTimeout(..., 0)`) afterwards, the extension [will change the URL](https://github.com/ghostery/ghostery-extension/blob/c24ea1e63ef4e7d1bdfcaa00453d38dceaaf8ac9/src/classes/EventHandlers.js#L638) to be the redirect information page.

If we add a flag to disable it, skipping step 2) is a way to implement it.

**Comment by chrmod** [comment]
This option is now available in Ghostery settings.

Thank you for the report @mjmatthiesen 
<img width="589" alt="Screenshot 2022-10-21 at 10 27 52" src="https://user-images.githubusercontent.com/1228153/197150068-bac76582-255e-4998-878a-15de06c2815a.png">

**Comment by mjmatthiesen** [comment]
Great, thanks! Just waiting on firefox to update ghostery so I can uncheck that last one :)

**Comment by mjmatthiesen** [comment]
When is this update being released? I'm on "Ghostery for Firefox version 8.7.6" and the setting isn't there.

**Comment by philipp-classen** [comment]
> When is this update being released? I'm on "Ghostery for Firefox version 8.7.6" and the setting isn't there.

Yes, Firefox is still on 8.7.6 but the changes are included in the 8.9.5 release that we want to push to Firefox (it is already live on Edge/Opera and partly rolled out on Chrome). Unfortunately, I cannot give an exact date when it will land on the Firefox store, as it depends on reviews, which are outside of our control.

@mjmatthiesen I'll update the post here when I know more. But I hope the release goes out soon.

**Comment by philipp-classen** [comment]
> Thanks. Just thought I was going crazy because I still didn't see it. If it's not rolled out it's not rolled out. All good.

Now 8.9.5 is live on all platforms.
