### ISSUE TITLE
old.reddit.com doesn't work when ghostery is active (firefox)

### ISSUE THREAD

**Issue by mjmatthiesen** [ghostery/ghostery-extension#807]
### Description

Browse to old.reddit.com with ghostery active. Page remains blank. Pause ghostery. Reload. Page works. This is firefox, no idea about other browsers.

### Expected Behaviour

It worked yesterday.

### Actual Behaviour

Blank page.

### Steps to Reproduce

See description.

### Versions

+ Browser: Firefox
+ OS: Windows
+ Node: No idea
+ NPM: and don't care

**Comment by philipp-classen** [comment]
I also saw it on the normal Reddit site (`https://www.reddit.com/`). It was unable to load on one of my profiles. It seemed to get stuck in loop trying to download videos, but wasn't able to make progress.

The effect was that the site is blank, but my machine was under load and it downloaded a lot of data (>150mb and continuing).

Switching blocklists (Settings -> Ad Block Lists) fixed it for me. Even after I switched back to include annoyances. Switching back and forth downloads the latest block lists as a side-effect. To be verified, but I have the impression that the community blocklists fixed it.

**Comment by philipp-classen** [comment]
Confirmed now: reloading the block lists fixed it for other profiles as well.

If you are affected and want to force an update of the blocklists to get the fix, follow these steps:
* Go to Settings -> Ad Blocking
* Change the settings to something else and change change back (if will force a blocklist update)

![settings-ad-blocking](https://user-images.githubusercontent.com/1616509/176875249-9c0edd90-79c3-4621-8a5a-61b02dc49571.png)

If you then reload Reddit, it should work again.

**Comment by mjmatthiesen** [comment]
Thanks. Works.
