### ISSUE TITLE
TIP: Using password manager extensions to login to the Ghostery extension

### ISSUE THREAD

**Issue by MichaelKing1832** [ghostery/ghostery-extension#812]
ProTip for users with the FF (Firefox) browser and password managers (e.g. BitWarden):

With the release of Ghostery extension 8.7.6 for Firefox, logging in will be an infrequent activity, but when you need to do it, this makes it easier to leverage your password manager extension to log in the Ghostery extension.

1. Open Firefox and login to your password manager extension.
2. Use the password manager extension to launch the Ghostery.com website login URL. ( https://signon.ghostery.com/ )
3. Login to the Ghostery.com wesbite normally using your password manager extension
4. You will automatically also be logged into the Ghostery extension.

This is useful because when you are entering login credentials within the Ghostery extension, you are not able to access the other extensions, like BitWarden, to look up and copy/paste the credentials from that extension into Ghostery extension.

FF: 102.0.1 (64-bit) on WIn10 21H2 (build 19044.1826) with Ghostery 8.7.6.

**Comment by chrmod** [comment]
This is a great suggestion - thank you. In future releases we plan to remove the login form from the extension, so users will always login via website and thus be able to use password managers.
