### ISSUE TITLE
[FF Extension] Input validation failure. Leading whitespace from login email not removed/trimmed.

### ISSUE THREAD

**Issue by MichaelKing1832** [ghostery/ghostery-extension#813]
### Description
Entering an email address inadvertently including leading whitespace (I did not test trailing whitespace) results in a blocking error claiming an invalid email address was entered. Because the user entry error was to include "invisible" whitespace, this is not visually apparent to the user who only sees what they think is their valid email address. This is a source of user frustration.

### Expected Behavior

User entered input where whitespace is not allowed, should be automatically trimmed of all leading whitespace (non-printable characters) and trailing whitespace (non-printable characters). Those are invalid characters for an email address, and as such, automatically removing any such characters from leading and trailing positions improves not only the user experience (avoiding reporting a blocking input user error that is not visible to the user) but also removes potential invalid input attack surface to improve overall security of the extension.

Further, I would report separately invalid email addresses that include invisible (non-printable) whitespace characters to clearly inform the user that the reason their email input was rejected is not visible, to prompt further user inspection before re-entry. This also avoids automatic removal of whitespace from the interior of the email address that would otherwise obfuscate an automated attack as the data source used by the attacker would not be classified as a valid "email" address (e.g. CRLFs around the "@" character) that are only composed by the vulnerable extension itself into a valid email address at evaluation time.

### Actual Behavior

Entered " user@example.com". Login entry was rejected due to invalid email address provided. Visually, there is no indicator as to the cause of the invalid nature of the entry, as all leading whitespace is not rendered by browsers. 

### Steps to Reproduce

1. Begin login to Ghostery extension.
2. Enter " user@example.com" into the Ghostery extension user login panel for the Ghostery account email address. Note the leading space character.
3. Enter the user password as normal into the user login panel for the Ghostery account password .
4. Login entry will be rejected due to invalid email address provided. 
5. Visually, there is no indicator as to the cause of the invalid nature of the entry, as all leading whitespace is not rendered by browsers. 

### Versions
Ghostery for Firefox version 8.7.6, Firefox 102.0.1 (64-bit) on Windows 21H2 (19044.1826).

**Comment by MichaelKing1832** [comment]
Still present in Ghostery 8.7.6 with FF 104.0 on Win10x64 21H2 (19044.1889).

**Comment by chrmod** [comment]
@GRadziejewski can you please confirm if this is happening on 8.9.x ?

**Comment by philipp-classen** [comment]
8.9.5 has been released now.

**Comment by chrmod** [comment]
@MichaelKing1832 if possible, please confirm if the fix works for you.

At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!

**Comment by MichaelKing1832** [comment]
Not fixed. Still happening. Test URL: signon.ghostery.com

Form entry does not strip leading whitespace or trailing whitespace for the account email address.

Did not test for password entry either, but that is the same issue if present. Nobody has leading or trailing whitespace characters in their passwords. Too difficult to detect the problem to help users after a broken user input validator fails to detect and prevent this in the first place.

**Comment by philipp-classen** [comment]
For the server side UI tweaks, I created #973 

Note that the changes where for the extension UI (matching the steps in how to reproduce). We haven't changed anything on the server login. But my expectation is that in the extension UI, it should work now.

Regarding password fields, I would not attempt to truncate them. Whether it is a good idea or not, I would not be surprised if there are password in use with leading and trailing white spaces.

**Comment by MichaelKing1832** [comment]
I would counter that these alleged ghostery users you point to as justification for NOT fixing this usability issue don't exist,and never have.

Such Ghostery users (with leading whitespace in their email or password) do not exist now, as entries with trailing or leading whitspace are already invalid values, and are rejected today.

Users shouldn't be subjected to vague error messages, or get a poor user experience for making what is a common, foreseeable, entry mistake.

Windows "auto-select" often includes adjacent whitespace in cut-and-paste operations, something users do entering in credentials.

The fix (trimming leading and trailing whitespace from email and password before acceptance) makes Ghostery easier to use, and eliminates the "Entry rejected. Try again." UX anti-pattern currently implemented.
