### ISSUE TITLE
tracking redirect alert: redesign

### ISSUE THREAD

**Issue by mdsandu-zz** [ghostery/ghostery-extension#822]
the redesign aims to clarify the specific situation for the user, offer control over it and inform about the particular tracker.  

see new design here: https://www.figma.com/file/qHERAPVK1MBBMLWKqDufzf/Ghostery-Web-%5Bfinal-screens%5D?node-id=2042%3A35696

**Comment by smalluban** [comment]
The v10 does not have the redirect feature. Closing for now, we can re-open if needed.
