### ISSUE TITLE
Text from the Ad-Blocking on popup is trimmed.

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#842]
### Expected Behavior
After opening the main box and focusing the mouse cursor on the icon (left bottom corner), a pop-up with information about Ad-Blocking is visible, and the User can read the whole text.

### Actual Behavior
After opening the main box and focusing the mouse cursor on the icon (left bottom corner), a pop-up with information about Ad-Blocking is visible - the text on the pop-up is trimmed.
(Screenshots were added at the bottom.)

### Preconditions
- "Ghostery - Privacy Ad Blocker" should be installed.
- Open any page.

### Steps to Reproduce
1. Click on the Ghost near the address bar.
2. Move the mouse cursor to the icon - left bottom corner and wait for the pop-up

### Versions
+ Browser: Chrome
+ Version: 104.0.5112.102
+ Version of Ghostery Browser Extension - Privacy Ad Blocker: 8.8.0

For example:
![Ad-Blocking_PopUp_Trimmed](https://user-images.githubusercontent.com/40433708/186661980-f13605e6-e9e5-4ba7-95db-7cfd30f16aee.png)

**Comment by chrmod** [comment]
That must come from the fact that the Ad-Blocker and Anti-Tracking buttons have changed positions.
