### ISSUE TITLE
Ghostery Blocks the content.js file from JSON Formatter (Chrome Extension)

### ISSUE THREAD

**Issue by konqui** [ghostery/ghostery-extension#86]
### Description

Ghostery Blocks the content.js file from JSON Formatter (Chrome Extension)

### Expected Behavior 

A possibility to add scripts from other chrome extensions to a Whitelist.

### Actual Behavior 

The Json Formatter Extension is useless since all its functions are in that on content.js file which gets blocked. I think it must be blocked by one of the Entries in the Ad Categorie since those are the only ones I have set to block.  Right now I don't have the time to check one by one which exactly it is.

### Steps to Reproduce

1. Install Gostery Extension on Chrome
2. Block all Ads
![ad block](https://user-images.githubusercontent.com/782442/40783689-8532210e-64e3-11e8-91f8-ef1243846244.PNG)
3. Install JSON Formatter from Chrome Webstore https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa
4. Open any Page with RAW JSON Data
### Versions
+ Browser: Google Chrome Version 67.0.3396.62 (Offizieller Build) (64-Bit)
+ OS: Windows 7 Professional DE 64bit
+ Node: v8.9.4
+ NPM: 5.6.0

**Comment by christophertino** [comment]
I just tested this against Ghostery 8.2 and it appears to work fine for me.  Do you have a specific JSON url we could test?

**Comment by ludwo** [comment]
e.g.  https://jsonplaceholder.typicode.com/posts 
When I pause ghostery plugin, JSON is rendered correctly after page refresh.

**Comment by BonesyWonesy** [comment]
I'm running in to this issue as well. My solution was to remove Ghostery.   Formatted JSON is more important to me that what Ghostery provides.

**Comment by izedamo** [comment]
I have also been facing this same issue since a long time.

**Comment by creechy** [comment]
This still appears to be an issue. I am using Microsoft Edge Chromium 87.0.664.60 and Ghostery 8.5.4. I have tried a couple different JSON formatter extensions and they do not until I disabled the "purple box" per @christophertino's comment above. Its now at (Ghostery -> Settings -> Tracker Tally)

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
