### ISSUE TITLE
Synchronization failed when Adblocking is turned off

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#865]
Expected Behavior
After pressing "Update Now", synchronization should work and the latest version of DB should be downloaded.

Actual Behavior
After pressing "Update Now", there is the message "Update failed. Please try again later."

Prerequisites:
Install Ghostery Browser Extension in version 8.8.0.

Steps to Reproduce
1. Open the browser and turn OFF Adblocking.
2. Open the Ghostery Browser Extension box.
3. Open Settings / General Settings.
4. Press "Update now."
5. Wait for synchronization
![obraz](https://user-images.githubusercontent.com/40433708/189910699-27c0eabf-7468-4488-8a04-afe6964cd7dd.png)

**Comment by philipp-classen** [comment]
Confirmed.The update currently assumes the adblocker is enabled:
```
Uncaught (in promise) TypeError: L.modules.adblocker.background.adblocker is null
```
