### ISSUE TITLE
Simplify manifest host permissions

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#869]
To clarify that Ad-Blocking requires so called "wide host permissions" we have to load all content scripts on all pages. 

If we continue to load Trackers Preview just on google.*, Safari will list all those domains in the extension preference pages, which makes it look like we need permissions to google only. This is misleading and incorrect. We want users to understand that Ghostery needs access to all pages to block ads.

**Comment by marcoclg19** [comment]
Will there be a Chrome extension for Manifest V3?

**Comment by philipp-classen** [comment]
> Will there be a Chrome extension for Manifest V3?

@marcoclg19 Please let's keep this ticket on topic (the ticket is about an Apple issue). But yes, if Chrome shuts down Manifest V2, there will still be Ghostery for Chrome. You can already try out our Manifest V3 version here: https://github.com/ghostery/ghostery-extension/tree/main/extension-manifest-v3

If you have questions, you can also reach out to us on support@ghostery.com
