### ISSUE TITLE
Android Panel: Seetings - tooltips are cut 

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#882]
**Description**
Description of the "Ask me to confirm before visiting (...)" feature is cutted, it's not fully visible.

**Steps to Reproduce**
1. Open the browser
2. Click on the Ghostery icon
3. Click on the "Settings" button
4. Open "General Settings"
5. Open information about "Ask me to confirm before visiting (...)" by pressing "i" button.
![Screenshot_20220928-133441_Ghostery](https://user-images.githubusercontent.com/40433708/192771759-a69faa63-775e-4f97-8c5f-ef8002ef0cde.jpg)

Versions
Ghostery Browser 2022-09-27 / Build #2015906579

**Comment by smalluban** [comment]
Ghostery Browser migrated to extension v10. Feel free to re-open if the issue is still valid.
