### ISSUE TITLE
Ghostery.com don't send the "submit a tracker".

### ISSUE THREAD

**Issue by Nappsel** [ghostery/ghostery-extension#89]
For a month I can't send data about a new tracker through the site [ghostery.com](https://www.ghostery.com/submit-a-tracker/). Tell me, how else can i send this data to the ghostery team?

### Versions

+ Browser: Chrome 67
+ OS: Windows 10

**Comment by Aziz-Ghostery** [comment]
I'm able to reproduce, server error displayed:
There was an error trying to send your message. Please try again later.

Network console shows:
{into: "#wpcf7-f103-p9-o1", status: "spam",…}
into: "#wpcf7-f103-p9-o1"
message: "There was an error trying to send your message. Please try again later."
status: "spam"

**Comment by Aziz-Ghostery** [comment]
@Nappsel could you please clear your browser cache and try to submit the form again. Thanks

**Comment by Nappsel** [comment]
@Aziz-Ghostery, still can not send the form. :(

> There was an error trying to send your message. Please try again later.
