### ISSUE TITLE
Onboarding: remove double header from Privacy Policy

### ISSUE THREAD

**Issue by chrmod** [ghostery/ghostery-extension#892]
![IMG_B835C2C3AB8D-1](https://user-images.githubusercontent.com/1228153/195040341-21cb56f0-c939-45ac-ba3c-574bbe905b5a.jpeg)

**Comment by smalluban** [comment]
Fixed with https://github.com/ghostery/ghostery-extension/commit/5dd8cec20bcac659ec97283cbd55fdf496da8934
