### ISSUE TITLE
"Restrict site" does not block with Ad-blocking disabled

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#932]
Description
After turning OFF Ad-Blocking, Anti-Tracking and set website as a "Site restricted", on the website adverts are visible.

Steps to Reproduce
1. Open https://theverge.com
2. Open Ghostery and turn ON: ad-blocking, anti-tracking. Set website as a "Site restricted". Refresh the website.
3. Check the adverts.
![theverge com_GBE_ON_SiteRestr](https://user-images.githubusercontent.com/40433708/201666359-cbda35b6-9137-47d3-b157-1d45b16d9606.png)
4. Open Ghostery and turn OFF: ad-blocking, anti-tracking. Set website as a "Site restricted". Refresh the website.
5. Check the adverts.
![theverge com_GBE_OFF_SiteRestr](https://user-images.githubusercontent.com/40433708/201666533-d4e23484-4356-40a5-ab31-33a2a7f4fe47.png)

Expected Results:

Versions
Browser: Chrome 107.0.5304.110
OS: MacOS Monterey 13.0
GBE 8.9.5

Browser: Chrome 107.0.5300.89
OS: Windows 10 Pro 19044.2130
GBE 8.9.5

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
