### ISSUE TITLE
Options at bottom of options page need labels

### ISSUE THREAD

**Issue by mdinger** [ghostery/ghostery-extension#937]
### Description
Ghostery options page shows three options at the bottom but have no labels. I have no idea what these buttons do.

### Expected Behavior

The buttons need a label to know what they are.

### Versions

+ Browser: Firefox for Android 
+ OS: Android 13
+ Version: 8.9.5

![Screenshot_20221116-133014](https://user-images.githubusercontent.com/4156987/202264905-231d5b41-2a71-4fc9-90c9-7b97bd29f518.png)

**Comment by chrmod** [comment]
@mdinger thank you for pointing this out. We are in a process of designing a completely new Ghostery panel, you can be sure we will take fix this problem. Lets keep this issue open until new panel is ready.

At Ghostery we value contributions! Please reach out to support@ghostery.com with a link to this issue, so we can send you a coupon code to get access to Contributor extras.
We are happy to have you as a part of the Ghostery Contributors community!
