### ISSUE TITLE
Unverified account is logged out on new webpage

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#953]
Description
After logging into new unverified account, when User will open a new webpage - User will be logged out. 

Preconditions
New account which is not yet verified

Steps to Reproduce
1. Log into new account.
![obraz](https://user-images.githubusercontent.com/40433708/200559081-9dbdaa01-fa50-4899-bede-5c61a636b492.png)
![obraz](https://user-images.githubusercontent.com/40433708/200559324-b21433d5-9347-4eab-94f0-75a751a739e5.png)
2. Open website for example : https://cnn.com
3. Open Ghostery and check the User button
![obraz](https://user-images.githubusercontent.com/40433708/200559566-4397692f-d1f8-46ec-b166-3a137172f3ec.png)
![obraz](https://user-images.githubusercontent.com/40433708/200559644-4a2ddd07-510a-49f4-b817-cd9f463b8366.png)

Expected Results:
When User is logging in, the User should not be logged out during browsing the Internet.

Original: https://github.com/ghostery/user-account/issues/56

**Comment by smalluban** [comment]
The last platform migrated to v10.
