### ISSUE TITLE
Ghostery on Firefox (Desktop + Mobile) may start with all trackers being disabled

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#956]
It can happen that you install Firefox (on Desktop and Mobile), enable it, and then end with all tracking categories being disabled. That is not the expected behavior, since some categories such as advertising and site analytics should be enabled by default.

On Firefox, there is a path to reproduce:
* Install Ghostery
* Now Firefox will show the onboarding but also the Firefox specific popup asking whether the extension should be enabled in private mode
* If you enable Ghostery (finishing the onboarding), it will now start without blocking any trackers. It will work if you manually go into settings and select categories that should be blocked. 

It is not clear if the problem affects Chrome as well. It could be, but at least the aspect of having the popup asking about private mode is Firefox specific. That is why I'm marking it as Firefox for now, since only on Desktop Firefox, we have a reproducible path.

**Comment by philipp-classen** [comment]
Looks like it gets cleared once you answer the Firefox popup:
* Install Ghostery
* Enable Ghostery but do not interact with the Firefox popup
* Now in the UI, the default categories are enables
* Answer the Firefox popup
* Now all categories are disabled

**Comment by ghostwords** [comment]
Probably related: https://bugzilla.mozilla.org/show_bug.cgi?id=1558336

**Comment by smalluban** [comment]
The last platform migrated to v10.
