### ISSUE TITLE
Ghostery in Chrome is hiding Hyper Link ("Privacy Policy") in our site 

### ISSUE THREAD

**Issue by arokiadossarokiadoss** [ghostery/ghostery-extension#972]
### Description

Chrome Ghostery extension  is hiding the following link from the site footer causing legal issues. 
<li data-track_events="click" class="yCmsComponent disclaimer-link" data-track_data="{'click':'pageFooterLinkClick'}">
<a href="/en-us/privacy-policy" title="Privacy Policy" id="privacypolicy">Privacy Policy</a></li>

Note: issue doesnt happen in Safari Browser with Ghostery installed.

### Expected Behavior
The above mentioned html element should not be injected with CSS by Ghostery  preventing user from seeing it.

[What you expected to happen]
The above mentioned html element should not be injected with Ghostery CSS  preventing user from seeing it.
### Actual Behavior
The above mentioned html element is hidden by Ghostery by modifying the CSS
[What actually happened]
The above mentioned html element is hidden by Ghostery by modifying its  CSS
### Steps to Reproduce

STEP 1 : Open our site (https://www.rodanandfields.com/en-us/) in chrome browser with Ghostery installed - 
STEP 2: You will see that the hyperlink "Privacy Policy" in the page footer is hidden 

### Versions

+ Browser: Chrome
+ OS: All OS Mac , Windows 
+ Node:
+ NPM:

**Comment by chrmod** [comment]
Hi @arokiadossarokiadoss, thank you for reporting. 

Ghostery uses various community lists for content blocking, for example EasyList. Can you please check if the link is getting removed on other adblockers like uBlock Origin. 

We cannot access the page you have linked to, getting Access Denied error. Is it geo restricted?
![Uploading Screenshot 2022-12-19 at 10.01.13.png…]()

**Comment by arokiadossarokiadoss** [comment]
Hi, 
Our URL is not GEO restricted, please try again --> https://www.rodanandfields.com

I don't have any other adblocker installed other than Ghostery. Please note Safari with Ghostery is not causing this issue.
btw I cant access your screen shot.

**Comment by chrmod** [comment]
sorry, must have rushed with the image upload. you should be able to see the screenshot now.

Have tried multiple browser and I cannot access this page even with curl
```bash
curl https://www.rodanandfields.com/
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>

You don't have permission to access "http&#58;&#47;&#47;www&#46;rodanandfields&#46;com&#47;" on this server.<P>
Reference&#32;&#35;18&#46;6d645e68&#46;1671649371&#46;1cafb3d3
</BODY>
</HTML>
```

**Comment by arokiadossarokiadoss** [comment]
Curl call will not work as Akamai and our webserver is putting restriction. Call should be initiated from a Browser.

**Comment by wouter-vs** [comment]
I can confirm your issue.

We noticed something similar, we build a lot of shops using Shopware and by default they add a Privacy Policy checkbox in the checkout. When Ghostery is enabled this checkbox is hidden.
A piece of css is injected that hides a number of html elements with certain classes, in our case its the class ".privacy-notice".

This makes the checkout of a lot of shops running on Shopware unusable.
Please remove this injected css, this has nothing to do with blocking trackers. Showing these notices and asking for consent is required by law and in my personal opinion Ghostery has no business interfering with a websites html on this level.

This piece of css is injected.
```
[data-ad-width], [data-revive-zoneid], [id^="google_ads_iframe"], div[aria-label="Ads"], div[data-ad-targeting], div[data-native_ad], div[id^="dfp-ad-"], div[id^="ezoic-pub-ad-"], div[id^="yandex_ad"], div[id*="ScriptRoot"], a[onmousedown^="this.href='https://paid.outbrain.com/network/redir?"][target="_blank"], amp-embed[type="taboola"], display-ad-component, [data-test="cookie-banner"], app-cookies, app-cookies-consent, div[data-gdpr-consent-prompt], div[data-testid="cookie-policy-banner"], sibbo-cmp-layout, thor-cookies, div.cookie-alert, div.cookie-banner, div.cookie-consent, div.cookie-consent-modal, div.cookie-consent-popup, div.cookie-container, div.cookie-content, div.cookie-details, div.cookie-notice, div.cookie-overlay, div.cookie-wrapper, div.cookieBanner, div.cookieHolder, div.cookies-modal-container, div.cookies-visible, div.js-disclaimer, div.privacy-notice, div.v-cookie, div.with-cookie {
    display: none !important;
}
```

**Comment by arokiadossarokiadoss** [comment]
Hi Wouter-vs,
Thanks for your response. I believe this CSS is injected by Ghostery into the client browser when RF site accessed by Customer. In such cases how do i remove this injected css

**Comment by arokiadossarokiadoss** [comment]
> Sorry, must have rushed with the image upload. You should be able to see the screenshot now.
> 
> I'm on polish IP.
> 
> Have tried multiple browsers and I cannot access this page even with curl.
> 
> ```shell
> curl https://www.rodanandfields.com/
> <HTML><HEAD>
> <TITLE>Access Denied</TITLE>
> </HEAD><BODY>
> <H1>Access Denied</H1>
> 
> You don't have permission to access "http&#58;&#47;&#47;www&#46;rodanandfields&#46;com&#47;" on this server.<P>
> Reference&#32;&#35;18&#46;6d645e68&#46;1671649371&#46;1cafb3d3
> </BODY>
> </HTML>
> ```

Hi Chrmod, I am waiting for my Networks team to open access to your location. Please give us some time.

**Comment by ansgarbecker** [comment]
This is still an issue with various ecommerce pages. Here's a live Shopware page on which you can reproduce it: https://www.stabilo.com/de/ . Please use the "de" / german version, as the english one doesn't let you order products for some reason.

* put some product in your cart, e.g. from https://www.stabilo.com/de/stabilo-easyergo/on1189-4
* click "Weiter zur Kasse" (continue to checkout)
* click "Bestellung als Gast" (order as guest)
* fill out all required fields
* scroll down to the "Weiter" (continue) button and inspect the html right above the button:
  * `<div class="form-text privacy-notice">...<input type="checkbox"...` has a `display: none !important` rule from Ghostery
* try to click the "Weiter" button to complete the order - you can't, because the required "privacy-notice" checkbox is hidden.

Here's a screen of the hidden HTML checkbox:

![grafik](https://github.com/ghostery/ghostery-extension/assets/7986591/e264e79a-a6aa-4cd9-9b96-f55098f477a0)


We were having the same issue on die-beraterapotheke.de , only we have a workaround per plugin now. But in a default configuration Ghostery is blocking the user from buying.

We reported this to Shopware as well: https://issues.shopware.com/issues/NEXT-29983
But I think the bug is in Ghostery, not in Shopware.

Please consider making the CSS rule more specific, so you're not blocking users from buying.

**Comment by chrmod** [comment]
@ansgarbecker thank you for the report. This looks like a different issue (very similar in nature) and we definitely should tweak those rules. Let us test it as a broken page https://github.com/ghostery/broken-page-reports/issues/353

**Comment by smalluban** [comment]
Chrome platform migrated to v10. Feel free to re-open if the issue is still valid.
