### ISSUE TITLE
XMLs are not displayed properly in Firefox

### ISSUE THREAD

**Issue by philipp-classen** [ghostery/ghostery-extension#983]
When Ghostery is enabled, XML files are not displayed correctly. It affects Firefox 108, but not Chrome.

To reproduce, open https://whotracks.me/blog/feed.xml

![xml-display-bug](https://user-images.githubusercontent.com/1616509/212357641-cab6fc83-d543-4aca-9932-3913a9d02ba4.png)

* Left: Firefox without Ghostery
* Middle: Firefox with Ghostery 8.9.8 (Ghostery breaks the styling)
* Right: Chromium with Ghostery

**Comment by NinkevdVeen** [comment]
I can also confirm this happens. In my case on FF 111.

**Comment by philipp-classen** [comment]
@NinkevdVeen I was now looking into again. First I was also able to reproduce when I tested on an existing, older profile. Then I tried to disable adblocking, anti-tracking and Never-Consent and eventually it worked and then I could not reproduce again, even when turning the options on again. I'm now also unable to reproduce on a fresh profile.

@GRadziejewski Are you able to still reproduce the problem with a fresh profile? I wonder if there was a problem that now only exists indirectly through caches?

**Comment by NinkevdVeen** [comment]
@philipp-classen thank you for checking. with the link provided in OP I still have the issue.
What is good to note is that it doesn't happen right away. I can see the expected XML format. I go to another tab and go back and the formatting disappears. Sometimes it happens when I wait long enough, but the tabbing is consistent behavior for testing. Maybe this extra info helps?

**Comment by philipp-classen** [comment]
@NinkevdVeen Confirmed. I also saw the behavior now: first it formats properly, but when I leave it open the layout eventually breaks. Switching tabs seems to trigger it reliably.

**Comment by philipp-classen** [comment]
Looks like its Never Consent:
```
<rss version="2.0">
<style id="autoconsent-prehide"/>
```

This is how the RSS feed first looks and then it goes away. The original content is:
```
<rss version="2.0">
<channel>
<title>WhoTracksMe blog</title>
<link>https://whotracks.me/blog.html</link>
<description>By the Ghostery tech team</description>
```

`autoconsent-prehide` must be coming from the auto-consent library.

**Comment by philipp-classen** [comment]
This is how it first looks in Firefox (notice the `<style id="autoconsent-prehide"/>`):
![before](https://user-images.githubusercontent.com/1616509/226405449-68a0f74a-3f8f-438b-944e-b2414a816c25.png)

and eventually it will turn into this:
![after](https://user-images.githubusercontent.com/1616509/226405705-0e7e0e61-e183-4b7a-a28e-6ad1c2f6cfa8.png)

**Comment by philipp-classen** [comment]
Affects also the Manifest V3 code. To reproduce from a fresh profile, you have to visit first a page that triggers Never Consent and select "on all pages". Then the test link will trigger the problem there, too.

**Comment by philipp-classen** [comment]
A fix will be included in the upcoming releases.

**Comment by GRadziejewski** [comment]
Version 8.9.14 is live. 
On version .14 it looks like this:
![image](https://user-images.githubusercontent.com/40433708/232455219-484293fd-df1c-4b69-bb6f-acd1744b55a3.png)


On version .13 it looks like this:
![image](https://user-images.githubusercontent.com/40433708/232455360-97bfa01c-79dc-4805-b020-fdb10cbae5d9.png)

So I think that we can call it fixed and I'm closing this ticket.
@NinkevdVeen if you can still see that issue, please let me know.
CC @philipp-classen
