### ISSUE TITLE
[quesition]: manifest v3 for Chromium

### ISSUE THREAD

**Issue by tachibana-shin** [ghostery/ghostery-extension#998]
### Description

Are there any plans for a utility to make manifest v3 support Chromium browsers or is anyone working on it?. If not I would really like to create a fork as Chrome has stopped updating manifests v2 now

### Expected Behavior

version manifest v3 work on Chrome

**Comment by chrmod** [comment]
Hi @tachibana-shin - yes, we are working on it. We have functional MV3 implementation here https://github.com/ghostery/ghostery-extension/tree/main/extension-manifest-v3 - but there is still a lot work to done with features like anti-tracking.
